### ISSUE TITLE
Countly is not (yet) world's best mobile analytics platform

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#1]

**Comment by davidmann4** [comment]
this report is kinda old - still relevant? I would like to use it for an app.

**Comment by gorkem-cetin** [comment]
David, this is basically a "fun Github issue" - showing that we are not still number one, but getting there as we conquer the world one app at a time. 

Lately G2 has stated that Countly is #4 - see report here: 

https://www.g2crowd.com/categories/mobile-app-analytics

**Comment by davidmann4** [comment]
thanks for the link, we previously used mixpanel and really liked this feature:
https://mixpanel.com/notifications/

are there any plugins to send automated campaigns like "hey you downloaded but never signed up" with clicky? any tools you can recommed?

**Comment by gorkem-cetin** [comment]
After 4 years, we have done a lot of things:

- Countly is now used by 4 of 10 world's biggest brands: MS, Samsung, Verizon and AT&T. 
- It's been used by more than 13.000 apps worldwide
- We not only have mobile, but web and desktop analytics as well.
- We are featured by Gartner and several other independent consultancy companies
- The Countly Analytics and Marketing SDK has become increasingly popular, tracking more than 1,200,000,000 installed applications worldwide, from Android to iOS to Windows Phone.
- Countly has become the third most used push notifications SDK in the world (according to SafeDK)
- Countly has made a huge leap forward to become the seventh most used Android analytics SDK, just after such massive players as Google, Amazon and Flurry (according to Mobbo)
- Our Github repo has been starred more than 2950 times, and forked more than 1000 times, making Countly one of most active open source analytics projects.

We are very proud of what we have done till now. Countly is quickly becoming the defacto standard for many companies when it comes to analytics, but it's just the beginning. 

Watch us grow!
