### ISSUE TITLE
countly-server runs as root

### ISSUE THREAD

**Issue by milgner** [Countly/countly-server#102]
The supervisord configuration specifies `user=root` which in itself is doubtful whether it's a good idea but could be tolerated.
But then, the application user isn't overriden in neither `program:countly-dashboard` or `program:countly-api` sections.
Right now I don't have access to Ubuntu or RHEL systems to update the installer scripts but as I'm currently modifying the configuration files in this regard, I'd be willing to contribute a PR if you like.
Do you have a CI system to test these changes on your target platforms?

**Comment by ar2rsawseen** [comment]
Based on provided example implemented installing countly as another user here: https://github.com/Countly/countly-server/commit/89c950d20afc2e3e2d42a2fb6b3e5ed1a9d4f96c

You still need to run install script as root though
