### ISSUE TITLE
countly install fail, need help

### ISSUE THREAD

**Issue by zfavourite99** [Countly/countly-server#1028]
my system info:
#head -n 1 /etc/issue  => CentOS release 6.10 (Final)

countly version is 19.08

install log:
` 57600K .......... .......... .......... .......... .......... 99%  124K 1s
 57650K .......... .......... .......... .......... .......... 99%  222K 1s
 57700K .......... .......... .......... .......... .......... 99%  165K 1s
 57750K .......... .......... .......... .......... .......... 99%  287K 1s
 57800K .......... .......... .......... .......... .......... 99%  234K 0s
 57850K .......... .......... .......... .......... .......... 99%  222K 0s
 57900K .......... .......... .......... .......... .......... 99%  206K 0s
 57950K ...                                                   100% 27.5M=3m15s

2019-08-20 16:01:07 (298 KB/s) - “google-chrome-stable_current_x86_64.rpm” saved [59344318/59344318]

Downloaded google-chrome-stable-76.0.3809.100-1.x86_64.rpm google-chrome-stable_current_x86_64.rpm
error: not an rpm package
error: google-chrome-stable-76.0.3809.100-1.x86_64.rpm: not an rpm package (or package manifest): 
Installing the required font dependencies.
Loaded plugins: security
Setting up Install Process
http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 3 seconds')
Trying other mirror.
Package fontconfig-2.8.0-5.el6.x86_64 already installed and latest version
Package fontpackages-filesystem-1.41-1.1.el6.noarch already installed and latest version
Package ipa-gothic-fonts-003.02-4.2.el6.noarch already installed and latest version
Package xorg-x11-fonts-100dpi-7.2-11.el6.noarch already installed and latest version
Package xorg-x11-fonts-75dpi-7.2-11.el6.noarch already installed and latest version
Package xorg-x11-fonts-misc-7.2-11.el6.noarch already installed and latest version
Package xorg-x11-fonts-Type1-7.2-11.el6.noarch already installed and latest version
Package xorg-x11-utils-7.5-14.el6.x86_64 already installed and latest version
Nothing to do
--2019-08-20 16:01:16--  http://mirror.centos.org/centos/7/os/x86_64/Packages/glibc-2.17-260.el7.x86_64.rpm
Resolving mirror.centos.org... 103.27.60.52, 2604:1380:3000:2800::1
Connecting to mirror.centos.org|103.27.60.52|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3804652 (3.6M) [application/x-rpm]
Saving to: “glibc.rpm”

     0K .......... .......... .......... .......... ..........  1% 57.6K 64s
    50K .......... .......... .......... .......... ..........  2% 43.2K 73s
   100K .......... .......... .......... .......... ..........  4% 17.3K 1m57s
   150K .......... .......... .......... .......... ..........  5% 9.23K 3m2s
   200K .......... .......... .......... .......... ..........  6% 11.0K 3m26s
   250K .......... .......... .......... .......... ..........  8% 14.8K 3m28s
   300K .......... .......... .......... .......... ..........  9% 10.2K 3m43s
   350K .......... .......... .......... .......... .......... 10% 10.2K 3m53s
   400K .......... .......... .......... .......... .......... 12% 6.97K 4m16s
   450K .......... .......... .......... .......... .......... 13% 10.3K 4m18s
   500K .......... .......... .......... .......... .......... 14% 8.23K 4m26s
   550K .......... .......... .......... .......... .......... 16% 6.15K 4m42s
   600K .......... .......... .......... .......... .......... 17% 8.35K 4m44s
   650K .......... .......... .......... .......... .......... 18% 14.6K 4m34s
   700K .......... .......... .......... .......... .......... 20% 11.9K 4m29s
   750K .......... .......... .......... .......... .......... 21% 7.57K 4m32s
   800K .......... .......... .......... .......... .......... 22% 21.6K 4m19s
   850K .......... .......... .......... .......... .......... 24% 9.55K 4m17s
   900K .......... .......... .......... .......... .......... 25% 5.86K 4m24s
   950K .......... .......... .......... .......... .......... 26% 7.26K 4m25s
  1000K .......... .......... .......... .......... .......... 28% 7.48K 4m24s
  1050K .......... .......... .......... .......... .......... 29% 17.8K 4m14s
  1100K .......... .......... .......... .......... .......... 30% 10.8K 4m9s
  1150K .......... .......... .......... .......... .......... 32% 9.20K 4m5s
  1200K .......... .......... .......... .......... .......... 33% 11.0K 4m0s
  1250K .......... .......... .......... .......... .......... 34% 9.40K 3m56s
  1300K .......... .......... .......... .......... .......... 36% 12.6K 3m49s
  1350K .......... .......... .......... .......... .......... 37% 12.0K 3m43s
  1400K .......... .......... .......... .......... .......... 39% 7.16K 3m42s
  1450K .......... .......... .......... .......... .......... 40% 19.2K 3m34s
  1500K .......... .......... .......... .......... .......... 41% 8.08K 3m31s
  1550K .......... .......... .......... .......... .......... 43% 7.71K 3m28s
  1600K .......... .......... .......... .......... .......... 44% 8.48K 3m24s
  1650K .......... .......... .......... .......... .......... 45% 8.47K 3m20s
  1700K .......... .......... .......... .......... .......... 47% 17.3K 3m13s
  1750K .......... .......... .......... .......... .......... 48% 8.16K 3m10s
  1800K .......... .......... .......... .......... .......... 49% 6.17K 3m8s
  1850K .......... .......... .......... .......... .......... 51% 4.62K 3m8s
  1900K .......... .......... .......... .......... .......... 52% 4.59K 3m8s
  1950K .......... .......... .......... .......... .......... 53% 12.0K 3m2s
  2000K .......... .......... .......... .......... .......... 55% 10.7K 2m56s
  2050K .......... .......... .......... .......... .......... 56% 8.85K 2m51s
  2100K .......... .......... .......... .......... .......... 57% 7.53K 2m47s
  2150K .......... .......... .......... .......... .......... 59% 7.69K 2m42s
  2200K .......... .......... .......... .......... .......... 60% 15.2K 2m36s
  2250K .......... .......... .......... .......... .......... 61% 18.8K 2m29s
  2300K .......... .......... .......... .......... .......... 63% 8.22K 2m24s
  2350K .......... .......... .......... .......... .......... 64% 6.98K 2m20s
  2400K .......... .......... .......... .......... .......... 65% 9.72K 2m14s
  2450K .......... .......... .......... .......... .......... 67% 4.75K 2m12s
  2500K .......... .......... .......... .......... .......... 68% 8.18K 2m6s
  2550K .......... .......... .......... .......... .......... 69% 10.5K 2m1s
  2600K .......... .......... .......... .......... .......... 71% 9.43K 1m55s
  2650K .......... .......... .......... .......... .......... 72% 15.5K 1m49s
  2700K .......... .......... .......... .......... .......... 74% 13.1K 1m43s
  2750K .......... .......... .......... .......... .......... 75% 18.9K 97s
  2800K .......... .......... .......... .......... .......... 76% 10.0K 92s
  2850K .......... .......... .......... .......... .......... 78% 6.27K 87s
  2900K .......... .......... .......... .......... .......... 79% 17.4K 81s
  2950K .......... .......... .......... .......... .......... 80% 12.3K 75s
  3000K .......... .......... .......... .......... .......... 82% 8.72K 70s
  3050K .......... .......... .......... .......... .......... 83% 7.33K 65s
  3100K .......... .......... .......... .......... .......... 84% 8.24K 60s
  3150K .......... .......... .......... .......... .......... 86% 10.8K 55s
  3200K .......... .......... .......... .......... .......... 87% 12.0K 49s
  3250K .......... .......... .......... .......... .......... 88% 9.61K 44s
  3300K .......... .......... .......... .......... .......... 90% 9.54K 39s
  3350K .......... .......... .......... .......... .......... 91% 19.2K 33s
  3400K .......... .......... .......... .......... .......... 92% 13.3K 28s
  3450K .......... .......... .......... .......... .......... 94% 14.8K 22s
  3500K .......... .......... .......... .......... .......... 95% 21.6K 17s
  3550K .......... .......... .......... .......... .......... 96% 19.2K 12s
  3600K .......... .......... .......... .......... .......... 98% 16.1K 7s
  3650K .......... .......... .......... .......... .......... 99% 14.8K 2s
  3700K .......... .....                                      100% 23.2K=6m16s

2019-08-20 16:07:34 (9.88 KB/s) - “glibc.rpm” saved [3804652/3804652]

Extracting glibc...
--2019-08-20 16:07:35--  http://mirror.centos.org/centos/7/os/x86_64/Packages/util-linux-2.23.2-59.el7.x86_64.rpm
Resolving mirror.centos.org... 111.90.139.14, 2604:1380:3000:2800::1
Connecting to mirror.centos.org|111.90.139.14|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2070452 (2.0M) [application/x-rpm]
Saving to: “util-linux.rpm”

     0K .......... .......... .......... .......... ..........  2% 21.7K 91s
    50K .......... .......... .......... .......... ..........  4% 16.3K 1m43s
   100K .......... .......... .......... .......... ..........  7% 16.4K 1m45s
   150K .......... .......... .......... .......... ..........  9% 12.3K 1m54s
   200K .......... .......... .......... .......... .......... 12% 8.36K 2m11s
   250K .......... .......... .......... .......... .......... 14% 6.97K 2m27s
   300K .......... .......... .......... .......... .......... 17% 8.31K 2m31s
   350K .......... .......... .......... .......... .......... 19% 8.91K 2m31s
   400K .......... .......... .......... .......... .......... 22% 12.3K 2m24s
   450K .......... .......... .......... .......... .......... 24% 9.23K 2m22s
   500K .......... .......... .......... .......... .......... 27% 9.93K 2m19s
   550K .......... .......... .......... .......... .......... 29% 7.35K 2m19s
   600K .......... .......... .......... .......... .......... 32% 8.62K 2m16s
   650K .......... .......... .......... .......... .......... 34% 8.58K 2m13s
   700K .......... .......... .......... .......... .......... 37% 10.4K 2m7s
   750K .......... .......... .......... .......... .......... 39% 12.9K 2m0s
   800K .......... .......... .......... .......... .......... 42% 6.99K 1m59s
   850K .......... .......... .......... .......... .......... 44% 5.15K 1m59s
   900K .......... .......... .......... .......... .......... 46% 4.43K 2m1s
   950K .......... .......... .......... .......... .......... 49% 8.03K 1m56s
  1000K .......... .......... .......... .......... .......... 51% 2.62K 2m3s
  1050K .......... .......... .......... .......... .......... 54% 2.85K 2m6s
  1100K .......... .......... .......... .......... .......... 56% 1.72K 2m16s
  1150K .......... .......... .......... .......... .......... 59% 1.58K 2m24s
  1200K .......... .......... .......... .......... .......... 61% 1.54K 2m30s
  1250K .......... .......... .......... .......... .......... 64% 2.54K 2m26s
  1300K .......... .......... .......... .......... .......... 66% 1.48K 2m28s
  1350K .......... .......... .......... .......... .......... 69% 9.98K 2m14s
  1400K .......... .......... .......... .......... .......... 71% 12.3K 2m1s
  1450K .......... .......... .......... .......... .......... 74% 6.79K 1m49s
  1500K .......... .......... .......... .......... .......... 76% 9.94K 97s
  1550K .......... .......... .......... .......... .......... 79% 10.2K 85s
  1600K .......... .......... .......... .......... .......... 81% 8.60K 74s
  1650K .......... .......... .......... .......... .......... 84% 5.14K 64s
  1700K .......... .......... .......... .......... .......... 86% 10.3K 53s
  1750K .......... .......... .......... .......... .......... 89% 5.87K 43s
  1800K .......... .......... .......... .......... .......... 91% 7.15K 33s
  1850K .......... .......... .......... .......... .......... 93% 14.4K 23s
  1900K .......... .......... .......... .......... .......... 96% 8.31K 14s
  1950K .......... .......... .......... .......... .......... 98% 8.56K 4s
  2000K .......... .......... .                               100% 16.0K=6m16s

2019-08-20 16:13:52 (5.38 KB/s) - “util-linux.rpm” saved [2070452/2070452]

Extracting util-linux...
--2019-08-20 16:13:54--  http://mirror.centos.org/centos/7/os/x86_64/Packages/libmount-2.23.2-59.el7.x86_64.rpm
Resolving mirror.centos.org... 147.75.93.107, 2401:78c0::10
Connecting to mirror.centos.org|147.75.93.107|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 186596 (182K) [application/x-rpm]
Saving to: “libmount.rpm”

     0K .......... .......... .......... .......... .......... 27% 13.8K 10s
    50K .......... .......... .......... .......... .......... 54% 8.66K 8s
   100K .......... .......... .......... .......... .......... 82% 11.8K 3s
   150K .......... .......... .......... ..                   100% 21.3K=15s

2019-08-20 16:14:12 (12.0 KB/s) - “libmount.rpm” saved [186596/186596]

Extracting libmount...
--2019-08-20 16:14:13--  http://mirror.centos.org/centos/7/os/x86_64/Packages/libblkid-2.23.2-59.el7.x86_64.rpm
Resolving mirror.centos.org... 147.75.93.107, 2401:78c0::10
Connecting to mirror.centos.org|147.75.93.107|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 184844 (181K) [application/x-rpm]
Saving to: “libblkid.rpm”

     0K .......... .......... .......... .......... .......... 27% 22.7K 6s
    50K .......... .......... .......... .......... .......... 55% 9.33K 6s
   100K .......... .......... .......... .......... .......... 83% 11.6K 2s
   150K .......... .......... ..........                      100% 13.2K=14s

2019-08-20 16:14:28 (12.7 KB/s) - “libblkid.rpm” saved [184844/184844]

Extracting libblkid...
--2019-08-20 16:14:29--  http://mirror.centos.org/centos/7/os/x86_64/Packages/libuuid-2.23.2-59.el7.x86_64.rpm
Resolving mirror.centos.org... 160.116.15.22, 2604:1380:3000:2800::1
Connecting to mirror.centos.org|160.116.15.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84248 (82K) [application/x-rpm]
Saving to: “libuuid.rpm”

     0K .......... .......... .......... .......... .......... 60% 62.5K 1s
    50K .......... .......... .......... ..                   100%  105M=0.8s

2019-08-20 16:14:30 (103 KB/s) - “libuuid.rpm” saved [84248/84248]

Extracting libuuid...
--2019-08-20 16:14:31--  http://mirror.centos.org/centos/7/os/x86_64/Packages/libselinux-2.5-14.1.el7.x86_64.rpm
Resolving mirror.centos.org... 160.116.15.22, 2604:1380:3000:2800::1
Connecting to mirror.centos.org|160.116.15.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 165932 (162K) [application/x-rpm]
Saving to: “libselinux.rpm”

     0K .......... .......... .......... .......... .......... 30% 64.8K 2s
    50K .......... .......... .......... .......... .......... 61% 97.1K 1s
   100K .......... .......... .......... .......... .......... 92% 18.3K 0s
   150K .......... ..                                         100% 22970G=4.0s

2019-08-20 16:14:36 (40.3 KB/s) - “libselinux.rpm” saved [165932/165932]

Extracting libselinux...
--2019-08-20 16:14:37--  http://mirror.centos.org/centos/7/os/x86_64/Packages/pcre-8.32-17.el7.x86_64.rpm
Resolving mirror.centos.org... 160.116.15.22, 2604:1380:3000:2800::1
Connecting to mirror.centos.org|160.116.15.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 432020 (422K) [application/x-rpm]
Saving to: “pcre.rpm”

     0K .......... .......... .......... .......... .......... 11% 65.5K 6s
    50K .......... .......... .......... .......... .......... 23% 98.3K 4s
   100K .......... .......... .......... .......... .......... 35% 65.5K 4s
   150K .......... .......... .......... .......... .......... 47% 40.0K 4s
   200K .......... .......... .......... .......... .......... 59% 27.7K 4s
   250K .......... .......... .......... .......... .......... 71% 15.6K 3s
   300K .......... .......... .......... .......... .......... 82% 28.0K 2s
   350K .......... .......... .......... .......... .......... 94% 23.4K 1s
   400K .......... .......... .                               100% 28.7K=13s

2019-08-20 16:14:50 (32.5 KB/s) - “pcre.rpm” saved [432020/432020]

Extracting pcre...
Loaded plugins: security
Setting up Install Process
http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 3 seconds')
Trying other mirror.
Package gcc-4.4.7-23.el6.x86_64 already installed and latest version
Package gcc-c++-4.4.7-23.el6.x86_64 already installed and latest version
Package 1:make-3.81-23.el6.x86_64 already installed and latest version
Package autoconf-2.63-5.1.el6.noarch already installed and latest version
Package automake-1.11.1-4.el6.noarch already installed and latest version
Nothing to do
/tools/countly/countly-server-19.08/bin/countly/bin/scripts/install-google-chrome.sh: line 235: chrome: command not found
Linking issues were encountered, attempting to patch the  executable.
--2019-08-20 16:14:55--  https://github.com/NixOS/patchelf/archive/0.9.tar.gz
Resolving github.com... 52.74.223.119
Connecting to github.com|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/NixOS/patchelf/tar.gz/0.9 [following]
--2019-08-20 16:14:56--  https://codeload.github.com/NixOS/patchelf/tar.gz/0.9
Resolving codeload.github.com... 54.251.140.56
Connecting to codeload.github.com|54.251.140.56|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 96859 (95K) [application/x-gzip]
Saving to: “0.9.tar.gz”

     0K .......... .......... .......... .......... .......... 52%  223K 0s
    50K .......... .......... .......... .......... ....      100%  199K=0.4s

2019-08-20 16:14:58 (211 KB/s) - “0.9.tar.gz” saved [96859/96859]

/tmp/google-chrome-installation/patchelf-0.9 /tmp/google-chrome-installation /tools/countly/countly-server-19.08/bin
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --warnings=all 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force --warnings=all
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing --warnings=all
configure.ac:6: installing `build-aux/compile'
configure.ac:4: installing `build-aux/install-sh'
configure.ac:4: installing `build-aux/missing'
src/Makefile.am: installing `build-aux/depcomp'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
Setting page size to 4096
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating patchelf.spec
config.status: executing depfiles commands
Making all in src
make[1]: Entering directory `/tmp/google-chrome-installation/patchelf-0.9/src'
g++ -DPACKAGE_NAME=\"patchelf\" -DPACKAGE_TARNAME=\"patchelf\" -DPACKAGE_VERSION=\"0.9\" -DPACKAGE_STRING=\"patchelf\ 0.9\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"patchelf\" -DVERSION=\"0.9\" -DPAGESIZE=4096 -I.    -Wall -g -O2 -MT patchelf.o -MD -MP -MF .deps/patchelf.Tpo -c -o patchelf.o patchelf.cc
mv -f .deps/patchelf.Tpo .deps/patchelf.Po
g++ -Wall -g -O2   -o patchelf patchelf.o  
make[1]: Leaving directory `/tmp/google-chrome-installation/patchelf-0.9/src'
Making all in tests
make[1]: Entering directory `/tmp/google-chrome-installation/patchelf-0.9/tests'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/tmp/google-chrome-installation/patchelf-0.9/tests'
make[1]: Entering directory `/tmp/google-chrome-installation/patchelf-0.9'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/tmp/google-chrome-installation/patchelf-0.9'
stat: No such file or directory
stat: No such file or directory
sed: can't read /opt/google/chrome/google-chrome: No such file or directory
Attempted experimental patching of Chrome to use a relocated glibc version.
/tools/countly/countly-server-19.08/bin/countly/bin/scripts/install-google-chrome.sh: line 255: /usr/bin/google-chrome-stable: No such file or directory
Installation has failed.
Please email contact@intoli.com with the details of your operating system.
If you're using using AWS, please include the AMI identifier for the instance.`

i dose not understand why download el7 package to centos6? maybe el6? 
in above log i see :
Extracting libselinux...
--2019-08-20 16:14:37--  http://mirror.centos.org/centos/7/os/x86_64/Packages/pcre-8.32-17.el7.x86_64.rpm

**Comment by ar2rsawseen** [comment]
@kaanklky can you check this, when you have time?

**Comment by kaanklky** [comment]
Hi @zfavourite99,
Is your server in China?

**Comment by zfavourite99** [comment]
@kaanklky YES, I'm in China

**Comment by kaanklky** [comment]
@zfavourite99 
You can try to install with up-to-date version of this repo after PR merged.

**Comment by zfavourite99** [comment]
@kaanklky thank you very much. that error is fixed. but there have a new error:

`changing mode of /usr/local/lib/python2.7/lib-dynload/grp.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/operator.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/zlib.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/cStringIO.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/_csv.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/parser.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/_codecs_hk.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/gdbm.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/_hotshot.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/_testcapi.so to 755
changing mode of /usr/local/lib/python2.7/lib-dynload/ to 755
running install_scripts
changing mode of /usr/local/bin/idle to 755
changing mode of /usr/local/bin/smtpd.py to 755
changing mode of /usr/local/bin/2to3 to 755
changing mode of /usr/local/bin/pydoc to 755
running install_egg_info
Removing /usr/local/lib/python2.7/lib-dynload/Python-2.7.10-py2.7.egg-info
Writing /usr/local/lib/python2.7/lib-dynload/Python-2.7.10-py2.7.egg-info
rm /usr/local/lib/python2.7/lib-dynload/_sysconfigdata.py*
/usr/bin/install -c -m 644 ./Misc/python.man \
                /usr/local/share/man/man1/python2.7.1
if test "xno" != "xno"  ; then \
                case no in \
                        upgrade) ensurepip="--altinstall --upgrade --no-default-pip" ;; \
                        install|*) ensurepip="--altinstall --no-default-pip" ;; \
                esac; \
                 ./python -E -m ensurepip \
                        $ensurepip --root=/ ; \
        fi
Loaded plugins: security
Setting up Install Process
Package python-pip-7.1.0-1.el6.noarch already installed and latest version
Nothing to do
--2019-08-26 16:39:09--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io... 151.101.108.175, 2a04:4e42:1a::175
Connecting to bootstrap.pypa.io|151.101.108.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1775417 (1.7M) [text/x-python]
Saving to: “get-pip.py.1”

100%[===========================================================================================================================================================================================================>] 1,775,417   21.1K/s   in 93s     

2019-08-26 16:40:42 (18.7 KB/s) - “get-pip.py.1” saved [1775417/1775417]

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting pip
  Downloading http://mirrors.aliyun.com/pypi/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl (1.4MB)
     |████████████████████████████████| 1.4MB 2.1MB/s 
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.2.3
Loaded plugins: security
Setting up Install Process
Package python-meld3-0.6.7-1.el6.x86_64 already installed and latest version
Nothing to do
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting supervisor
  Downloading http://mirrors.aliyun.com/pypi/packages/a5/27/03ee384818f4fc5f678743bb20ac49c5b4fc9f531bd404dec4b61a8b5d42/supervisor-4.0.4-py2.py3-none-any.whl (296kB)
     |████████████████████████████████| 307kB 1.4MB/s 
Collecting meld3
  Downloading http://mirrors.aliyun.com/pypi/packages/b6/ae/e6d731e4b9661642c1b20591d8054855bb5b8281cbfa18f561c2edd783f7/meld3-1.0.2-py2.py3-none-any.whl
Installing collected packages: meld3, supervisor
Successfully installed meld3-1.0.2 supervisor-4.0.4
Loaded plugins: security
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package sendmail.x86_64 0:8.14.4-9.el6_8.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================================================================================================================================================
 Package                                                    Arch                                                     Version                                                            Repository                                              Size
=====================================================================================================================================================================================================================================================
Installing:
 sendmail                                                   x86_64                                                   8.14.4-9.el6_8.1                                                   base                                                   717 k

Transaction Summary
=====================================================================================================================================================================================================================================================
Install       1 Package(s)

Total download size: 717 k
Installed size: 1.5 M
Downloading Packages:
sendmail-8.14.4-9.el6_8.1.x86_64.rpm                                                                                                                                                                                          | 717 kB     00:00     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.
** Found 14 pre-existing rpmdb problem(s), 'yum check' output follows:
device-mapper-event-1.02.79-8.el6.x86_64 has missing requires of device-mapper = ('0', '1.02.79', '8.el6')
device-mapper-event-1.02.79-8.el6.x86_64 has missing requires of device-mapper-event-libs = ('0', '1.02.79', '8.el6')
device-mapper-event-1.02.117-12.el6_9.1.x86_64 is a duplicate with device-mapper-event-1.02.79-8.el6.x86_64
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of libappindicator3.so.1()(64bit)
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of libatk-bridge-2.0.so.0()(64bit)
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of libatspi.so.0()(64bit)
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of libc.so.6(GLIBC_2.14)(64bit)
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of libc.so.6(GLIBC_2.15)(64bit)
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of libc.so.6(GLIBC_2.16)(64bit)
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of liberation-fonts
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of libgdk-3.so.0()(64bit)
google-chrome-stable-76.0.3809.100-1.x86_64 has missing requires of libgtk-3.so.0()(64bit)
lvm2-2.02.100-8.el6.x86_64 has missing requires of lvm2-libs = ('0', '2.02.100', '8.el6')
lvm2-2.02.143-12.el6_9.1.x86_64 is a duplicate with lvm2-2.02.100-8.el6.x86_64
  Installing : sendmail-8.14.4-9.el6_8.1.x86_64                                                                                                                                                                                                  1/1 
  Verifying  : sendmail-8.14.4-9.el6_8.1.x86_64                                                                                                                                                                                                  1/1 

Installed:
  sendmail.x86_64 0:8.14.4-9.el6_8.1                                                                                                                                                                                                                 

Complete!
Starting sendmail:                                         [  OK  ]
Starting sm-client:                                        [  OK  ]
updating gcc to devtoolset-2...
Loaded plugins: security
Setting up Install Process
Package wget-1.12-10.el6.x86_64 already installed and latest version
Nothing to do
--2019-08-26 16:43:58--  http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo
Resolving linuxsoft.cern.ch... 188.185.97.23, 137.138.120.95, 137.138.52.72, ...
Connecting to linuxsoft.cern.ch|188.185.97.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1587 (1.5K)
Saving to: “/etc/yum.repos.d/slc6-devtoolset.repo”

100%[===========================================================================================================================================================================================================>] 1,587       6.91K/s   in 0.2s    

2019-08-26 16:43:59 (6.91 KB/s) - “/etc/yum.repos.d/slc6-devtoolset.repo” saved [1587/1587]

Loaded plugins: security
Setting up Install Process
http://linuxsoft.cern.ch/cern/devtoolset/slc6X/x86_64/yum/devtoolset/repodata/repomd.xml: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2001:1458:d00:1b::94: Network is unreachable"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: slc6-devtoolset. Please verify its path and try again
[root@iZwz95wvlhb3mr6848q1zjZ bin]# ls
backup  commands  config  countly.install_rhel.sh  countly.install.sh  countly.install_travis.sh  countly.install_ubuntu.sh  installer.sh  README.md  scripts  upgrade`

**Comment by zfavourite99** [comment]
@ar2rsawseen I can not reopen this issue, so @you .

**Comment by kaanklky** [comment]
> @ar2rsawseen I can not reopen this issue, so @ you .

It is because of your routing table or DNS preferences; you can try to run `echo "ip_resolve=4" >> /etc/yum.conf` to fore yum to use IPv4 and re-install Countly.

**Comment by zfavourite99** [comment]
run `echo "ip_resolve=4" >> /etc/yum.conf` not work. I add `137.138.120.95 linuxsoft.cern.ch` to /etc/hosts that resolved. now install success. thanks.
