### ISSUE TITLE
run countly install script, libc.so.6 linked file changed

### ISSUE THREAD

**Issue by zfavourite99** [Countly/countly-server#1039]
my system info:
#head -n 1 /etc/issue => CentOS release 6.10 (Final)

countly version is github master

when I run the countly.install_rhel.sh script, my libc.so.6 linked file changed.
by default libc.so.6 linked to libc-2.12.so, I update the libc version to 2.17, then I linked the libc.so.6 to libc-2.17.so, but after I run the countly.install_rhel.sh, libc.so.6 linked to libc-2.12.so.

**Comment by ar2rsawseen** [comment]
Not sure if it is related, but we do install specific version g++ and link it to compile push binaries

**Comment by ar2rsawseen** [comment]
@kaanklky

**Comment by kaanklky** [comment]
Can't reproduce; not related to installation of Countly on CentOS 6.x.
