### ISSUE TITLE
First install - Cannot Add App

### ISSUE THREAD

**Issue by hongkongkiwi** [Countly/countly-server#104]
Hi there,

I just installed Countly Server using the install script on Ubuntu 14.04. I'm browsing to the dashboard and I've found that after login I cannot add an app. It asks me to add an app as I don't currently have any (that's fine), when I type in App Name, Country & Category and click Add Application then the button disables, but the app screen doesn't disappear. 

I checked the MongoDB and it doesn't actually add anything in there. Any ideas what's going on?

**Comment by ar2rsawseen** [comment]
Old issue, if you still have problems, please reopen
