### ISSUE TITLE
App icon fails to upload upon initial setup

### ISSUE THREAD

**Issue by joshhopkins** [Countly/countly-server#1040]
### Expected Behavior
Supported file types upload with no issue.

### Current Behavior
Supported file types fail to upload.

### Steps to Reproduce (for bugs)
1. Fresh install Countly 
2. Create application and upload App icon

### Your Environment
* Operating System and version: Ubuntu 18.04, Countly 19.08.1

**Comment by ar2rsawseen** [comment]
Fixed here:
https://github.com/Countly/countly-server/commit/d42a1586e484288fe85e3143690f03658ce2e1b4
