### ISSUE TITLE
Better custom translations

### ISSUE THREAD

**Issue by mt-sebastien-robert** [Countly/countly-server#1046]
### Current state

For context, we build a Docker image on top of Countly's Docker image, so we may override some files, or add new ones, to the core ones.

In our scenario, we need to have some custom translations, and I mean, translations that are specific to us, hence can't be stored in Transifex. We may add new ones, or override existing ones.

For the moment, there are two ways to achieve that:

1. Create a plugin, and set custom translations in file `plugins/XXX/frontend/public/localization/XXX.properties`.
This is not really ideal because having a plugin just for that is a lot of empty files and empty folders.

2. Create a new file in `frontend/express/public/localization/XXX/WHATEVER.properties`.
This is not ideal either because whether our overridden keys will really override or go to trash depends on something unreliable, named the order files are read by `readdirSync` function. (cf the `locales` Grunt task)

### Suggestion

Language files from plugins are guaranteed to be processed after core ones, and I would like to propose a way to have custom core files be guaranteed to also be processed after Countly's core ones.

In the Grunt task, between the loop that processes `.../localization/dashboard`, `.../localization/help` and `.../localization/mail`, and the loop that processes plugins, why not having something like:

```js
let dir = path.join(__dirname, 'frontend/express/public/localization/custom')
if (!fs.existsSync(dir)) {
    return;
}
fs.readdirSync(dir).forEach(function(name) {
    var file = path.join(dir, name);
    if (fs.statSync(file).isFile() && name.indexOf('.') !== 0) {
        pushLocaleFile(name, dir + '/' + name);
    }
});
```

Or something similar. Or another path that could avoid potential future conflicts, like `frontend/express/public/custom_localization`.

Let's discuss this feature request, and let me know if you need a hand, I'd be happy to contribute a PR.

Thanks.

**Comment by ar2rsawseen** [comment]
Added it here:
https://github.com/Countly/countly-server/commit/70e1bb03dfbe28450d23241fe72fade16a904ec4

 :)

**Comment by mt-sebastien-robert** [comment]
@ar2rsawseen 
Works great, thanks a lot 😃
