### ISSUE TITLE
hi my countly server web manage page error, in chrome i go to address http://my.domain.com ,there show me Forbidden Token

### ISSUE THREAD

**Issue by zfavourite99** [Countly/countly-server#1051]
hi my countly server web manage page error, in chrome i open link http://my.domain.com, countly show me "Forbidden Token", and there have no more information. And some days ago, i used countly fine.

**Comment by ar2rsawseen** [comment]
Hello
that could mean database is down, can you recheck countly can connect to mongodb?

You can try running

```
mongo countly `countly mongo`
```

**Comment by zfavourite99** [comment]
run the command error:
`[root@iZwz95wvlhb3mr6848q1zjZ bin]# mongo countly `countly mongo`
MongoDB shell version v3.6.14
connecting to: mongodb://localhost:27017/countly?gssapiServiceName=mongodb
2019-09-11T16:03:47.594+0800 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
2019-09-11T16:03:47.618+0800 E QUERY    [thread1] Error: couldn't connect to server localhost:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:263:13
@(connect):1:6
exception: connect failed
[root@iZwz95wvlhb3mr6848q1zjZ bin]# `

**Comment by ar2rsawseen** [comment]
So mongodb is not running, you need to find out why. Mongodb logs would be the first place to check

```
tail /var/logs/mongodb/mongod.log -n 100
```

**Comment by zfavourite99** [comment]
[mongod.log](https://github.com/Countly/countly-server/files/3599758/mongod.log)

this is the log.

**Comment by ar2rsawseen** [comment]
Unfortunately hard to say, nothing in the logs too :)

**Comment by zfavourite99** [comment]
Thank you for helping me solve the problem.

**Comment by ZeroJsus** [comment]
> So mongodb is not running, you need to find out why. Mongodb logs would be the first place to check
> 
> ```
> tail /var/log/mongodb/mongod.log -n 100
> ```
> 
> Starting MongoDB is usually something like
> 
> ```
> service mongod start
> ```
> 
> or
> 
> ```
> systemctl start mongod
> ```

thanks for you help.
that solve my question.
