### ISSUE TITLE
mongodb memory too large

### ISSUE THREAD

**Issue by zfavourite99** [Countly/countly-server#1085]
i install countly server, but it run some time, mongodb will shut down, i found the mongodb memory too large.
![image](https://user-images.githubusercontent.com/2630290/67473729-d23ff180-f685-11e9-8d25-8518ab51490a.png)

mongodb shut down because the memory too large?

**Comment by ar2rsawseen** [comment]
Hello
that's possible. MongoDB by default consumes half of the RAM (and can consume more on intensive use)

You can use /var/log/mongodb/mongod.log to see why mongodb shuts down
