### ISSUE TITLE
"/bin/certs/certbot-auto" path doesn't exist

### ISSUE THREAD

**Issue by joshhopkins** [Countly/countly-server#1119]
Following the documentation for [installing Let's Encrypt](https://resources.count.ly/docs/installing-lets-encrypt-for-https#section-configuration-options) provides inscription to setup cron job for cert auto renewal. It appears the path provided, "/bin/certs/certbot-auto" doesn't exist.

Furthermore, it appears that the [Nginx config provided](https://resources.count.ly/docs/configuring-https-and-ssl) prevents connections from Certbot. Running `sudo certbot renew --dry-run --webroot -w /usr/local/countly/frontend/express/public` should work with suggested configuration.

### Your Environment

* Operating System and version: Ubuntu 18.04, Countly 19.08.1

**Comment by joshhopkins** [comment]
Was able to get `certbot renew` working by amending the default server block: `/etc/nginx/sites-available/default`.

```
server {
  listen 80;
  listen [::]:80;
  server_name example.com;
  return 301 https://$server_name$request_uri;
  location ~ /.well-known {
    allow all;
    root /usr/local/countly/frontend/express/public;
  }
}
```

This tells nginx that requests to /.well-known/acme-challenge should be served from the webroot (/usr/local/countly/frontend/express/public), while everything else remains unchanged.

**Comment by joshhopkins** [comment]
And cron job should be: `0 12 * * * /usr/bin/certbot renew --quiet --post-hook "/usr/sbin/service nginx restart"`

This checks if the cert requires renewal every day at midnight and if the cert is updated will restart Nginx (Nginx doesn’t dynamically load the new certificate).

**Comment by waiterZen** [comment]
@joshhopkins  Thanks for your sharing. The document we provide a long time ago and certbot upgrade frequently, that might cause it does not work now.
Let me test your approach and if you not mind we can update to our document later.
