### ISSUE TITLE
Plugin not reloaded

### ISSUE THREAD

**Issue by BernhardSchlegel** [Countly/countly-server#1123]
### Expected Behavior

During Plugin development, I want to "reload" the plugin so that the changes are reflected on the WebUI. 

Not even the version number on the plugins page is updated.

### Current Behavior

However, none of the following methods helped

- `countly restart` as mentioned [here](https://resources.count.ly/docs/plugins-development-introduction)
- `countly stop && countly start`
- `grunt locales`

### Steps to Reproduce (for bugs)

1. Disabled production mode ![image](https://user-images.githubusercontent.com/5735721/70274646-22749e00-1772-11ea-915c-3f6e0fe09055.png)
2. Copied and modified "slipping-away" plugin
3. Activated my plugin

### Your Environment

* Ubuntu 18.04
* countly 19.08.1

**Comment by BernhardSchlegel** [comment]
Disable production mode

![image](https://user-images.githubusercontent.com/5735721/70274646-22749e00-1772-11ea-915c-3f6e0fe09055.png)

**Comment by ar2rsawseen** [comment]
Hello,
for server-side modifications you need to restart countly process
But for browser file modifications, if you disabled production mode like you show, then nothing needs to be done, except clear cache in browser, so Ctrl + F5 should work.

Can you tell us which exactly modifications you expected to occur?

**Comment by BernhardSchlegel** [comment]
<kbd>Ctrl</kbd> + <kbd>F5</kbd> was the missing puzzlepiece - thanks-a-lot!
