### ISSUE TITLE
Vagrantfile comment port mismatch

### ISSUE THREAD

**Issue by jeffsteinmetz** [Countly/countly-server#1164]
in
https://github.com/Countly/countly-server/blob/b96065488c33890f4db6448a9065482575494579/Vagrantfile

This comment states 8080 as the port

```
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  config.vm.network "forwarded_port", guest: 80, host: 32768
```

Either the comment needs to be updated to 32768

or this line needs to be
  `config.vm.network "forwarded_port", guest: 80, host: 8080`

**Comment by ar2rsawseen** [comment]
Hello,
really not sure why it is like that, but I guess original PR had these settings :)
Do you have any preference for the choice here, because I think internally no one here uses Vagrant specifically?

**Comment by jeffsteinmetz** [comment]
we use 8080

The vagrant file has been handy for local app dev (vs docker since vagrant
makes it easy to save state between restarts).

**Comment by ar2rsawseen** [comment]
Done here:
https://github.com/Countly/countly-server/commit/816ecec26c61dbced1530f748150990363c68b2c
:)
