### ISSUE TITLE
Where can I find Chinese documentation

### ISSUE THREAD

**Issue by lcxlhjy** [Countly/countly-server#1173]
Where can I find Chinese documentation? Thanks very much!

**Comment by ar2rsawseen** [comment]
Hello
I am sorry, I don't think there is any.
Any specific part you are interested in?
Maybe @waiterZen can help you with that?

**Comment by ar2rsawseen** [comment]
But please use
https://support.count.ly/hc/en-us/community/topics
for such discussions :)
