### ISSUE TITLE
Multiple events on one graph

### ISSUE THREAD

**Issue by ar2rsawseen** [Countly/countly-server#119]
Selecting multiple events to display on the graph, similar to All Apps view

**Comment by jianglinchun** [comment]
Did this future finished or not?

**Comment by ar2rsawseen** [comment]
Hello, no not yet

**Comment by ar2rsawseen** [comment]
Available in compare plugin
https://github.com/Countly/countly-server/commit/aaf08e7896b4cc6a8452125aa9b0e23bec46f7ec
