### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by chasel** [Countly/countly-server#1253]
When i use node 10.x build code, start process occur below error:
<img width="873" alt="Screen Shot 2020-03-31 at 12 25 52" src="https://user-images.githubusercontent.com/1614604/77986993-30ff4a80-734b-11ea-87fd-1374e3886aee.png">
How i solve it?

OS: ubuntu 16.04 TLS
node:10.19.0
npm: 6.14

when i downgrade node version to 8.x is work. but 10.x has error

**Comment by chasel** [comment]
when i see .travis.yml used 10.x, which 10.x vesion?

**Comment by ar2rsawseen** [comment]
Hello
as far as we tested there were no problems with nodejs 10
Have you tried deleting node_modules folder and running `npm install` to reinstall dependencies after upgrade?

**Comment by chasel** [comment]
ok, all node_modules files clear is worked

**Comment by chasel** [comment]
use node xxx/api.js && node xxx/frontend/express/public/app.js is worked, when i use node 10.19.0 and had delete node_modules folder.
But use countly start  with supervisord, has below error:
![Screenshot from 2020-04-02 10-14-13](https://user-images.githubusercontent.com/1614604/78204434-14d6e700-74cc-11ea-9c64-05b550ed2094.png)

**Comment by chasel** [comment]
deleted time build folder and use node-gyp rebuild isn't work.

**Comment by ar2rsawseen** [comment]
NODE_MODULE_VERSION 64 is Nodejs 10
NODE_MODULE_VERSION 57 is Nodejs 8

so somewhere it still detects and uses node modules from old version
So either you delete the wrong directory, or have globally installed modules or something like that

**Comment by chasel** [comment]
not work when I deleted many times  node_modules folder and repeat npm install if use counlty command start server.

only use node command is worked.

**Comment by chasel** [comment]
why diffierent I don't understand node command & countly command start server use  the same file path.

**Comment by chasel** [comment]
![Screenshot from 2020-04-03 09-51-59](https://user-images.githubusercontent.com/1614604/78316329-f3d8c980-7591-11ea-8449-465a7a18076d.png)

**Comment by chasel** [comment]
![Screenshot from 2020-04-03 09-52-49](https://user-images.githubusercontent.com/1614604/78316336-f76c5080-7591-11ea-90a5-d4e9b4a05a9e.png)

**Comment by ar2rsawseen** [comment]
What path does `countly dir` command outputs?

**Comment by ar2rsawseen** [comment]
Other place to check is inside `/etc/systemd/system/countly.service` which path is used in that file

**Comment by chasel** [comment]
![Screenshot from 2020-04-10 15-08-56](https://user-images.githubusercontent.com/1614604/78971121-7129ae80-7b3d-11ea-8c86-4cd17cdae240.png)

**Comment by chasel** [comment]
same directory

**Comment by ar2rsawseen** [comment]
And
```
/etc/systemd/system/countly.service
```

**Comment by chasel** [comment]
what?

**Comment by chasel** [comment]
![Screenshot from 2020-04-13 14-43-58](https://user-images.githubusercontent.com/1614604/79098861-6ec19180-7d95-11ea-9b4e-725b926753ff.png)

**Comment by chasel** [comment]
![Screenshot from 2020-04-13 14-43-59](https://user-images.githubusercontent.com/1614604/79099063-e8597f80-7d95-11ea-9abc-e45dace36a73.png)

**Comment by ar2rsawseen** [comment]
ok, then Countly dirs are ok
What else it could be, is multiple nodejs versions installed and `npm install` inside Countly would for some reason use incorrect one?

what does these commands output?
```
node --version
nodejs --version
```

**Comment by chasel** [comment]
![Screenshot from 2020-04-13 19-53-58](https://user-images.githubusercontent.com/1614604/79118536-c1647300-7dc0-11ea-8175-e39e9610bf3d.png)

**Comment by ar2rsawseen** [comment]
weird that nodejs is not there, they should both come together
But in overall, really have no other idea here, somehow, somewhere incorrect nodejs version is linked.

try empty clean VM instance :)

**Comment by chasel** [comment]
ok, I see.
I can try it.
