### ISSUE TITLE
Install script failing with npm/node-gyp (nodejs 0.10.35, Ubuntu 14.04 64-bit)

### ISSUE THREAD

**Issue by Dids** [Countly/countly-server#126]
After upgrading NodeJS to the latest (0.10.35), I was unable to run the install script due to node-gyp permission errors, even after running as root. I don't know what the root cause of this problem is, but it seems to be affecting quite a lot of people: https://github.com/TooTallNate/node-gyp/issues/454

This can't really be a permission problem, as this is fresh install and I tried creating/recreating the node-gyp directory itself and setting full read/write permissions on it, so just a heads up for anyone else running in to this.

The fix, for me at least, was to modify the countly.install.sh script (line 73) by appending '-unsafe-perm' to the npm line, like so: npm install time --unsafe-perm

**Comment by ar2rsawseen** [comment]
Interesting, it seems to be building correctly on Travis.
Either way --unsafe-perm seems to allow execute npm install with root permission, so will try to add them just in case

**Comment by Dids** [comment]
Or wait, do you want this to stay open to remind of the --unsafe-perm flag?

**Comment by ar2rsawseen** [comment]
No worries, will close it once we publish the new core with the fixes ;)

**Comment by ar2rsawseen** [comment]
Added in https://github.com/Countly/countly-server/commit/b657d76128eaa94e48bbd393feee7782d0135778
