### ISSUE TITLE
Countly hogging all CPU & memory until crashing the system

### ISSUE THREAD

**Issue by Dids** [Countly/countly-server#127]
I'm running Countly in a production environment, so there's quite a few incoming connections coming to Countly.
Everything has been working perfectly so far, but exactly 50 minutes ago, Countly started using 100% memory AND 100% CPU on a steady basis. I can open the web UI, but it never finishes loading, some UI elements aren't visible, etc.

The logs themselves don't say anything.

Any idea on how to further debug?

**Comment by derekmoorecountly** [comment]
What is the server specifications? RAM / CPU and swap space?

**Comment by Dids** [comment]
Countly is running as a VM with 4GB of RAM, with MongoDB hosted in a separate VM (also has 4GB of RAM).

The host machine has an Intel i7 980 CPU, running at 3.33Ghz, 6 cores and 12 threads.

Even after I restart the Countly VM, Countly's node app immediately starts eating all the RAM and CPU it can. I was previously using only 2GB of RAM, but bumped that up to 4GB, just to find out that it's eating through that too like it's butter.

I'll try throwing in a few more virtual CPUs to see if that'll help, but I highly doubt it.

**Comment by derekmoorecountly** [comment]
Please increase the RAM on DB. App server is waiting for DB server and queues everything, resulting in hogging up memory. 

Let me know after increasing only the RAM of DB server (without changing the number of vCPUs).

**Comment by Dids** [comment]
Didn't see your comment before increasing the virtual CPU amount, and weirdly enough, something happened.

I bumped the Countly VM's vCPUs from 1 to 4 (just for the heck of it), and after rebooting, Countly is now using only 1-2% of RAM, with CPU load at a steady 0.02. Seems really odd that the vCPU amount would've had anything to do with it, though.

I'll still investigate the MongoDB VM's performance logs from VMWare to see if that had anything to do with it.

**Comment by Dids** [comment]
MongoDB seems fine, nothing in the logs and both memory and CPU usage have been low. I'm also using MMS to monitor, and even that shows no signs of any issues on the DB server.

**Comment by Dids** [comment]
I'm not 100% sure, but this might've been caused by another VM on the same host, as it was running several CPU-intensive processes at the same time.

I'll close this ticket for now, hoping that it was just that and nothing else, really gave me a scare there! :smiley:

**Comment by Dids** [comment]
Looks like it's been happening non-stop last night again. The Countly VM does consume all of it's memory and generate a ton of warnings, then it constantly consumes all CPU, temporarily bringing down several other VMs.
I have no idea where to look at this point.

**Comment by Dids** [comment]
Right now the Countly VM is sitting at 35% RAM used, but the login screen was filled with out of memory messages.
CPU load on the other hand is at 4.5 and the entire VM feels very slow.

**Comment by Dids** [comment]
Other VMs on the same host are now using very little resources, but Countly is still insisting on randomly using all memory & CPU, causing all kinds of havoc.

**Comment by Dids** [comment]
Since I'm running MongoDB elsewhere, I decided to try and see if hosting Countly API/frontend on Digital Ocean would make a difference.

Guess what? It doesn't! Same CPU & memory hogging until the system becomes unresponsive.

**Comment by Dids** [comment]
By the way, not sure if it matters but I'm using the 'messaging' branch.

**Comment by Dids** [comment]
This issue might actually have something to do with Ubuntu/upstart: http://ubuntuforums.org/showthread.php?t=2218100

I'm currently trying to fix it by adding a 5sec delay to the plymouth-upstarts-bridge init.d script, and by installing this from the official Ubuntu apt repo: https://launchpad.net/ubuntu/trusty/+package/plymouth-disabler

It'll take a few hours to see if the issues are gone or not, so I'll report back when I'm absolutely sure.

**Comment by Dids** [comment]
Nope, wasn't it, sigh.

At this point I'm almost 100% certain that it's Countly at fault, as it's happening on different hardware but with the same setups.

**Comment by Dids** [comment]
Heh, tried giving it 16GB of RAM and it ate through it like crazy. I guess I'm going to have to go with a different analytics provider.

**Comment by derekmoorecountly** [comment]
How many custom events are you collecting in your production environment? Does any of these custom events, by chance, have near unlimited values? E.g, time in seconds, etc?

**Comment by Dids** [comment]
While I'm only collecting 2 separate custom events (purchasing a product and dismissing the product purchase prompt), I did mess up with the iOS implementation of the "sum" value, so all of my production users are now submitting invalid "sum" values.

The sum value can really be anything, as I was parsing a string to a float, but I forgot that the string had a currency symbol (ie. "$ 1.99"), so the value wasn't displaying correctly on Countly.

I'm guessing you're on to something here, since that's the only "issue" I could see there as well?

**Comment by derekmoorecountly** [comment]
That wouldn't make a very large and distinct set of sums I believe. Are there any logs generated in your log directory by chance?

**Comment by Dids** [comment]
Nope, that's the first thing I checked.
Countly did keep writing log lines about timezones not matching (config vs /etc/timezone), but I fixed that a few days ago.

**Comment by derekmoorecountly** [comment]
Ok.. if it's possible to give us a read-only access to your dashboard, we can check it. Otherwise it's a guesswork :)

**Comment by Dids** [comment]
I'm spinning up a new Digital Ocean droplet right now, to start from a fresh install again.
Can you give me your email address, so I can send you the credentials once I'm done installing? :)

**Comment by derekmoorecountly** [comment]
Please send it to hello at count.ly and we can have a look. 

Thanks!

**Comment by Dids** [comment]
Sent!

**Comment by Dids** [comment]
Even though the dashboard seems to be up, the system isn't even allowing me to open up top, due to node hogging all the memory:

root@countly:~# top
-bash: fork: Cannot allocate memory

**Comment by Dids** [comment]
Interesting update: right around after accessing the frontend, CPU and memory usage dropped extremely, and I could open 'top' again. Then after a few seconds/a minute, CPU and memory usage started climbing again.

**Comment by Dids** [comment]
By the way, I'm still seeing this line a ton in countly-api.log:

Fri, 23 Jan 2015 13:57:25 GMT time Date#setTimezone(Europe/Helsinki, undefined)

It's repeated over and over again, roughly 10 times per second, but only every 5-10 seconds.

**Comment by Dids** [comment]
countly-dashboard.log is getting at least 100 lines per second, is there anyway to reduce logging?

**Comment by Dids** [comment]
I don't know why, but it seems to be behaving now. Will probably need to wait for at least 24hrs and see if I get any New Relic alerts.

**Comment by Dids** [comment]
This just keeps getting weirder and weirder. At least the dashboard is staying up, even though memory usage is at 97% and I can't even SSH to the server. According to New Relic, CPU is relatively low, which might explain why the frontend is still accessible.

**Comment by Dids** [comment]
The droplet's unaccessible now, after letting it run for a few hours.

Here's what I see in Digital Ocean's VNC view:

![Screenshot](https://dl.dropboxusercontent.com/u/480/Countly.png)

**Comment by gorkem-cetin** [comment]
It crashed also when I was on the dashboard. Are you using a custom(ized) SDK by chance?

**Comment by Dids** [comment]
Nope, everything is straight from the official 'messaging' branches. :/

**Comment by derekmoorecountly** [comment]
@osoner I see that session loyalty and session frequency screens has some issues, can you check? 
![session1](https://cloud.githubusercontent.com/assets/5315723/5887256/cef3aa40-a3cd-11e4-8d31-1081756c73e1.png)
![session2](https://cloud.githubusercontent.com/assets/5315723/5887257/cef61712-a3cd-11e4-8730-9a1b50cb2dd3.png)

**Comment by Dids** [comment]
Since I restarted the server roughly 12 hours ago, it's been up without a hitch. That's not saying much though, since it might go down any moment now.

**Comment by derekmoorecountly** [comment]
Could you copy and paste the code snippet you used to send data to your servers?

**Comment by Dids** [comment]
Nothing fancy there, just pushing regular events. Like I mentioned before, the "sum" value is wrong, since it's actually a string that can't be parsed to a valid float.

[[Countly sharedInstance] recordEvent:@"Purchased Pro" count:1 sum:[[[FRIAPManager sharedInstance] getPriceForUpgradeWithIdentifier:@"Flash_Reader_Pro"] floatValue]];

and

[[Countly sharedInstance] recordEvent:@"Dismissed Upgrade Popup" count:1];

**Comment by ar2rsawseen** [comment]
BTW.
To stop logging like crazy, remove 

    environment=DEBUG=*

from https://github.com/Countly/countly-server/blob/messaging/bin/config/supervisord.conf

and restart server

**Comment by Dids** [comment]
Thanks! I'll try and see if that has any effect on the issue.

**Comment by Dids** [comment]
No change, always runs of out memory at least once a day and eventually locks up so I have to do a hard reset. It can take anywhere from an hour to 12 hours, though.

**Comment by derekmoorecountly** [comment]
> The sum value can really be anything, as I was parsing a string to a float, 
> but I forgot that the string had a currency symbol (ie. "$ 1.99"), so the value 
> wasn't displaying correctly on Countly.

Could you resubmit your app, fixing this? Trying to narrow down potential points of pain.

**Comment by Dids** [comment]
I could, but that'll take a few weeks to go live. Might take a couple of weeks after that for most of my users to update.

**Comment by Dids** [comment]
I'm trying to use Compose.io again as the DB host. What roles does Countly require from the database user? Compose.io gives readWrite@db, but not dbAdmin@db, and I'm seeing these in the MongoDB log file:
assertion 13 not authorized for query on countly.members ns:countly.members query:{ api_key: "<redacted>" }

**Comment by Dids** [comment]
I managed to get a hotfix update through, and manually removed all sum's from MongoDB, but that made no difference.
I'm shutting down the droplet, since it's just not worth it at this point.

**Comment by ar2rsawseen** [comment]
User's that had this problem with old core, does not seem to have it with new plugins core, so closing this issue

**Comment by urvashi31** [comment]
how to shut down a countly server?

**Comment by ar2rsawseen** [comment]
run
`countly stop`

**Comment by urvashi31** [comment]
thankew

**Comment by urvashi31** [comment]
and how to stop it's mongodb connection?

**Comment by ar2rsawseen** [comment]
depends on init system, mongodb has its own daemon, so could be
`sudo stop mongod` or
`sudo service mongod stop` or
`sudo systemctl stop mongod` or
`sudo /etc/init.d/mongod stop`
