### ISSUE TITLE
Dashboard locks under Mac OS X

### ISSUE THREAD

**Issue by derekmoorecountly** [Countly/countly-server#128]
Sometimes, under uncertain circumstances, dashboard doesn't move up/down using a mouse. Keyboard works, and it's possible to click on other UI components. 

This happens only with Mac OS X and not other operating systems. Tested browser is Chrome.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/5d2d5e20e01d7e596d871d435037eba8fb22f5cf
