### ISSUE TITLE
Countly does not recognize all iphone model 

### ISSUE THREAD

**Issue by allairgoo** [Countly/countly-server#129]
The full list is here : https://theiphonewiki.com/wiki/Models . But Countly identify iphone 6 as an iphone 7,2 and iphone 6+ as 7,1.

**Comment by osoner** [comment]
@ar2rsawseen I think it is time we automate this somehow. We can host a simple JSON list on our server and each Countly server can fetch (and maybe cache it for some time) and use that instead of a hardcoded one.

**Comment by ar2rsawseen** [comment]
Sure, we could store them in a file like:
http://178.62.137.211/javascripts/countly/countly.device.list.js

And check later as:

```
    countlyDevice.getDeviceFullName = function(shortName) {
		if(countlyDeviceList && countlyDeviceList[shortName])
			return countlyDeviceList[shortName];
        return shortName;
    };
```

And then periodically fetch and update countly.device.list.js from central server.

Either through cron or some trigger in Countly

**Comment by gorkem-cetin** [comment]
Here's a list of an incomplete mapping for Android but an OK start:

https://github.com/meetup/android-device-names

@osoner I think we better skip off automation for this release and think of a good solution for next release as time permits.

**Comment by jeremytoh8** [comment]
@ar2rsawseen thanks for your advice. I tried to install the messaging branch and cloned the whole repo https://github.com/Countly/countly-server/tree/messaging
But when I tried to setup the messaging branch everything went through but in the end, it failed on nginx 502 Bad Gateway. I setup from scratch on Ubuntu 14.04 VPS. 
However, when I setup from scratch the master branch, it works fine but without messaging feature. Can you please advice? Thanks.

**Comment by derekmoorecountly** [comment]
What's the amount of RAM on Ubuntu VPS? Countly would need at least 1GB of RAM, or enough swap space if there's 512MB RAM, otherwise Linux will go out of memory during initial start.

**Comment by jeremytoh8** [comment]
i am using 2048 GB of RAM and 4 vCPU on Ubuntu 14.04 64-bit. 
These are the basic steps I did to setup countly messaging branch. 
From the prompt: sudo su
/home/user# git clone -b messaging https://github.com/countly/countly-server.git
/home/user# cd countly-server-bin
/home/user/countly-server/bin# bash countly.install.sh
After the setup is finished, it come out with error below when referring to the IP Address 
502 Bad Gateway
nginx/1.4.6 (Ubuntu)

You guys can easily replicate this messaging branch bug on any newly setup Ubuntu VPS. I did the same steps on the master branch and I can successfully login to countly admin via the IP Address. Something is not right on the messaging branch setup scripts which causes the nginx error

I can even let you guys and gals access to my newly setup Ubuntu VPS via SSH to replicate this messaging branch bug. Just shoot me a PM or email. Thanks.

**Comment by gorkem-cetin** [comment]
Thanks, npm didnt simply install flat module, while it was required in a file. Fixing that momentarily. 

Meanwhile you can install by hand only once (npm install flat) and then issue stop countly-supervisor , start countly-supervisor as root and you won't see nginx error, but login page instead.

**Comment by iartem** [comment]
@jeremytoh8, I've just pushed that missing flat module. Feel free to make `git pull` and `restart countly-supervisor`.
