### ISSUE TITLE
Login monitoring (HIPAA compliance)

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#130]
Successful and unsuccessful login attempts should be logged in an appropriate place on dashboard to conform HIPAA (Health Insurance Portability and Accountability Act) standards.

**Comment by gorkem-cetin** [comment]
According to http://www.idealware.org/articles/search-hipaa-compliant-software

"One of the clearest HIPAA requirements is that organizations keep an audit log of who did what in the software package. It's important that your package be able to track which person accessed which record (down to the client level) on what date, and whether he or she viewed it, updated it, or deleted it. (This rule implies that all users need a distinct username and password to access organizational software.)

It's also very desirable to be able to track what each user changed specifically ― for instance, to be able to see the value of a field both before and after he or she changed it "

**Comment by ar2rsawseen** [comment]
Implemented system logs here: https://github.com/Countly/countly-server/commit/2f07ec9e4812ebe984019bca214c5c360101258c

For now it tracks login, password reset, app (create,update,reset,delete) and user (create, update, delete) events
