### ISSUE TITLE
More space in Device ID 

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#133]
Is it better to rename the Device column to Device ID and remove Device ID in all data, under that column? That will provide more space for all other columns.
 
Screenshot: 
![device_id](https://cloud.githubusercontent.com/assets/1757036/6651681/45b0465c-ca57-11e4-94d4-633d7bac154b.png)

**Comment by ar2rsawseen** [comment]
Yes, but in that column could also appear other info, as device model and manufacture, etc

**Comment by gorkem-cetin** [comment]
Invalid :)
