### ISSUE TITLE
How do I exclude / ignore my traffic from Countly?

### ISSUE THREAD

**Issue by emresaracoglu** [Countly/countly-server#1336]
Hello

I didnt find in documentation. How do I exclude / ignore my traffic from Countly with IPs or cookies?

Thank you

**Comment by ar2rsawseen** [comment]
Hello,
can you elaborate more?
What exactly you want to block and on which side? :)

On SDK there is usually opt out options available, that are stored persistently.
On server side you can utilize Nginx configuration to be able to block any requests:
For example:
https://help.dreamhost.com/hc/en-us/articles/216456127-Blocking-IPs-with-Nginx

**Comment by emresaracoglu** [comment]
I couldn't find a section to ignore IPs (IP range) in the admin panel on the self-hosted side. Is it possible to ignore the traffic of people with a certain IP?

**Comment by ar2rsawseen** [comment]
So for Enterprise there is a plugin Filtering rules, which allows to block users by IP address, but also many other things, starting from custom user properties to any other segments.

But for Community edition opting out on SDK side or configuring Nginx is the only way

**Comment by emresaracoglu** [comment]
I understand, thank you for answer
