### ISSUE TITLE
I think it's not work，Because countly not listen port 3000,6001

### ISSUE THREAD

**Issue by DraperHXY** [Countly/countly-server#1356]
### Expected Behavior

The Countly Server is not running
I just want deploy Countly and login in on the browser

### Current Behavior

I use ``wget -qO- http://c.ly/install | bash`` to install countly server.
But access on the browser only have 502 BadGateway
After installation, I think my Nginx configuration file has extra something. I’m not sure
The Nginx conf file on the follow:

``` conf
server {
	listen   80;
	listen   [::]:80 ipv6only=on;
	server_name  localhost;

	access_log  /var/log/nginx/countly/access.log;
        error_log   /var/log/nginx/countly/error.log;

	location = /i {
        if ($http_content_type = "text/ping") {
             return 404;
        }
		proxy_pass http://127.0.0.1:3001;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP $remote_addr;
	}

	location ^~ /i/ {
        if ($http_content_type = "text/ping") {
             return 404;
        }
		proxy_pass http://127.0.0.1:3001;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP $remote_addr;
	}

	location = /o {
        if ($http_content_type = "text/ping") {
             return 404;
        }
		proxy_pass http://127.0.0.1:3001;
	}

	location ^~ /o/ {
        if ($http_content_type = "text/ping") {
             return 404;
        }
		proxy_pass http://127.0.0.1:3001;
	}

	location / {
        if ($http_content_type = "text/ping") {
             return 404;
        }
		proxy_pass http://127.0.0.1:6001;
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP $remote_addr;
	}
}
```

I have been sawed the port 3001 and 6001，so I use ``netstat -ant | grep 3001`` check the port
But doesn't have more info. So I think Countly Server maybe is not work.

I use ``countly healthcheck all`` 

![image](https://user-images.githubusercontent.com/18048426/82987737-a37a6700-a02a-11ea-80c4-8ca3b35720c7.png)

### Your Environment

* OS : Ubuntu 18.04.2 LTS
* Countly Version: 20.4

**Comment by DraperHXY** [comment]
![image](https://user-images.githubusercontent.com/18048426/82991299-0cb0a900-a030-11ea-8ae9-b3582907158c.png)

**Comment by ar2rsawseen** [comment]
It looks like processes are not running or crashing
do you have anything in /root/countly/log/countly-api.log?

**Comment by DraperHXY** [comment]
I try to install countly again. And check the log

/root/countly/countly/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /root/countly/countly/node_modules/time/build/time.node
 → /root/countly/countly/node_modules/time/build/Debug/time.node
 → /root/countly/countly/node_modules/time/build/Release/time.node
 → /root/countly/countly/node_modules/time/out/Debug/time.node
 → /root/countly/countly/node_modules/time/Debug/time.node
 → /root/countly/countly/node_modules/time/out/Release/time.node
 → /root/countly/countly/node_modules/time/Release/time.node
 → /root/countly/countly/node_modules/time/build/default/time.node
 → /root/countly/countly/node_modules/time/compiled/10.20.1/linux/x64/time.node
 → /root/countly/countly/node_modules/time/addon-build/release/install-root/time.node
 → /root/countly/countly/node_modules/time/addon-build/debug/install-root/time.node
 → /root/countly/countly/node_modules/time/addon-build/default/install-root/time.node
 → /root/countly/countly/node_modules/time/lib/binding/node-v64-linux-x64/time.node
    at b

![image](https://user-images.githubusercontent.com/18048426/83043325-5079d180-a075-11ea-92c3-bf34f90ed759.png)

**Comment by ar2rsawseen** [comment]
So for some reason, it could not install time module
can you check install log for error, why it did not install it?

Also, you can try to reinstall node modules

```
rm node_modules
npm install
```

**Comment by DraperHXY** [comment]
I enter node_modules and only delete time module
then this output on the following
![image](https://user-images.githubusercontent.com/18048426/83087669-6498ef80-a0c4-11ea-9be8-dffae5aa62f4.png)

**Comment by DraperHXY** [comment]
I have some question want to ask.
1. If I don't install mongodb, Can I finish install countly completely？[Shoud I install Countly on a clean instance](https://support.count.ly/hc/en-us/articles/360037874591-Installation-FAQ#should-i-install-countly-on-a-clean-instance)
2. If I install countly on a clean instance. the mongodb be installed automaticly?
3. I finish above steps, It's look like that time module was installed success. Some log in ``log/countly-api.log``

![image](https://user-images.githubusercontent.com/18048426/83089176-4208d580-a0c8-11ea-9986-0d301d74b24d.png)

Should I install MongoDB independently?

Thanks

**Comment by DraperHXY** [comment]
2020-05-28T01:29:02.881Z: INFO	[jobs:job]	Replacing jobs api:clearAutoTasks ({"status":0,"name":"api:clearAutoTasks"})
2020-05-28T01:29:02.882Z: INFO	[jobs:job]	Replacing jobs api:task ({"status":0,"name":"api:task"})
2020-05-28T01:29:02.883Z: INFO	[jobs:job]	Replacing jobs api:userMerge ({"status":0,"name":"api:userMerge"})
{ MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout.waitQueueMember.timer.setTimeout [as _onTimeout] (/root/countly/countly/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'MongoServerSelectionError',
  reason:
   TopologyDescription {
     type: 'Single',
     setName: null,
     maxSetVersion: null,
     maxElectionId: null,
     servers: Map { 'localhost:27017' => [ServerDescription] },
     stale: false,
     compatible: true,
     compatibilityError: null,
     logicalSessionTimeoutMinutes: null,
     heartbeatFrequencyMS: 10000,
     localThresholdMS: 15,
     commonWireVersion: null },
  [Symbol(mongoErrorContextSymbol)]: {} }
2020-05-28T01:29:21.609Z: ERROR	[db:read]	Error reading plugins {"name":"findOne","args":[{"_id":"plugins"},{"projection"

**Comment by ar2rsawseen** [comment]
Countly install script should also install MongoDB too
The fact that it is not installed, means there was some error in the installation specifically (maybe that is why time module errored too)
Feel free to rerun install script :)

**Comment by DraperHXY** [comment]
I have been installed MongoDB independently and access dashboard success.
Thanks for your help 👍
