### ISSUE TITLE
Consider separating "change password" and "delete account" forms

### ISSUE THREAD

**Issue by dimaqq** [Countly/countly-server#1365]
<img width="1186" alt="Screenshot 2020-05-29 at 9 46 26" src="https://user-images.githubusercontent.com/662249/83208819-b52a4e80-a191-11ea-8131-f090f52d7a70.png">

I was saved by confusion of entering the password the 4th time... which password old or new?

If I didn't stop to think, I would have deleted my account when I meant to change the password 😱

**Comment by osoner** [comment]
This is a very good point Dima, thank you for bringing it to our attention.

**Comment by ar2rsawseen** [comment]
This was added here: https://github.com/Countly/countly-server/pull/1446
