### ISSUE TITLE
`.0` is added to app versions that are not understood

### ISSUE THREAD

**Issue by dimaqq** [Countly/countly-server#1385]
I've tested a few app versions:
* `2020.06.2.<hex>` is shown verbatim
* `local+<hex>` gets `.0` appended to it
* unrecognised version (null?) is displayed as `0.0`, presumably version is casted to `0` and then `.0` is appended

<img width="1120" alt="Screenshot 2020-06-17 at 16 04 59" src="https://user-images.githubusercontent.com/662249/84866309-82021d80-b0b4-11ea-96a9-2f3ff387c488.png">

I've validated that the web sdk sends `local+<hex>` correctly. 

The database contains `av: "local+<hex>:0"` with a colon 🙈 but then again all other versions in the database have dots replaced with colons.

I seems if I ensure that the `app_version` starts with a number, the rest, stringy content is preserved.

**Comment by ar2rsawseen** [comment]
I think it stems from this:
https://github.com/Countly/countly-server/blob/7c2b6517999b965389a019b2ef1f64773759d9d1/api/parts/data/usage.js#L535-L537

which comes from commit 5 years ago, but I honestly don't remember the reason for it. Will need to research more

**Comment by ar2rsawseen** [comment]
Reason for this was semantic version comparison and ordering.
I have fixed to apply this only to numeric versions here:
https://github.com/Countly/countly-server/commit/a050e93c5036867cdf609b79edf98ba885903d56

So it should fix your issue :)
