### ISSUE TITLE
Numbers on world map (dashboard) should have a description

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#141]
On the dashboard, the country list next to the map shows sessions, but it's not visible and clear. Adding one or more buttons (e.g sessions, users, new users etc) will remove misunderstandings.

**Comment by ar2rsawseen** [comment]
Implemented switching metrics for country and city in https://github.com/Countly/countly-server/commit/665476967d2dcf3d687baf12313709b9d585bd5d and https://github.com/Countly/countly-server/commit/62afcfd76ca6812d032a79d88ac01dcd1f5dae0d
