### ISSUE TITLE
countly docker not able to connect to mongo db of aws

### ISSUE THREAD

**Issue by SejalParmar8796** [Countly/countly-server#1418]
Hello Team,
I am trying to run the docker image with the mongo db database which is in aws. But somehow, it is not able to connect. And When I check in browser, it is giving forbidden token.
Can you please look into it?

**Comment by ar2rsawseen** [comment]
Hello,
usually, problem is that it cannot connect to the database, and the most common reason is authentication. Can you try connecting without authentication and then set it up later? And let us know if the issue still persists. And if it does, please provide logs on what is going on there :)
