### ISSUE TITLE
Analytics iOS platform have Android.

### ISSUE THREAD

**Issue by truonguit2010** [Countly/countly-server#142]
Hi,
I select Analytics tab and select Platform. I select iOS platform, It also show Android.

![screen shot 2015-05-06 at 12 01 21 pm](https://cloud.githubusercontent.com/assets/4622117/7487763/d694d534-f3e7-11e4-8f58-4b76d52b49bd.png)

**Comment by ar2rsawseen** [comment]
Hello @truonguit2010
which Countly version are you using exactly?

**Comment by truonguit2010** [comment]
Hello ar2rsawseen,
I use Countly 14.08 version.

**Comment by ar2rsawseen** [comment]
Too bad, I wanted to make sure that those records really contain incorrect OS or incorrect device string and 15.03+ version has DBViewer plugin that would allow to easily do that. :)

Either way, as you see by the names in the string KiOS, chiOS, Mac, etc, those devices have some custom rom, that possibly made Android running on iOS, as for example OpenIBoot. Thats probably why the confusion.
