### ISSUE TITLE
Countly doesn't work with Ubuntu 15.04

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#143]
It fails at the final line

Done, without errors.
./countly.install.sh: 123: ./countly.install.sh: start: not found

Note to self: Modify readme.md once this issue is closed.

**Comment by osoner** [comment]
Haven't tested it yet but I think new release comes with systemd instead of upstart: http://linux.softpedia.com/blog/Ubuntu-15-04-Users-Can-Switch-Off-Systemd-and-Use-Upstart-479373.shtml

This should fix it:

`sudo apt-get install upstart-sysv`

Will test whether this affects existing versions.

**Comment by osoner** [comment]
Actually you need to restart the server in order for `sudo apt-get install upstart-sysv` to work. Will try to find a way around this.

**Comment by ar2rsawseen** [comment]
Fixed in implementing init system/platform independent commands, so it is now working on Ubuntu 15.04 too.

But it is probably better to remove the warning after 15.08 release
