### ISSUE TITLE
If an app has long name, its name overflows under All Apps view

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#144]
![longname](https://cloud.githubusercontent.com/assets/1757036/7703971/263bdb76-fe44-11e4-8128-d645cec5310e.png)

Also there'a 1px overflow here: 

![1px](https://cloud.githubusercontent.com/assets/1757036/7703979/32591cfc-fe44-11e4-856f-a651bfe02407.png)

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/6147f41dc2af9b8877b243fda35e56e8d13aa407 and https://github.com/Countly/countly-server/commit/68576c91cc428c3a86693888cea27226aaeadd6d
