### ISSUE TITLE
Server maintenance mode

### ISSUE THREAD

**Issue by ar2rsawseen** [Countly/countly-server#146]
Provide an option to enable server maintenance mode which either responds 503 for SDK requests to make them queue requests and sync back later

or make server side queue in another db, that can be relaunched later on

**Comment by gorkem-cetin** [comment]
Out of curiosity, would there by any SDK changes for this to happen?

**Comment by ar2rsawseen** [comment]
No, server response with service unavailable, which is not success code, so no changes there if SDK properly listens to response codes, which I think all official ones do :)

**Comment by gorkem-cetin** [comment]
Just FYI: there's a check needed for Unity & cocos2d-x at least, will also ping for Appcelerator.

**Comment by osoner** [comment]
The queue implementation should take care of this in all SDKs. Device having no internet connection and maintenance mode should basically be the same thing for the SDKs, no HTTP 200 response.

**Comment by ar2rsawseen** [comment]
but not everyone will have queue db, so SDK should look for success HTTP response code and possible for JSON response with result property equal to Success.

I think we could write SDK implementation guide

**Comment by gorkem-cetin** [comment]
An implementation guide would be great. All SDKs have started to become different from each other in terms of features and methods of work. I'm trying to get them aligned talking to other SDK devs, but a generic doc would be great.
