### ISSUE TITLE
Crash reports plugin for Community Edition

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#152]
![crash_reports_ce](https://cloud.githubusercontent.com/assets/1757036/8023339/3a2579d6-0d11-11e5-9680-0d4313e8734e.png)

Add crash reports plugin for Community Edition. Basic features would be: 

* Time series graph for: 
 * Total occurences
 * Unique crash number
 * Non-fatal & fatal crash number

* Overall statistics for: 
 * Latest app version
 * Affected user % 
 * Top platforms 
 * Crash fatality (fatal vs non-fatal)

* Last 10 crashes (FIFO)

**Comment by ar2rsawseen** [comment]
Added in https://github.com/Countly/countly-server/commit/5905f6044d4e3f4c2cbd8b230a4cac9c22ff1fc4
