### ISSUE TITLE
Live Session dashboard

### ISSUE THREAD

**Issue by vBlackOut** [Countly/countly-server#1536]
Hello, 

it's possible to views the current session ( all active session immediatly on dashboard )

if you are more information or are request SQL ( mongoDB )

thank you for your information or add this functionnality

thank you

**Comment by ar2rsawseen** [comment]
Hello
so the connection from SDK to Countly is not a continuous connection, so you cannot really say if the client is still connected or not. The client may suddenly stop sending requests without properly ending, session, etc. So there is no 100% metric to rely on. Mostly what you can do is check the last request time for each user and assume that if within 1-minute new request does not come in, then use is probably offline now
For that in  `countly` database `app_usersAPP_ID` collection, there are all the documents for each user you have, and there is a field `lac` which is a millisecond timestamp for the last API call. So you can check when was the last time user connected to the server.

**Comment by vBlackOut** [comment]
Ok thank you i show this on database 

but i don't exactly to live session.

Ok i close this issue.
