### ISSUE TITLE
Timezone bug?

### ISSUE THREAD

**Issue by windware-ono** [Countly/countly-server#1544]
I've just started on a fresh Countly instance of 20.04 and I did some test accesses but somehow the 1 week setting doesn't show any visitor count,

![countly-week](https://user-images.githubusercontent.com/4352236/94745813-5fbbb380-03b6-11eb-971a-1979d72f7746.png)

but if I change the period to just today, it shows but the graph is still empty.

![countly-today](https://user-images.githubusercontent.com/4352236/94745840-72ce8380-03b6-11eb-9dd0-4625c4753037.png)

The screenshots were taken around 7:15 and I'm on GMT+9 timezone, if that is somehow shifting the day calculation.
The accesses were made on Oct 1st and the server's timezone is also at GMT+9.

**Comment by ar2rsawseen** [comment]
Hello,
so we have a generic problem with timezone. As in, data is displayed in the app's timezone, while the dashboard is displayed in the user's timezone. Thus there could be cases when the user is (or still) on a different day than the app's incoming data. But it should be replicable for all graphs, not only Views.

**Comment by windware-ono** [comment]
Is this closed as it's fixed in an unreleased version?

**Comment by ar2rsawseen** [comment]
Hello
if that is this known problem with timezone, we have an internal ticket for it, but no schedule or plan yet. As it requires too many changes. Most probably it will be paired with some major refactoring or something like that.
So for now, it will not be fixed.
