### ISSUE TITLE
Some pages not/partially showing the data on load

### ISSUE THREAD

**Issue by windware-ono** [Countly/countly-server#1545]
Somehow even with several accessed data, when I load the Browsers page under Analytics, it shows up empty first,

![countly-browser-before](https://user-images.githubusercontent.com/4352236/94746373-87f7e200-03b7-11eb-9630-97b65bc16700.png)

but if I wait for 10 seconds, causing XHR of `method=browser&action=refresh` to be triggered, it fills in the table but the graph doesn't show up.

![countly-browser-after](https://user-images.githubusercontent.com/4352236/94746376-89c1a580-03b7-11eb-8313-a45ab2552723.png)

This also happens in the Languages page where it shows `Total Visitors` as 3 and `Total Sessions` as 0 with the pie graph being empty when I load the page but after 10 seconds, they become 6 and 3 and the pie graph gets drawn.

After a while, the Browsers page now fills in the data on load but not sure what triggered it to act normally.

**Comment by ar2rsawseen** [comment]
If you can reproduce it, can you also check what is happening with API calls in the Networking tab, maybe there was some problem on the server side during that time?

**Comment by ar2rsawseen** [comment]
Sorry, we cannot reproduce this. It may as well been some problem with the process or server at that specific time.
