### ISSUE TITLE
Map broken on another language

### ISSUE THREAD

**Issue by windware-ono** [Countly/countly-server#1546]
The map works fine under English interface,

![countly-map-en](https://user-images.githubusercontent.com/4352236/94748587-9b597c00-03bc-11eb-81e8-eca066815199.png)

but the country no longer gets highlighted by changing the language.

![countly-map-jp](https://user-images.githubusercontent.com/4352236/94748612-aca28880-03bc-11eb-9c08-cd89d63baeda.png)

**Comment by ar2rsawseen** [comment]
Hello, it was a great catch that countries disappear when you are changing language :) 
This has now been fixed here and will be in next release:
https://github.com/Countly/countly-server/commit/615bed019c2d4285583eca42331c8c0f2cf75084
