### ISSUE TITLE
Errors creating new app, and ajax calls

### ISSUE THREAD

**Issue by Dreamystify** [Countly/countly-server#1550]
I have got countly running in a docker swarm behind traefik. I forward requests from countly.mydomain.com to the countly-frontend container. It loads as expected to the create user and then login, and redirects to https://countly.mydomain.com/dashboard#/manage/apps to create an app. Unfortunately thats as far as I get, when I click the 'Add application' button is does nothing. in the dev tools console window of chrome I get the following error

GET https://countly.mydomain.com/i/apps/create?args=%7B%22name%22%3A%22MyApp%22%2C%22type%22%3A%22mobile%22%2C%22timezone%22%3A%22Australia%2FSydney%22%2C%22country%22%3A%22AU%22%7D 404

which gives a 404

The countly-api, countly-frontend and mongodb containers are all running and there are no connection issues. 

Any ideas?

**Comment by iartem** [comment]
You've set routing rules incorrectly. That request which 404s should go to API container and it goes to the frontend one or doesn't go anywhere. Please refer to our [standard Nginx](https://github.com/Countly/countly-server/blob/master/bin/docker/nginx.server.conf) rules as a reference and use our support channels (community forum or Slack) for such questions. Github is for issues only.

**Comment by Dreamystify** [comment]
Ah ok, the following did the trick on the api container traefik labels thank you.
Host(`countly.mydomain.com`) && PathPrefix(`/o`) || PathPrefix(`/i`)
