### ISSUE TITLE
Impossible to run "countly" CLI commands from the docker frontend

### ISSUE THREAD

**Issue by gioppoluca** [Countly/countly-server#1557]
### Expected Behavior
I'm expecting to be able to issue countly commands

### Current Behavior
In the container when I enter the user is non root (that is a good thing) but the executing user do not have sudo rights so no chances to execute countly commands

### Your Environment
docker

**Comment by ar2rsawseen** [comment]
Hello
do you mean you cannot execute any countly command, like even `countly dir`?
or you mean you cannot execute some countly commands because of permission?

**Comment by gioppoluca** [comment]
I can execute "countly dir" but not clountly add_user (the message is "need to be root")

**Comment by iartem** [comment]
@gioppoluca you can always run something like `docker exec -u root`, of course assuming you don't use k8s and you have access to docker.

**Comment by ar2rsawseen** [comment]
Since `countly add_user` adds a global admin user that can do anything, it was decided to restrict this command with root only permission. But as you see, there are workarounds for docker too.
