### ISSUE TITLE
Screen widget stays on screen after clicking another menu item

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#156]
In another words, screen does not refresh so the widget stays there. 

![screenshot](https://cloud.githubusercontent.com/assets/1757036/8125402/090c91b4-10ee-11e5-8371-fa7cc0a33912.png)

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/1524ace8434325dee19ae81010c00d0f432ccfee
