### ISSUE TITLE
Enrich data in Countly by writing directly to database

### ISSUE THREAD

**Issue by JCHHeilmann** [Countly/countly-server#1582]
Is it possible to enrich data collected by Countly by writing directly into the MongoDB database?

We are collecting IDs of content from the App SDK. We would like to add details to these IDs, that cannot be added to the custom event in the app, using an external service. Can this service add this additional data directly into the Countly data stored in the MongoDB? Will it show up in Countly?

Thank you

**Comment by ar2rsawseen** [comment]
Hello
there are multiple pre and post-processing to data, so it is not possible to write data directly to the database.
But you can use /i API to feed the data or feed it programmatically to our request processing module.
Example of using request processing module:
https://github.com/Countly/countly-server/blob/master/api/tcp_example.js#L79-L95
