### ISSUE TITLE
spawn /usr/sbin/sendmail ENOENT

### ISSUE THREAD

**Issue by multinerd** [Countly/countly-server#1586]
### Expected Behavior
in `Configuration` > `API` > `Send a test email to me` should send an email to my email address.

### Current Behavior
Docker outputs the following
```
countly-api_1 | Error sending email
countly-api_1 | spawn /usr/sbin/sendmail ENOENT
```

### Steps to Reproduce (for bugs)

1. Git Clone, Docker Compose
2. Create first user and send email
3.
4.

### Your Environment

* Operating System and version: Windows 10

Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

* Any changes you have made to your instance: 

- added `COUNTLY_CONFIG_HOSTNAME` to `docker-compose.yml`
- changed exposed port to `9001`
- configured both `extend/mail.js` and `api/config.js` (email settings was tested with a local test application and works)

**Comment by ar2rsawseen** [comment]
I think sendmail is not available in our docker image to make it as light as possible. Docker can only use external mail servers, like separate image with mail server or remote mail server. And you can configure connection to that mail server through configs:
https://support.count.ly/hc/en-us/articles/360037814511-Docker-Kubernetes#email

**Comment by multinerd** [comment]
So in order for me to have emailing functionality, dont bother configuring the 2 `js` files, just pass them as env variables?

**Comment by multinerd** [comment]
nvm, working now. thanks for the guidance.
