### ISSUE TITLE
[Feature]: Ability to change application's icon

### ISSUE THREAD

**Issue by multinerd** [Countly/countly-server#1587]
### Expected Behavior

Is it possible to change the icon of an application after the app was created? If it is, I am unable to find it.

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/6367998/97055014-e6962300-1553-11eb-821e-52e0862ddace.png)

**Comment by ar2rsawseen** [comment]
Hello
this is form in read mode, you need to go to top right ... and select Edit
then you would be able to edit all the fields

**Comment by multinerd** [comment]
Ah, I cant believe I missed that...
