### ISSUE TITLE
Allow web ui to be zoomable on mobile

### ISSUE THREAD

**Issue by ddaddy** [Countly/countly-server#159]
The web ui is pretty static on an iPhone. Sending a push message from an iPhone is impossible as the Send button is off the bottom of the screen and it doesn't scroll or zoom out.

**Comment by gorkem-cetin** [comment]
Thanks for reporting this. Our UI is undergoing a major change which will honor responsive design, minimalism and elegance. We will keep this in mind!

**Comment by osoner** [comment]
We'll make the new UI as responsive as possible but I guess we can at least enable zooming + scrolling to begin with.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/037251c680b0aeed77e78e3cec839a78a56943ad
