### ISSUE TITLE
Web UI configuration

### ISSUE THREAD

**Issue by ar2rsawseen** [Countly/countly-server#160]
Plugin that will provide Web UI to allow to change frontend, api and plugins configuration files

**Comment by gorkem-cetin** [comment]
Is this the feature you are currently working on your instance? (178)?

**Comment by ar2rsawseen** [comment]
Not yet :)

I'm also overally thinking about config design and maybe we need something better

**Comment by ar2rsawseen** [comment]
Added in https://github.com/Countly/countly-server/commit/e848a92e0117896ddb5559bae1ca2fee85a57c43
