### ISSUE TITLE
No need for iptables command in installer anymore

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#164]
MongoDB has introduced the following in MongoDB config file: 

<pre>
# Listen to local interface only. Comment out to listen on all interfaces. 
bind_ip = 127.0.0.1
</pre>

So there's no need for iptables in installer.

**Comment by ar2rsawseen** [comment]
Since it is a security issue, would want to have more agreements.
What do @osoner and @iartem think?

**Comment by iartem** [comment]
This option was there for ages... Not sure what you guys mean. 

Iptables role is far from just dropping external connections to mongo. I know we used it just for this, but still. I'd rather modify config to block all external connections except for the ones to 80 & 22 ports. But this would definitely break the contract if someone tries to update the server and it just starts blocking everything. Or installs Countly and doesn't expect it to have iptables inside. 

May be it's worth adding a question to install script asking "Do you want to have Iptables block all incoming connections to ports other than 80 & 22?"?

**Comment by ar2rsawseen** [comment]
But isn't that server administrator part to provide such security to block all other connections.
We just need to manage stuff that keeps countly going and provide security for countly only, with less as possible OS level changes.

Also iptables persistant does not seem to work and iptables are reset after reboot now

**Comment by gorkem-cetin** [comment]
I believe that is more to be left to the sysadmin rather than us. We can provide suggestions, maybe lots of them but just like other solutions, this level of security is better handled with the person who knows internal rules & regulations.

**Comment by ar2rsawseen** [comment]
Ok, then let's put it in a separate script in scripts folder (just like make.swap.sh) so if anyone needs it, can run and block connections

**Comment by osoner** [comment]
I think instead of a script we should just write about this in our docs. We already have enough scripts. Also, I think UFW is a better option https://help.ubuntu.com/community/UFW and easier to use. One thing to note though, if ufw is enabled the first thing that should be done is to allow SSH access otherwise it will be blocked as well.

**Comment by ar2rsawseen** [comment]
Removed in https://github.com/Countly/countly-server/commit/ef4ffe8d2cef7238682bed4699c562aaa5bf59cf

and added script in https://github.com/Countly/countly-server/commit/34ebde22eff53c915347701a5750f19bbd2b7ee9
