### ISSUE TITLE
Installation fails at mobile plugin [Ubuntu 20.04]

### ISSUE THREAD

**Issue by UweTrottmann** [Countly/countly-server#1649]
### Expected Behavior
The installation script should complete without error.

### Current Behavior
The installation script fails after installing the `mobile` plugin.

```
Installing plugin "mobile"...
Done running npm install "mobile"
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodejs ENOENT 
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
        at onErrorNT (internal/child_process.js:465:16)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn nodejs',
  path: 'nodejs',
  spawnargs: [ '/home/REDACTED/countly/plugins/mobile/install.js' ]
}
```

### Your Environment

* Operating System and version:  Ubuntu 20.04.1 LTS
* Any changes you have made to your instance: n/a

I noticed the `plugins/mobile/install.js` is empty. Can that be a cause?

**Comment by ar2rsawseen** [comment]
Hello,
so usually that error means that file was not found, and that is the reason why it actually exists empty, to mitigate that error :D
Currently, we cannot reproduce this on our instances as well as our CI.

Can you share if it is your local Ubuntu or some VM in cloud?

**Comment by UweTrottmann** [comment]
It's running on a virtual server (KVM), the used storage driver is SCSI. File system is `ext4`.

And yes, it's weird because I can see and open the file as well...

**Comment by UweTrottmann** [comment]
Looking at the error this might actually be #1595. Should the `nodejs` package be installed (because it isn't)?

**Comment by UweTrottmann** [comment]
The Travis script expects the legacy `nodejs` command to exist, so I guess there is some legacy code that does, too.
https://github.com/Countly/countly-server/blob/cc74cb28dcf9f2be57ebca2fdbbbef7dc73aba2e/.travis.yml#L20

Workaround: add a symlink from `nodejs` to `node` using
`sudo update-alternatives --install /usr/bin/nodejs nodejs /usr/bin/node 100`

Then the installation continues.

**Comment by UweTrottmann** [comment]
The installation script is then stuck at
`Installing views plugin`

I guess support for Ubuntu 20.04 isn't ready (and I right now don't want to look into why it's stuck 😁), so I will try with the recommended 18.04 LTS release (still gets 2 years of updates, so is fine).

If it's of value, here is the installation log of my last attempt on 20.04:
[countly-install-2020-11-12-Ubuntu-20.04.log](https://github.com/Countly/countly-server/files/5535012/countly-install-2020-11-12-Ubuntu-20.04.log)

Thanks!

**Comment by ar2rsawseen** [comment]
What do you mean legacy?
`node` command actually switched to `nodejs` because of the name clashing with some other older package named node (https://packages.debian.org/source/wheezy/node)
There are even packages linking node to nodejs for backward compatibility (https://packages.debian.org/stretch/nodejs-legacy)
So as far as I know, nodejs should be the way to go, but if you have some other information, please share links :)

About being stuck at views, it seems it cannot bring the database up, so MongoDB was not installed or was not properly installed.

**Comment by UweTrottmann** [comment]
It looks like in `buster` the `node` binary name was restored. E.g. see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862051. 

You can also read about this in the `README.Debian` of [the buster nodejs package](https://packages.debian.org/buster/nodejs):
```
/usr/bin/node, /usr/bin/nodejs
==============================

"node" binary name is not available in stretch,
and is replaced by "nodejs".
"node" binary name is available in buster, and
"nodejs" is kept to avoid breaking old scripts.

However, the preferred name is "node" since it is
the upstream binary name.
```

However, the install script in this repo uses https://deb.nodesource.com/setup_14.x where the `nodejs` package from their `focal` repo only installs the `node` binary. That's why the install failed.

I'm not sure why they are not providing the symlink to `nodejs`, I can't find a decision or where to download the package source to inspect it.

**Comment by ar2rsawseen** [comment]
So they are changing it back and forth.
Ok, thank you, we will check it :)
