### ISSUE TITLE
Enable push notification preview functionality

### ISSUE THREAD

**Issue by rmacksoud** [Countly/countly-server#165]
We might want to consider showing push notification preview when creating a new message, sort of like this.  Don't know how much real value add this provides but I think people seeing a demonstration of this would get a better feeling and understanding.  Just a thought.

![image](https://cloud.githubusercontent.com/assets/13142147/8556112/ecc4bb74-24c2-11e5-85f7-b15ebd172e99.png)

**Comment by gorkem-cetin** [comment]
Richard - this is now being implemented and due version 16.10

**Comment by gorkem-cetin** [comment]
This will be done in 16.10.

**Comment by gorkem-cetin** [comment]
This feature is here & stable, so closing. 

Final release is due this week.
