### ISSUE TITLE
push notification "templates"

### ISSUE THREAD

**Issue by rmacksoud** [Countly/countly-server#166]
If I want to send the exact same push notification to a different segment of users, can I clone or somehow reuse an existing message?  We should probably  implement support for some kind of templates for messages.

**Comment by gorkem-cetin** [comment]
You can use a previously sent push notification as a template for another push notification. This can be done by clicking on the previously sent notification and then Duplicate button.

![duplicate](https://cloud.githubusercontent.com/assets/1757036/8567151/a038b1ee-256b-11e5-9030-eed4662a09e7.png)

That doesn't change the segment though.

**Comment by rmacksoud** [comment]
In order to be really useful as "templates" you should be able to duplicate
and then redefine the segment.  This seems like a logical capability since
I may have the same message I want to send to different segments or want to
modify a previously used message slightly for a new segment.


   [image: Countly Ltd] <http://count.ly/>

*Richard Macksoud* | *VP, Sales & Business Development*
Countly Ltd
rm@count.ly | 1.973.922.0726 <+19739220726> | https://count.ly
<http://count.ly/> <http://count.ly/>

   <https://twitter.com/rmacksoud>[image: Linkedin]
<http://www.linkedin.com/in/rmacksoud> [image: skype]
<http://www.googledrive.com/host/0B3DCOkELVvIMcmtRcWJPQUFFOXc> [image:
Twitter] <https://twitter.com/gocountly>

**Comment by gorkem-cetin** [comment]
+1
