### ISSUE TITLE
Error 404 while connecting localhost to countly

### ISSUE THREAD

**Issue by jamestechv** [Countly/countly-server#1662]
I am getting an error in countly.min.js file in line no 184 while trying to connect localhost port 85 to countly. Can anyone kindly point out what the issue is?
![cats](https://user-images.githubusercontent.com/73769785/99711438-c95b6280-2ac7-11eb-912f-6e0757108917.jpg)
![cats2](https://user-images.githubusercontent.com/73769785/99711495-d6785180-2ac7-11eb-91e1-13b4551ef50b.jpg)

**Comment by ar2rsawseen** [comment]
Hello
I only see a network error where SDK cannot connect to Countly server.
Are you sure Countly server is running on localhost:85?
can you check http://localhost:85/o/ping

**Comment by jamestechv** [comment]
Well ,that's the issue I'm facing, how to fix that network error .I'm not able to ping it at the moment as my windows is updating

**Comment by jamestechv** [comment]
Its shows error 404 while i ran it on http://localhost:85/o/ping.
![cats3](https://user-images.githubusercontent.com/73769785/99761117-4b28ab80-2b1b-11eb-993b-b08a6a0316e0.jpg).
The below one is my nginx config file source code incase that helps 
![cats4](https://user-images.githubusercontent.com/73769785/99761153-64c9f300-2b1b-11eb-9276-07dd51cd9ee8.jpg)

**Comment by ar2rsawseen** [comment]
So it looks like you nginx works on port 80, but you are trying to connect to 85.
so simply http://localhost/o/ping might work?

**Comment by jamestechv** [comment]
Thanks alot for the help ,the issue was sought out
