### ISSUE TITLE
countly not recording the information of : Browsers, platforms, languages

### ISSUE THREAD

**Issue by SejalParmar8796** [Countly/countly-server#1669]
Hello,
In countly V20.04.1, it is not recording all the information like browsers, platforms and languages.

**Comment by ar2rsawseen** [comment]
Hello :)
need more information:
What app type you use inside Countly dashboard? mobile, desktop or web?
What SDK do you use? Android, iOS, Web?
Where do you use it? Inside native app, HTML app or inside website?
