### ISSUE TITLE
Clarify when and why IAP event key should be used 

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#168]
Many questions come from users what an event key is, and whether they should add one here. Optionally, provide an explanation here. Attaching a suggestion: 

![iap_event_key](https://cloud.githubusercontent.com/assets/1757036/8735170/7f4920d8-2c17-11e5-9192-8fc00c2b63e8.png)

**Comment by darkz1984** [comment]
IAP not dispaly in countly server 16.02.1??
what happen?

**Comment by gorkem-cetin** [comment]
There are no changes with IAP. Can you explain what you have done, and what the result is, so we can help you.

**Comment by ar2rsawseen** [comment]
@darkz1984 it is enterprise only feature, as far as I know, so probably that is the reason

**Comment by darkz1984** [comment]
@ar2rsawseen   @gorkem-cetin  I use cloud version and community version , and the cloud version has this feature,community version not have this version...

**Comment by gorkem-cetin** [comment]
@darkz1984 as you can see here, IAP plugin (revenue analytics) is not available with Community Edition.

http://count.ly/compare
