### ISSUE TITLE
Providing countly CLI with an invalid arguement makes it show CLI correct usage infinitely.

### ISSUE THREAD

**Issue by rajat-np** [Countly/countly-server#1735]
### Expected Behavior
It should just show correct usage once. 

### Current Behavior
It keeps on showing correct usage infinitely.

### Steps to Reproduce (for bugs)

1. countly restartr
### Your Environment

* Operating System and version: Ubuntu 18.04
* Any changes you have made to your instance:  Change "ubuntu/xenial64" to "ubuntu/bionic64" in Vagrantfile.

**Comment by ar2rsawseen** [comment]
Hello
interesting, but I cannot reproduce this in the last nightly build.

if I input `countly restartr`

it just outputs all possible commands once, and that's it.

So you have it like in an infinite loop?

**Comment by rajat-np** [comment]
Yeah, like an infinite loop caused by any random invalid argument.

**Comment by ar2rsawseen** [comment]
Cannot reproduce
