### ISSUE TITLE
Countly-server for flutter push notification?

### ISSUE THREAD

**Issue by NTMS2017** [Countly/countly-server#1742]
Hi,

I am new so please bare with me.

First I install on my macOS (big sur) VmwareFusion Play free edition. Than on top it I install Ubuntu Desktop 20.04LTS.

Now before I install Countly-server (only for push notification) in System-Requirements page talks about installing NodeJS 14.x and MongoDB 4.4.x.

(Question-1): Should I install both NodeJS 14.x and MongoDB 4.4.x or just one? Does Countly-server uses both NodeJS 14.x and MongoDB 4.4.x and why?

(Question-2): Due to low resources I need to use Countly-server push notification only. So Is there and option to install only Push Notification module?

(Question-3): Because I want to test Countly-server push notification (for my flutter mobile app) on my MacBook, can I test push notification on my flutter app development using Countly-server community edition?

Thanks

**Comment by ar2rsawseen** [comment]
Hello
1. Yes Countly requires both
2. no, only everything together is possible
3. yes, it should be possible

But overall, we do not support Mac installation out of the box
