### ISSUE TITLE
UI issue with map on main dashboard 

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#176]
A small UI issue with the map numbers. Screenshot attached. 

![map](https://cloud.githubusercontent.com/assets/1757036/8994201/92757da4-3712-11e5-9f4a-95ede262ac3c.png)

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/d57c08d6d5f4d607fa33efc065dd1ad8b2835d74
