### ISSUE TITLE
Online users realtime chart labels conflicting with graph

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#177]
Online users realtime chart labels conflicting with graph, see screenshot. 

![online_users_real_time_chart](https://cloud.githubusercontent.com/assets/1757036/9022739/fe819096-3889-11e5-80af-3e5d5ac61909.png)

That could be fixed by moving MM:SS label like 10 pixels to the below

**Comment by osoner** [comment]
This is on purpose to save space and will be changed with the new design so closing it for now.
