### ISSUE TITLE
Send push notifications to specific device from API

### ISSUE THREAD

**Issue by dimohamdy** [Countly/countly-server#178]
How I can use API to send PN to specific device

**Comment by gorkem-cetin** [comment]
Here are necessary documents for this: 

http://resources.count.ly/docs/ipushescreate
http://resources.count.ly/docs/ipushesaudience
http://resources.count.ly/docs/ipushescheck
http://resources.count.ly/docs/ipushesrefresh
http://resources.count.ly/docs/ipushesdelete

You can find them all under http://resources.count.ly

**Comment by dimohamdy** [comment]
sorry this links not help me 
I change the structure of Countly SDk to get the generated DeviceID and send it to Backend that use it to send notification for only single user

https://github.com/Navirize/countly-sdk-ios

**Comment by dimohamdy** [comment]
please Accept the pull Request

**Comment by gorkem-cetin** [comment]
Thanks for the pull request. This is an issue basically for countly-server, so I'm closing it. Make sure you create an issue for iOS related issues on countly/countly-sdk-ios

Many thanks again for your contribution!

**Comment by black1987** [comment]
Hi there 
Would please give more explanation regarding the args arguments in the prepare and create requests.
The documentation is unfortunately not very clear and doesn't provide request samples that we as developers can use as guides.
Regards
