### ISSUE TITLE
Drill Bookmarking - Edit

### ISSUE THREAD

**Issue by osoner** [Countly/countly-server#179]
![image](https://cloud.githubusercontent.com/assets/1264036/9326642/eaf5528e-45a3-11e5-88e5-406c66b08e86.png)

Right now when a bookmark is applied, we can't see the applied filters in the filtering section;

![image](https://cloud.githubusercontent.com/assets/1264036/9326646/f8ecd79a-45a3-11e5-8a82-8404607cb324.png)

We need to show this in the filtering section so that the user can edit this and create a new bookmark etc.

**Comment by ar2rsawseen** [comment]
Done :)
