### ISSUE TITLE
Feedback - Cannot read property 'fnSettings' of undefined

### ISSUE THREAD

**Issue by Acolyte** [Countly/countly-server#1799]
### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/994225/114605381-b3328680-9ca2-11eb-92e3-2fb998fccc81.png)

### Steps to Reproduce (for bugs)
1. Log into Countly
2. Visit Feedback page
3. Click on Ratings list

### Your Environment
* Ubuntu 20.04
* Countly 20.11.1

### Issue log (from Chrome console)
[countly.vyyer.id-1618339948109.log](https://github.com/Countly/countly-server/files/6306027/countly.vyyer.id-1618339948109.log)

**Comment by frknbasaran** [comment]
Hello @Acolyte,

Thanks for the information that you provided. I just created a clean Countly Community (20.11.1) instance on an Ubuntu 20.04 server to reproduce your case, but I couldn't reproduce this problem. Could you provide more information, please?

- What is your app type? Mobile, desktop, or web?
- Did you run the data-populator plugin? If yes, which populator template did you use?
- Did you disable production mode from the configurations menu?
- Did you face a similar error on any other page/view?

 I'll try to help you after you provide answers to the above questions.

**Comment by Acolyte** [comment]
Hello @frknbasaran,
We've set up a mobile application and haven't used data populator, having mobile app plugged in right after the setup. The production mode is enabled. Currently it's the only page we've encountered this issue - the concern that was raised by mobile developer is that he sent a value of 0.

**Comment by frknbasaran** [comment]
Hello again,

Thanks for the answers that you provided. Could you please clarify what is mobile developer's concern exactly? 

Does your mobile developer think the app sent incorrect data to the server via SDK? If your data isn't sensitive, it would be great if you can share the BSON backup of the `feedback` collection from `countly` database.

**Comment by Acolyte** [comment]
Hi @frknbasaran, please find an archive with feedback data (and metadata) attached

[feedback.tar.gz](https://github.com/Countly/countly-server/files/6312947/feedback.tar.gz)

**Comment by frknbasaran** [comment]
Hello @Acolyte,

Sorry for the late response. I used the dump to try to reproduce your issue but couldn't reproduce it. I need more information to understand the problem. If the problem still exists, is it possible to create a test member for me in your instance?

Here is what you should do if it's possible:

- Create a new test application that doesn't contain any sensitive data.
- Be sure to this problem is reproducible in this app
- Create a user that only can access your test application
- And send it credentials to my mail address

If it's possible, here is my email address: fb@count.ly

**Comment by Vlad-M-1** [comment]
@frknbasaran,
Here is the Android code which broke ratings page on the newly deployed Countly:

        Countly
            .sharedInstance()
            ?.ratings()
            ?.recordManualRating(
                BuildConfig.COUNTLY_WIDGET,
                rating,
                "",
                wholeMessage,
                false
            )

• BuildConfig.COUNTLY_WIDGET contained widget ID.
• wholeMessage was "Test 0 " + some info about the device.
• rating was 0 (which was intended as a way to send only the text feedback).

**Comment by ar2rsawseen** [comment]
This was on old ui, we have new rewritten frontend now, so most probably this issue should not exist, but if you still encounter it, feel free to reopen :)
