### ISSUE TITLE
[Fixes for China] Google Fonts

### ISSUE THREAD

**Issue by osoner** [Countly/countly-server#181]
We need to move away from things delivered from google domain. The first thing to address is [these two fonts](https://github.com/Countly/countly-server/blob/master/frontend/express/public/stylesheets/main.css#L1) we get from Google Fonts.

Using http://www.localfont.com/, these fonts and their used variants need to be stored locally.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/5000668e7e3917a5cbf632993cf3187c99ed6dc0
