### ISSUE TITLE
[Fixes for China] Google World Visualization

### ISSUE THREAD

**Issue by osoner** [Countly/countly-server#182]
We need to change the dashboard, analytics > countries and drill (shown only when there is a BY filter for country) maps since they don't work in China. I'm proposing to switch to http://datamaps.github.io/.

![image](https://cloud.githubusercontent.com/assets/1264036/9416768/542dd272-4850-11e5-9f65-308caa66a56c.png)

**Comment by tianshuo** [comment]
@osoner Thank you so much!

**Comment by gorkem-cetin** [comment]
Fixed in 18.08 by switching to echarts.
