### ISSUE TITLE
[Fixes for China] Google Maps in Geolocations

### ISSUE THREAD

**Issue by osoner** [Countly/countly-server#183]
Well, the issue is obvious. Google Maps doesn't work in China so geolocations doesn't work either. Not really sure how to proceed here, Bing Maps? or configurable Baidu Maps option @iartem?

![image](https://cloud.githubusercontent.com/assets/1264036/9416827/a1c47252-4850-11e5-8360-f1a42a477a61.png)

**Comment by tianshuo** [comment]
Hi, could someone first fix the jquery cdn issue? That is top priority for us.

**Comment by iartem** [comment]
What issue are you referring to?

**Comment by osoner** [comment]
Hi, I think @tianshuo is referring to the fact that javascript file for the map is loaded from a CDN. Unfortunately the fix for this is not hosting the file locally. Google doesn't allow this and even if we can host it locally the script will still make calls to Google servers.

We started changing the world visualisation to DataMaps and will find a similar fix for push geolocations as well.

Sorry for the inconvenience and thanks for your patience!

**Comment by jianglinchun** [comment]
I'm working on echarts of Baidu.
http://echarts.baidu.com/doc/example/map1.html
http://echarts.baidu.com/doc/example/map4.html
I'll share the code ASAP.

**Comment by tianshuo** [comment]
I created a new issue ( #211 ) for what I mentioned previously.
If provinces in China is supported, that would be great.

**Comment by osoner** [comment]
@jianglinchun did you have any chance to complete eCharts support?

**Comment by jianglinchun** [comment]
@osoner I'm busy with my jobs now. And I'd successfully developed a new plugin which used echarts. I may submit the pull requests within 1-2 month.

**Comment by jianglinchun** [comment]
@osoner I had fix the problem. But I'm not sure UE and the code guideline. Or should I and a switch to the config?

**Comment by gorkem-cetin** [comment]
@jianglinchun can we have a skype telco for this if you are done with your plugin? :) That would be really great if we can come up with a solution that can be used for China, and include it in next release if you are also comfortable with that. 

Awaiting for your reply.

**Comment by jianglinchun** [comment]
@gorkem-cetin thank you for your attention. I'd checkout the latest countly branch and I found a google service switch was added to the config panel. So I thought I should modify my code and use the switch value to decide when to switch to echarts. 
And my skype id: jianglinchun@live.com :)

**Comment by gorkem-cetin** [comment]
That exactly would work like that, unless @ar2rsawseen has another idea.

**Comment by ar2rsawseen** [comment]
Yes, the check for setting is actually quite simple:
https://github.com/Countly/countly-server/blob/master/plugins/mobile/frontend/public/javascripts/countly.views.js#L16

**Comment by jianglinchun** [comment]
please check this pull request:
https://github.com/Countly/countly-server/pull/273
