### ISSUE TITLE
User documentation for Push notifications

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#184]
Currently push notifications document is not very extensive and we need a proper end user push notifications documentation on http://resources.count.ly

**Comment by iartem** [comment]
In order to make documentation more extensive, we need more extensive task description :)

**Comment by gorkem-cetin** [comment]
Ok, so we need a user guide, which could be similar to:

* http://resources.count.ly/docs/introduction-to-crash-reporting-and-analytics
* http://resources.count.ly/docs/user-profiles
* http://resources.count.ly/docs/referral-analytics

I'd suggest the titles to be: 

* What is a push notification
* Push notifications for Android
* Push notifications for iOS
* Sending a new message
* Viewing messages
* Troubleshooting

Document should assume that all certificate / Google API key / Androidmanifest.xml etc related things have been done previously, and user should clearly be directed to and informed about relevant Android SDK & iOS SDK documentation beforehand. 

Therefore this documentation should only deal with end user related tasks to be done.

**Comment by gorkem-cetin** [comment]
Mostly done, so closing.
