### ISSUE TITLE
User should be warned in funnels if no custom events are collected

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#186]
Currently in Funnels, if no events are collected, pop-down doesn't show any events. When clicked on this pop-down, user may better be warned with a sentence like: 

"You need to collect some custom events for Funnels to work"

What do you think?

**Comment by ar2rsawseen** [comment]
Makes sense, it might be confusing if someone opens Funnel view and don't understand why he can't do anything

**Comment by ar2rsawseen** [comment]
Added
