### ISSUE TITLE
Rhel7 Pip fix for countly installation.

### ISSUE THREAD

**Issue by thatsk** [Countly/countly-server#1866]
countly instllation break in 20.11

### Expected Behavior
it should install countly without error.

### Current Behavior
/opt/countly/bin/countly.install.sh
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==21.0', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packag
### Possible Solution
https://github.com/Countly/countly-server/blob/master/bin/countly.install_rhel.sh#L55
this line should be replaced with 
```
pip install --upgrade "pip < 21.0"
```

### Your Environment
centos7.9

**Comment by thatsk** [comment]
More info you can found at .
https://exerror.com/python-pip-broken-wiith-sys-stderr-writeferror-exc/

**Comment by ar2rsawseen** [comment]
@kaanklky and @itsiprikshit your thoughts? :)

**Comment by kaanklky** [comment]
Thank you for you report @thatsk,
The line that you mentioned for replacement is commented out & it is not the one which break the installation as far as I can see; `pip` becomes broken after this line: https://github.com/Countly/countly-server/blob/master/bin/countly.install_rhel.sh#L56.
Working on it. :)

**Comment by kaanklky** [comment]
Fixed.
