### ISSUE TITLE
Override web/api ports using docker env variables

### ISSUE THREAD

**Issue by multinerd** [Countly/countly-server#1887]
Is it possible to change the port for the web and api docker containers?
If not, having this possibility can be useful, especially when the current ports are already in use, for example a preexisting container that uses the same port (minio defaults to 3001)

### Expected Behavior
Pass a variable like `COUNTLY_CONFIG_API_PORT` in the docker env 

### Current Behavior
Doesn't look like it currently exists.

**Comment by iartem** [comment]
Hi @multinerd, 
Passing that variable would indeed override Node.js port Countly uses, but I'm not sure if it's possible to override the Dockerfile port. Is it? Also could you describe why you cannot map the port to something else when running the container?

**Comment by multinerd** [comment]
Ok, nvm. i see how it overrides the configs. I was looking for the actual env name, I see its dynamically done in `configextender.js`. Im closing this issue.
