### ISSUE TITLE
Support for context path/ mounting

### ISSUE THREAD

**Issue by rosner** [Countly/countly-server#19]
Hi folks,

right now I use one machine to deploy all my analytics stuff (sentry, countly). Usually I run those services so that they only listen on localhost. Then I use nginx to proxy the calls to the individual services. Sometimes there's also load balancing involved through nginx' upstream module.

Since I want to run all services as "subdirectories" it would be necessary that countly supports something like this:
``` javascript
var countly = express.createServer();
countly.use('/countly', app);
countly.listen(countlyConfig.web.port);
```
So my final setup would look something like this:
```
x.company.com/sentry
x.company.com/countly
x.company.com/countly/i
x.company.com/countly/o
```
What do you think of supporting this?

**Comment by ar2rsawseen** [comment]
Implemented in https://github.com/Countly/countly-server/commit/b657d76128eaa94e48bbd393feee7782d0135778
Same server config required as mentioned by @osoner 
and also definition in countly config.js files in both api and frontend should define countlyConfig.path = "/countly"
