### ISSUE TITLE
Untranslated strings on dashboard

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#192]
Untranslated strings: 

Showing X to Y of Z entries
Feedback & support

We may keep this issue open for some time, or reopen if more non-translatable strings occur.

**Comment by ar2rsawseen** [comment]
Maximum number of applications to be compared (10)
Provide feedback
Support
Documentation

**Comment by ar2rsawseen** [comment]
All strings added to localization.
So should this issue be closed and reopened when new untranslated strings found?

**Comment by gorkem-cetin** [comment]
Ok to me
