### ISSUE TITLE
Enterprise info plugin needs to be rechecked for consistency and update

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#196]
There are a few additions to Enterprise-Info plugin and maybe some redundant parts could be removed.

**Comment by ar2rsawseen** [comment]
Enterprise info does not have info about these plugins:
Referral Analytics
Flows
Geo push
Live/Online

**Comment by gorkem-cetin** [comment]
Referral analytics (sources): 

Referral analytics allows you to measure your marketing campaign performance by attributing installs from specific campaigns.

Additionally you can target users from different platforms differently, by providing specific end URL for each platform and Count.ly will automatically redirect visitor to specific URL based on what platform visitor is using.

You can also manage single campaign with single Countly generated URL for both Android and iOS users each pointing to their own app market link.

**Comment by gorkem-cetin** [comment]
Flow: 

A flow visualization is a graphic that a traces a route or a path. With Flows, it's possible to see the steps users take to reach each page, or each event, depending on whether you track web pages or mobile apps. You can apply any filter like device, city, country, local hour, carrier and more. Each bubble can represent number of sessions or number of users. Since it's possible to segment with campaign, it's possible how traffic is engaging with your content and look for especially overperforming or underperforming campaigns or sources.

**Comment by ar2rsawseen** [comment]
Added them.
Anything else? :)

**Comment by gorkem-cetin** [comment]
I'll add screenshots about those two items as well as geopush desc. I think these should be enough. Already too much information there.
