### ISSUE TITLE
UI layout broken when viewing a scheduled push in TR locale

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#197]
When I schedule a push in UI locale and then acknowledge it for later sending, all seems to be good UI-wise. However when I click on the push message to be viewed, UI is broken. 

Screenshot: 

![ekran resmi 2015-09-26 18 37 39](https://cloud.githubusercontent.com/assets/1757036/10118277/65be4550-647d-11e5-8b9b-90d6a7559036.png)

**Comment by gorkem-cetin** [comment]
Fixed with your commit?

**Comment by iartem** [comment]
Should be, but worth checking

**Comment by gorkem-cetin** [comment]
Looks good :)
