### ISSUE TITLE
Error Install latest Countly Ubuntu 14.04 or Ubuntu 14.10

### ISSUE THREAD

**Issue by longtq-setacinq** [Countly/countly-server#199]
sh ./countly.install.sh
............................................
Err http://ppa.launchpad.net trusty/main Sources
  404  Not Found
Err http://ppa.launchpad.net trusty/main amd64 Packages
  404  Not Found
Err http://ppa.launchpad.net trusty/main i386 Packages
  404  Not Found
Ign http://ppa.launchpad.net trusty/main Translation-en_US
Ign http://ppa.launchpad.net trusty/main Translation-en
Err http://ppa.launchpad.net trusty/main Sources
  404  Not Found
Err http://ppa.launchpad.net trusty/main amd64 Packages
  404  Not Found
Err http://ppa.launchpad.net trusty/main i386 Packages
  404  Not Found
Ign http://ppa.launchpad.net trusty/main Translation-en_US
Ign http://ppa.launchpad.net trusty/main Translation-en
Fetched 548 kB in 52s (10,5 kB/s)
W: Failed to fetch http://ppa.launchpad.net/webupd8team/jupiter/ubuntu/dists/oneiric/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/webupd8team/jupiter/ubuntu/dists/oneiric/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/webupd8team/jupiter/ubuntu/dists/oneiric/main/binary-i386/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/lucid-bleed/ppa/ubuntu/dists/trusty/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/lucid-bleed/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/lucid-bleed/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/texlive-backports/ppa/ubuntu/dists/trusty/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/texlive-backports/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/texlive-backports/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

can anyone please help me ?

**Comment by gorkem-cetin** [comment]
Either your Ubuntu box is temporarily not connected to internet, or there's a problem with the remote repository. Either way, I'd suggest that you try again after issuing an "apt-get upgrade" with root access.

**Comment by damvantai** [comment]
I don't know solution but i change server to use in software update, 
it is good!!

**Comment by ar2rsawseen** [comment]
So it means repo server was down.
Closing issue
