### ISSUE TITLE
Calendar bug in Messaging plugin

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#200]
There's a calendar popup window bug disappear issue within calendar selector inside messaging plugin only. 

How to produce: 

1. Go to messaging 
2. Create a message (or go to messaging > messages, and select a message) 
3. Open push sending popup, and then click on scheduling > send later
4. Calendar pops up.
5. Select next month 
6. Calendar closes immediately not allowing to select a day.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/6e49bfc01531adbabd33350b029b47e79b59abb4
