### ISSUE TITLE
Lighthouse error "Registers an unload listener" from the tracking script

### ISSUE THREAD

**Issue by flayks** [Countly/countly-server#2019]
I've seen when running a Lighthouse test on one of my websites that the tracking script provided from Countly is apparently registering an unload listener. This penalizes the score of the website by 7 for Best practices, which could easily be fixed I believe.

From the Lighthouse [Page Lifecycle API](https://developers.google.com/web/updates/2018/07/page-lifecycle-api?utm_source=lighthouse&utm_medium=devtools#the-unload-event), they recommend this:

> The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Consider using the `pagehide` or `visibilitychange` events instead.

![image](https://user-images.githubusercontent.com/273716/132534719-8ec66349-dc72-4d72-9034-a2fec7a3ed6e.png)

That would be great to get back a score of a 100 for Best practices!

**Comment by ar2rsawseen** [comment]
Hello,
just wanted to make sure, does it really corelate to server and not https://github.com/Countly/countly-sdk-web? :)

**Comment by flayks** [comment]
@ar2rsawseen not totally sure to be fair. I'm not using the web SDK here. Should I maybe add it there instead?

**Comment by ar2rsawseen** [comment]
you say ` tracking script provided from Countly ` so that is usually web SDK that tracks it and sends data to Countly server, so yes, please open issue there :)

**Comment by flayks** [comment]
Sure, no problem!
