### ISSUE TITLE
Is it possible to limit certain user details get pushed?

### ISSUE THREAD

**Issue by variable** [Countly/countly-server#2021]
Currently countly pushes user data (automatically?) as below:

![image](https://user-images.githubusercontent.com/558175/132594761-0d7a9a27-6e14-4527-a629-63b19506ed2f.png)

Is it possible to say exclude certain form fields eg. username?

**Comment by ar2rsawseen** [comment]
Hello,
user_details field should not be pushed automatically.

It is either explicitly set through SDK methods
or implicitly by enabling SDK features, like https://support.count.ly/hc/en-us/articles/360037441932-Web-analytics-JavaScript-#automatically-fill-user-data

If you can share your SDK integration code, we can help you pin point the culprit :)

**Comment by variable** [comment]
Thanks @ar2rsawseen that makes sense.
