### ISSUE TITLE
Warning button and accept button colors in populator plugin to be modified

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#209]
Populator plugin button coloring better be Cancel -> Red and Continue -> Green

![shot](https://cloud.githubusercontent.com/assets/1757036/11189221/a89ee7f2-8c97-11e5-92e7-826de61f6e63.png)

**Comment by osoner** [comment]
I think this is good as is. Because when you "Continue" you are doing something you can ruin your data and that should be red. And "Cancel" is gray in all other popups so consistent.

**Comment by gorkem-cetin** [comment]
I thought so, before opening the bug and tried to convince myself not to go with this issue. Since we are already warning him there, and the red button calls for a "cancellation" and "refusal" in minds, thought to move forward. 

Feel free to close - both ways are equally right (or wrong) to me :-)

**Comment by ar2rsawseen** [comment]
Were there any complaints or confusion with this? Because, yes, currently it is consistent with other popups, as when clearing data

**Comment by gorkem-cetin** [comment]
No complaints other than me, so feel free to close it and open if necessary :)
