### ISSUE TITLE
[Fixes for China] add jQuery fallback

### ISSUE THREAD

**Issue by tianshuo** [Countly/countly-server#211]
Now jquery is using google's cdn, please add a fallback if it cannot be loaded.

**Comment by ar2rsawseen** [comment]
Hello,
which version of Countly are you using?
because I checked the latest version, and while there are dependencies on google libs. Jquery is definitely not one of them and was bundled together with Countly for quite some time now.

Can you maybe post more specific error that you encounter?

**Comment by jianglinchun** [comment]
Works for me now. beijing, china

**Comment by smoothdvd** [comment]
Everybody, you can use 360's http://libs.useso.com to "FIX" google js api problem. FUXX GFW.

**Comment by ar2rsawseen** [comment]
@smoothdvd unfortunately it does not have this:
https://developers.google.com/chart/

**Comment by ar2rsawseen** [comment]
In 16.02 we have a configuration setting under Management -> Configuration, to disable Google services, so the dashboard properly loads for users who can't access them. So I'm closing this issue

**Comment by smoothdvd** [comment]
Great works，thanks.
