### ISSUE TITLE
Countly API References does not generate demo code correctly.

### ISSUE THREAD

**Issue by multinerd** [Countly/countly-server#2118]
I am trying to create a library to communicate with countly's REST APIs, mainly the Push APIs.

On the [api reference page](https://api.count.ly/reference/ipushescreate), each endpoint has a [response](https://user-images.githubusercontent.com/6367998/139944357-2a71f3aa-57a7-45c3-8b7f-09c215f24c87.png) section which shows the api results in json format. This is very useful as I can just dump the JSON into something like [this tool](https://app.quicktype.io/) and generate a model class for my language.

On the same page, theres a section that shows [demo code](https://user-images.githubusercontent.com/6367998/139944748-762893c5-84f6-4b79-a082-ab415eca2a0a.png) for a given endpoint. The problem with the demo code is that endpoints that require form data shows a javascript string representation of an object (`[object Object]`)

For example,

- Node.js
  ```nodejs
  encodedParams.set('args', '[object Object]');
  ```
- Ruby
  ```ruby
  request.body = "args=%5Bobject%20Object%5D"
  ```
- GO
  ```go
  payload := strings.NewReader("args=%5Bobject%20Object%5D")
  ```
- .Net
  ```c#
  request.AddParameter("application/x-www-form-urlencoded", "args=%5Bobject%20Object%5D", ParameterType.RequestBody);
  ```

It looks like cURL is the only language that produces a valid json. 
```bash
curl --form 'args={"apps":["APP_ID"],"platforms":["a", "i"],"tz":false,"test":true,"type":"message","messagePerLocale":{"default": "Default message","en": "Message in English","de": "... in Deutsch","ru": "... на Русском", "default|t": "Default message title", "default|0|t": "Default button 0 title", "default|0|l": "http://default.button0.link.com", "default|1|t": "Default button 1 title", "default|1|l": "http://default.button1.link.com", "ru|t": "Заголовок сообщения на Русском", "en|1|t": "Button 1 title in English"},"userConditions":{"custom.age":"18"},"locales":[{"value":"default","title":"Default","count":1,"percent":100},{"value":"en","title":"English","count":1,"percent":100}], "buttons": 2, "sound":"default","media": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png", "source":"dash"}' https://example.com/i/pushes/create?api_key=API_KEY
```

Sorry if this is the wrong place to post, the documentation repo seems to be limited to sdk intergration and not the APIs and i did not find a API repo.

Update: It looks like it doesnt work for all cURL code.

![image](https://user-images.githubusercontent.com/6367998/139948371-dc834d03-31a1-416c-bde1-bd29da64d664.png)

**Comment by multinerd** [comment]
Update: It looks like it doesnt work for all cURL code.

![image](https://user-images.githubusercontent.com/6367998/139948371-dc834d03-31a1-416c-bde1-bd29da64d664.png)

**Comment by ar2rsawseen** [comment]
This bug should be reported to readme.io, but I think they fixed it
