### ISSUE TITLE
User login page Enterprise Edition information widget box not localizable

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#212]
When enterpriseinfo plugin is installed, then main login page comes with a list of features next to username-password entry dialog. This part is not localizable yet, but should be. 

![loc](https://cloud.githubusercontent.com/assets/1757036/11374677/f85fa9c2-92df-11e5-806f-ec322e8c3e18.png)

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/75ebbecea03154d92321219f29fdd07f88103043
