### ISSUE TITLE
Any Differences among those edition for iOS codes?

### ISSUE THREAD

**Issue by ivanyang1984** [Countly/countly-server#217]
we are now intending to use the countly ios for uploading the user track info to our own server.  i have read the information in your homepage. i saw the difference among the self-hosted, cloudy edition, saas, and enterprise edition.  I now confused  where is difference on IOS sdk?

**Comment by gorkem-cetin** [comment]
There are no differences between iOS SDKs. All SDKs are the same among different Countly Editions, and all SDK source code is available from Github.

**Comment by ivanyang1984** [comment]
thanks a lot!

**Comment by gorkem-cetin** [comment]
You're welcome.
