### ISSUE TITLE
Hybrid Mobile app support : Ionic

### ISSUE THREAD

**Issue by YatinGrover** [Countly/countly-server#222]
I am developing a cross platform app using Ionic Framework and could't find any documentation for integrating countly push notification with angularjs/ionic/cordova.
There is very clear documentation for android and ios separately but same is missing for ionic. The example on github(phonegap example) doesn't run straightaway and the countly.js is lacking explanation on GCM integration.
Can you please provide some resources for implementing push notification in mobile apps created using ionic via countly.

**Comment by gorkem-cetin** [comment]
We can help. Could you create this issue on the following repository?

https://github.com/countly/countly-sdk-js

I'm closing this now, as it's related directly to server side, but would be willing to help on a new thread you will create. 

Thanks.
