### ISSUE TITLE
It looks like CDN in the installer script is no longer working now

### ISSUE THREAD

**Issue by stormyyd** [Countly/countly-server#2226]
It seem like CDN provided in installer.sh "http://countly-1252600587.cos.ap-guangzhou.myqcloud.com/" is not working now.

### Screenshots (if appropriate):

<img width="988" alt="countly-cdn-error-1" src="https://user-images.githubusercontent.com/4938213/147065404-52fd022c-49fc-4b77-8f1e-2e0664fb30a2.png">

And trying access it by browser:

<img width="762" alt="countly-cdn-error-2" src="https://user-images.githubusercontent.com/4938213/147066070-8949b379-fdfe-4eba-9594-c5157b67b1b5.png">

Also got 404.

### Possible Solution

If CDN provider will no longer provide any service, I suggest you guys to remove related code. Or maybe you just need to update CDN info?

**Comment by ZeroJsus** [comment]
same question. need a solution.

**Comment by ar2rsawseen** [comment]
Hello
we had a dedicated contributor support packages for that repo for China downloads, unfortunately he does not support that anymore, so we will be removing this from the install script
