### ISSUE TITLE
Remove category selection during adding a new app

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#224]
I dont think there is a need for a category selection in the initial screen, what do you think? 

@osoner @ar2rsawseen

**Comment by ar2rsawseen** [comment]
This field is not required anymore and is commented out, so we can say it is removed, but can easily come up if/when needed :)

https://github.com/Countly/countly-server/commit/0c85611c8e4f77c1147955860438e7b902b80b25
