### ISSUE TITLE
In-app help for Versions and Languages

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#225]
For Versions tab: 

This page shows different versions of applications, in case they are defined. A stacked chart shows totel sessions and new users. The table under the chart shows total sessions, total users and new users, respectively for each application version. 

For Languages tab: 

Pie chart on the left shows percentage of total users or visitors with each language. Pie chart on the right shows percentage of new users or visitors with each language. This information is the language of the browser or the mobile device.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/8058f5c4bfb3a413f96b10c23933a8bf73e737f5
