### ISSUE TITLE
countly server error and not display and graphic.

### ISSUE THREAD

**Issue by darkz1984** [Countly/countly-server#229]
I test countly server  on ubuntu,and android sdk .The version is 15.08.

From the web page I can see event logs,and it ok,but I can't see any graphic ,such as online and users.
when I see the system log,the "api log" and "dashboard log" show me the same error blew:

[Error: countly/node_modules/mongodb/node_modules/bson/build/Release/bson.node: invalid ELF header]
[2016-02-17T07:32:23.613Z] js-bson: Failed to load c++ bson extension, using pure JS version

I think this cause there on graphic on the web.,..

**Comment by ar2rsawseen** [comment]
Hello,
make sure you are using code from release, not simply from master branch.
Did you download it from release?

**Comment by ar2rsawseen** [comment]
A month inactivity and no response, closing issue.
Please reopen it, if you still have problems
