### ISSUE TITLE
how can stop or uninstall  the countly server on linux mint

### ISSUE THREAD

**Issue by bogere** [Countly/countly-server#230]
PLease could help me to uninstall or stop the countly server on my linux mint because it seems it is blocking the path to mongodb because connect-mongo  has failed to connect to mongodb ....
even meteor has failed to run on the default port 3000. I installed it using the bash script.
I have tried to stop the countly process using this command.
stop countly-supervisor;
just  getting this message....    
`stop: Rejected send message, 1 matched rules; type="method_call", sender=":1.50" 
(uid=1000 pid=6638 comm="stop countly-supervisor ") interface="com.ubuntu.Upstart0_6.Job" member="Stop" 
error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init")`

**Comment by ar2rsawseen** [comment]
Hello, you need to run stop countly-supervisor as root user

**Comment by bogere** [comment]
Thank you very much
