### ISSUE TITLE
Easier to understand configuration parameters with explanations

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#232]
![one liner explanation](https://cloud.githubusercontent.com/assets/1757036/13394888/e28d6732-def3-11e5-91bd-555f0bbf664a.png)

Configuration page needs a simple, one liners for easier understanding of parameters.

Production mode: If enabled, serves minified, combined files.
Theme: Selected theme will be available server-wide, for all apps and users.
Session timeout in ms: User will be forced to logout after this time if he doesn't make any actions.
Server URL: This is the full qualified domain name used in outgoing emails.
Safer API responses: If enabled, server will verify key parameters and respond with error or success.
Maximal Session Duration: Maximum amount of time that should pass before server closes the session.
Track city data: Enable tracking city level data in dashboard.
Max unique event keys: Maximum number of event keys stored in database.
Max segmentation in each event: Maximum number of segmentations per custom custom events.
Max unique values in each segmentation: Maximum number of unique values in each segmentation.
Default Country: Default country to be used when creating app with API and without a country.
Default Category: Default category to be used, when creating app with API and without a category.
Logs (debug, info, warning..): Level of debug info to output into log file under /log directory.
Amount of reports displayed: Amount of reports to display in each crash group's page.

**Comment by ar2rsawseen** [comment]
Added in https://github.com/Countly/countly-server/commit/4544aa39a070ba62c48f75df88af9d5f41cc327d
