### ISSUE TITLE
DigitalOcean Marketplace Listing 404's

### ISSUE THREAD

**Issue by 4lch4** [Countly/countly-server#2337]
### Expected Behavior
When loading the DigitalOcean Marketplace listing mentioned in the README, I'd expect the listing to actually load instead of returning an error.

> Oh no! We couldn't find the page you were looking for.

### Current Behavior
When navigating to the listing, an error is returned saying it could not be located.

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/6931731/149822012-d89499a8-627b-4ea0-9da9-25c0b5470bd4.png)

### Possible Solution
Remove or update the link to the new listing (if it exists).

### Steps to Reproduce (for bugs)
1. Open the README and navigate to the [Installing and upgrading Countly server](https://github.com/Countly/countly-server#installing-and-upgrading-countly-server).
2. Click the link for option 2: `"If you have a Digital Ocean account, click here and install on Digital Ocean with a single click."`

**Comment by ar2rsawseen** [comment]
Hello,
thank you for reporting, checking with Digital Ocean One click team support

**Comment by ar2rsawseen** [comment]
This was resolved now by Digital Ocean team :)
