### ISSUE TITLE
Few docker issues

### ISSUE THREAD

**Issue by kayone** [Countly/countly-server#236]
I've been trying to use the docker container but I've been running into a couple of issues,

- I would really suggest you de-couple the mongo process from the countly server container and letting users connect a dedicated mongo container to the server container, using docker's `--link` command param.
- there is no volume defined for data in the dockerfile, so even when trying to mount `/data` so data is persisted doesn't really work, and everything is lost when the container is restarted.

**Comment by iartem** [comment]
Thanks for your report @kayone. Do you say that https://github.com/Countly/countly-server/blob/master/Dockerfile#L14 doesn't work?

**Comment by kayone** [comment]
well, it doesn't look like it, I've mounted that volume to a local folder, but restarting the container still causes the app to lose all data, the mount might work, but maybe it's not where the data is being saved to?

also check the mount point on the host and the folder is empty,

**Comment by gorkem-cetin** [comment]
Fixed in https://github.com/Countly/countly-server/commit/d7d2b5126166ad6977c224bbfa53794551dabdaf
