### ISSUE TITLE
More explanations for /dashboard#/manage/configurations

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#237]
Some more explanations for /configurations

- Allow users invite other users: When enabled, a user can invite another user via email to view dashboard.
- Funnel step limit: Number of steps that can be generated and used in a single funnel.
- Describe what parameters can be used for Logs (e.g "Enter system wide modules here to give more information. Modules may include jobs, push"). This informative sentence can be placed right at the top of Logs table.
- debug: Log fine-grained informational events that are most useful to debug an application. 
- info: Log informational messages that highlight the progress of the application.
- warning: Log potentially harmful situations.
- error: Log error events that might still allow the application to continue running.
- There is no "warn" log level but "Default" has it on your server.

**Comment by ar2rsawseen** [comment]
Added in https://github.com/Countly/countly-server/commit/237f895a2bae6a79cae58b80538c4356296f22df
