### ISSUE TITLE
data privacy

### ISSUE THREAD

**Issue by Henner** [Countly/countly-server#24]
Hi,

to use this software in europe, you need to ensure, that you fit to the european data privacy policies.
In the first place, anonymization of IP addresses - or what even makes it possible, to identify a user (device token, etc.).

Is there a possibility to fit these regulatory needs?

regards
Henrik

**Comment by jcgruenhage** [comment]
Why was this closed? I just realised that countly is logging IPs together with all reports, which is not what I want at all :D

**Comment by gorkem-cetin** [comment]
Where do you exactly see that Countly logs IPs?

**Comment by jcgruenhage** [comment]
In the event log. Every event is recorded together with a user ID and their current IP.

**Comment by jcgruenhage** [comment]
![screenshot from 2017-03-30 11-30-11](https://cloud.githubusercontent.com/assets/6861958/24497684/866b2dd8-153c-11e7-8867-d40aaf7c5fb6.png)

I've censored the IP and Device ID, but it should be obvious what I mean.

**Comment by gorkem-cetin** [comment]
Yes, that is event logs, which is used for debugging purposes. Each line has a limited life span (eg. FIFO). In case a customer asks to opt out of saving IPs, then this plugin is simply removed and IP related data is never stored. You can also do the same - disable or delete this plugin and you are done.

Again, thanks for clarification. We really care about end user privacy and if there is something else that we can help you achieve your goals about security and privacy, do not hesitate to let us know.

Hope that helps.

**Comment by jcgruenhage** [comment]
So there are no traces of IPs, if I disable the event log?

**Comment by ar2rsawseen** [comment]
You can also drop all collections starting with logs in countly database, if you want to make sure

**Comment by jcgruenhage** [comment]
Well, since I have not published a binary yet, the only logs I have are from myself and one other person, that compiled the app themselves, that should be fine ^^

**Comment by ar2rsawseen** [comment]
Just FYI, removed ip address from being recorded and shown by event logger:
https://github.com/Countly/countly-server/commit/56c46a6391d81ae4a87b2caa531dc40ce19d3d77

**Comment by jcgruenhage** [comment]
So I can go enable that again, after the next update? Nice, thank you :)
I just feel like that is information that is not needed. The city (will that still be displayed?) is already enough/more than enough.

**Comment by ar2rsawseen** [comment]
Yes, we felt the same way, that it is not needed.
And yes Country/City still will be displayed (if it is possible to retrieve it through IP value, but IP will not be recorded)

**Comment by jcgruenhage** [comment]
So it will use the IP to get that data, but not store it afterwards? Sounds perfect to me :) 

I have to say, I am very happy, that I have chosen countly, your support is great ^.^
