### ISSUE TITLE
Warn if countly command is not run as root

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#243]
It's possible that end users may run countly command without root priviledges. 

This is how to check it: 

```
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

```

**Comment by ar2rsawseen** [comment]
Added in https://github.com/Countly/countly-server/commit/807fa722074b63fa55b881fec8b3cee69553180b
