### ISSUE TITLE
Emphasize App key to be used in SDK

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#249]
Attached is the screenshot of the applications page. App ID is on top and App key is on 4th page. Both variables are tied to a specific application. The problem is while documentation clearly says that App key should be used, quite a big deal of developers use App ID (might be because it's on top). 

One option is to move App ID below App key and write a description for App key so it's used inside SDK. 

![appkey-appid](https://cloud.githubusercontent.com/assets/1757036/14227752/43d0d78a-f90d-11e5-9158-38d72c455c64.png)

**Comment by osoner** [comment]
Arturs, I got this

**Comment by osoner** [comment]
Fixed in 5c56c5190a558b05c1755ae4ddba17dce409a77c
