### ISSUE TITLE
ERROR: cannot verify raw.githubusercontent.com’s certificate

### ISSUE THREAD

**Issue by wonderful60** [Countly/countly-server#251]
HI,when i execute the shell script below,an error occurred always.I hope someone can help me, thank you!
```
[root@test bin]# countly update sdk-web
ERROR: cannot verify raw.githubusercontent.com’s certificate, issued by “/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA”:
  Issued certificate not yet valid.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’.
ERROR: cannot verify raw.githubusercontent.com’s certificate, issued by “/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA”:
  Issued certificate not yet valid.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’.
```

I try the way http://stackoverflow.com/questions/27144426/error-the-certificate-of-raw-githubusercontent-com-is-not-trusted ,but it was useless.

**Comment by gorkem-cetin** [comment]
What happened after you tried out what is written on SO? Can you paste the error here?

**Comment by wonderful60** [comment]
the problem is solved by installing centos7,tks!

**Comment by ar2rsawseen** [comment]
I added --no-check-certificate to wget call, thank you for reporting
https://github.com/Countly/countly-server/commit/aed3b0e76e4f93507c62d19fb3dac01028344e23
