### ISSUE TITLE
Missing Fonts with Ubuntu installation

### ISSUE THREAD

**Issue by schwedenmut** [Countly/countly-server#256]
Just installed the recent version of countly-server (Countly Community Edition v16.02.1) on my Ubuntu vserver and noticed, that there are some errors in the browsers console referring to missing fonts in the folder `/stylesheets/fonts/*` . Actually i noticed, that there is no such folder named _fonts_ in this folder.

![unbenannt-1](https://cloud.githubusercontent.com/assets/9077622/14763652/ee448f42-099b-11e6-9856-314a838e6a63.jpg)
I didn't look into the code, but did a Symlink ```ln -s ~/countly/frontend/express/public/fonts ~/countly/frontend/express/public/stylesheets/fonts``` and now the error is gone and the UI uses the desired fonts.

**Comment by ar2rsawseen** [comment]
Yes, that was already fixed internally and will be available in next version, but thank you for submitting it ;)

https://github.com/Countly/countly-server/commit/3260b1325625a0e96c2bca9bab89fcb610db8216
