### ISSUE TITLE
Better explanation for "crash does not exist" error

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#265]
Instead of "Crash does not exist" message, how about this one? 

This crash report cannot be viewed. Possible reasons:

1. You are trying to view a crash report that you do not have access to.
2. Link to this crash is invalid.

[ OK ]

**Comment by ar2rsawseen** [comment]
If we have the same for user profile and attribution campaign, could it be changed to something more generic, like

This content cannot be viewed. Possible reasons:
..etc...

?

**Comment by gorkem-cetin** [comment]
I think we could be doing that, if there is less context specific to crash inside the warning. But I believe it's not worth. Let translators do their work :-D

**Comment by osoner** [comment]
@ar2rsawseen let's not add secret features btw :)

**Comment by ar2rsawseen** [comment]
Corrected in https://github.com/Countly/countly-server/commit/8b7b9996c1045bd6d6dfc3ac3838a9142f569cb9
