### ISSUE TITLE
Last event shows up little in events list

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#270]
The very last event is shown mostly off-screen.

![ekran resmi 2016-07-05 13 04 01](https://cloud.githubusercontent.com/assets/1757036/16581207/f62a6d5a-42b0-11e6-9ab1-9f98fdde5560.png)

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/commit/fcedaf007a00ebe1e699a9d07bc503e062bbb956
