### ISSUE TITLE
Question: Is this usable in a swift only application?

### ISSUE THREAD

**Issue by The-Wolf312** [Countly/countly-server#271]
Can this be used in a swift application, if so what are the limitations?
Can the Objective-C used to import this be substituted for equivalent swift or does it need to be explicitly Objective-C?
Third question how would I go about importing this to an OS X app?

**Comment by gorkem-cetin** [comment]
@The-Wolf312 Please send your support related questions to http://support.count.ly. 

Closing this issue for now :)
