### ISSUE TITLE
Digital Ocean Installer is broken

### ISSUE THREAD

**Issue by davidmann4** [Countly/countly-server#272]
![image](https://cloud.githubusercontent.com/assets/1736570/16707746/d56b1066-45d9-11e6-9435-16ac2903474b.png)

tried NYC3 and AMS3 region

**Comment by gorkem-cetin** [comment]
Can you try again? this should be fixed. If not, can you send the output?

**Comment by davidmann4** [comment]
i can try - what was the link again?

**Comment by gorkem-cetin** [comment]
http://do.count.ly

**Comment by davidmann4** [comment]
![image](https://cloud.githubusercontent.com/assets/1736570/17228071/c23fda84-5511-11e6-9da6-346bab004f21.png)

**Comment by davidmann4** [comment]
![image](https://cloud.githubusercontent.com/assets/1736570/17228197/4b22e13e-5512-11e6-9999-91437937b057.png)

**Comment by gorkem-cetin** [comment]
Thanks David for this, will check and get back to you :)

**Comment by davidmann4** [comment]
works for you? strange that it fails for me on a normal NYC droplet ?

**Comment by gorkem-cetin** [comment]
works for me, but since it doesnt work for you, chances are there is definitely an issue. will check.
