### ISSUE TITLE
Install  Countly Server Error  On CentOS 

### ISSUE THREAD

**Issue by vitanie** [Countly/countly-server#274]
sudo su - 
cd COUNTLY_INSTALLATION_DIRECTORY/bin
bash countly.install.sh

----------------------------

[root@localhost bin]# bash countly.install.sh

   ______                  __  __
  / ____/___  __  ______  / /_/ /_  __
 / /   / __ \/ / / / __ \/ __/ / / / /
/ /___/ /_/ / /_/ / / / / /_/ / /_/ /
\____/\____/\__,_/_/ /_/\__/_/\__, /
              http://count.ly/____/

countly.install.sh: line 22: apt-get: command not found

**Comment by gorkem-cetin** [comment]
Please run countly.install_rhel.sh instead.

You can send your questions to http://support.count.ly
