### ISSUE TITLE
user agent parser upgrade need

### ISSUE THREAD

**Issue by jianglinchun** [Countly/countly-server#275]
pls use this: https://github.com/3rd-Eden/useragent

**Comment by jianglinchun** [comment]
Please use this sample code:
`var plugin = {},
	common = require('../../../api/utils/common.js'),
	countlyCommon = require('../../../api/lib/countly.common.js'),
	cache = require('memory-cache'),
	request = require('request'),
	useragent = require('useragent'),
	mysql = require('mysql'),
    plugins = require('../../pluginManager.js');

(function (plugin) {
	
	// 从http header中获取设备型号
	// 参考： https://github.com/3rd-Eden/useragent
	plugins.register("/session/metrics", function(ob){
		var agent = useragent.parse(ob.params.req.headers['user-agent']);
		ob.userProps[common.dbUserMap['device']] = agent.device.toString();
	});
`

**Comment by ar2rsawseen** [comment]
Hello,
thank you for suggestion, added it here:
https://github.com/Countly/countly-server/commit/693fb15e489c2853df7037c4863d926a0badcc84

if all works well, we may remove parsing UA on web sdk side completely thus making it much smaller :)

**Comment by jianglinchun** [comment]
Thank you. :+1:
