### ISSUE TITLE
[SEO]search engine analytics plan? 

### ISSUE THREAD

**Issue by jianglinchun** [Countly/countly-server#276]
search engine analytics function is very important for SEO metric.
Is it enough in "source" plugins???

**Comment by gorkem-cetin** [comment]
Can you please elaborate what you mean by "search engine analytics function"? Any example(s) would be great.

**Comment by jianglinchun** [comment]
Please refer to this chart example:
http://echarts.baidu.com/echarts2/doc/example/pie.html

直达 = direct
'营销广告 = cps/dsp ad, such as index.php?source=ad_site&ozs=sub_org
搜索引擎 = search engine.

All of those means we can dig further more on sources of the visits. How may came from search engine? How many came from driect access & how many came form our advertisement.

This is critical for SEO. The more visits came from search engine or even we can track which keyword was search and clicked to our website.

And SEOer need analytic platform to perform those analytic result.

**Comment by gorkem-cetin** [comment]
For this you can have a look at "Traffic Sources" under Analytics. Here is a screenshot. Note that it has some dummy data.

![sources](https://cloud.githubusercontent.com/assets/1757036/17393735/32888ee6-5a2e-11e6-8387-10fb45ff52b9.png)

For advertisements / campaigns I would suggest using Attribution Analytics plugin (available with Enterprise Edition).

**Comment by jianglinchun** [comment]
Thank you @gorkem-cetin  I'll check it out.
