### ISSUE TITLE
uncaughtException Unexpected token

### ISSUE THREAD

**Issue by efabulousf** [Countly/countly-server#277]
Hi, 
I don't know if here is the right place to ask but,
My Countly was working for a while and now I see 502 Bad Gateway Error on Countly Dashboard 
I had a little search through nginx and Countly Forums. This led me to Counly Log file and the Error Subjected. 
Please guide me through...

/home/mobile-log/countly-server-master/frontend/express/app.js:58 
process.on('uncaughtException', (err) => { 
                                       ^ 
SyntaxError: Unexpected token > 
    at Module._compile (module.js:439:25) 
    at Object.Module._extensions..js (module.js:474:10) 
    at Module.load (module.js:356:32) 
    at Function.Module._load (module.jls -loads:312:12) 
    at Function.Module.runMain (module.js:497:10) 
    at startup (node.js:119:16) 
    at node.js:935:3

**Comment by ar2rsawseen** [comment]
Hello, your nodejs version is too old. You need to upgrade to at least Nodejs 5.5

You should be able to do that by running upgrade script:
https://github.com/Countly/countly-server/blob/master/bin/upgrade/16.06/upgrade.sh

**Comment by ar2rsawseen** [comment]
Closing for now, if issue not fixed, please reopen
