### ISSUE TITLE
Unable to create Application type Web with latest /image

### ISSUE THREAD

**Issue by ccampbellsoln** [Countly/countly-server#278]
We are using Docker to run a Countly container. We pulled the latest countly/countly-server image and spun up an instance. Created an account then tried to create an App with Application Type of web. After saving it sends the correct application type in the Post request but the response contains mobile. Same behavior is seen when trying to update the App.

**Comment by ar2rsawseen** [comment]
By image you mean docker?

**Comment by ccampbellsoln** [comment]
Yes, sorry the details were a bit fuzzy. I tried some revisions between now and the 16.06 tag. They all seemed to have the same issue. Using the the 16.06 version is working correctly.

**Comment by wolfogre** [comment]
I meet the same problem with 16.06 too, whatever I choose web or mobile, the type is always mobile. I have to log in mongodb and change the data by hands.

**Comment by ar2rsawseen** [comment]
@wolfogre are you sure you are using stable release and not code directly from the repo?

**Comment by wolfogre** [comment]
@ar2rsawseen Sorry about that, you are right,  I was using the code directly from the repo, I reinstalled the  stable release, it works normally now, thank you ~
