### ISSUE TITLE
Some of analytics display blank page & broken menu UI when no data was received even if I refresh web browser

### ISSUE THREAD

**Issue by jianglinchun** [Countly/countly-server#280]
If no data was received by some period. Such as today. Some of those analytics are broken.
/analytics/countries
/analytics/versions
/analytics/platforms

If I click refresh button of web browser. The menu text was gone.
Please check.

You could dump yesterday's data & view today's data and you'l find out.

**Comment by gorkem-cetin** [comment]
- Can you send a video showing this behaviour? 
- What do you mean broken and what do you mean by "menu text"? 

A little more information can help us duplicate this.

**Comment by jianglinchun** [comment]
I'll show you the code to avoid those problem:
api\parts\data\fetch.js line 650. metricChangesDbResult may be undified.
`if(!metricChangesDbResult){
							callback(appUsersDbResult);
							return;
						}`

api\parts\data\fetch.js line 690. obj could be undified:
`if(!obj){
			return tmpObj;
		}`

**Comment by ar2rsawseen** [comment]
Have you been able to determine why they are undefined? Cause by definition they should not be.

metricChangesDbResult should always be at least empty array, unless there is some deeper problem with mongodb integration, like unsupported mongodb version or driver.

**Comment by ar2rsawseen** [comment]
Added checks here but it would be great to understand what you have differently, why those objects are undefined:

https://github.com/Countly/countly-server/commit/900bc252ed2737d491f25f03e039dda02d6a5cbc
