### ISSUE TITLE
[Improvement] web-type analytics should have devices analysis

### ISSUE THREAD

**Issue by jianglinchun** [Countly/countly-server#282]
Device identify could be done by parse useragent of the web browser. And html5 is a important part for a platform, Not only iOS & android.

Please add devices analysis to web-type analytics subment. It's very important.

**Comment by gorkem-cetin** [comment]
Do you mean platforms? (/dashboard#/analytics/platforms) ?

**Comment by ar2rsawseen** [comment]
Device metric was already added to be populated by user agent:
https://github.com/Countly/countly-server/blob/master/plugins/web/api/api.js#L27-L28

but it is in current dev code, you can try to sync with master to check that functionality, but not recommended for production yet, until release.

If you mean some other feature, please reopen ticket with more information
