### ISSUE TITLE
When install mongodb 3.2 on Ubuntu 16.04,there is a problem in countly.install_ubuntu.sh

### ISSUE THREAD

**Issue by yahuvi** [Countly/countly-server#284]
When install mongodb 3.2 on Ubuntu 16.04,there is a problem in countly.install_ubuntu.sh,as shown below:

W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D68FA50FEA312927
W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: There is no public key available for the following key IDs:
D68FA50FEA312927  
E: Failed to fetch store:/var/lib/apt/lists/partial/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.2_multiverse_binary-i386_Packages  Empty files can't be valid archives
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Unable to parse package file /var/lib/apt/lists/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.2_multiverse_binary-amd64_Packages (1)
W: You may want to run apt-get update to correct these problems
E: The package cache file is corrupted

see also:https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-ubuntu/

**Comment by ar2rsawseen** [comment]
Hello,
never had a problem before and rechecked now, still building, correctly, maybe there was a server problem at the time of your attempt?

If problem persists please try changing these values:
https://github.com/Countly/countly-server/commit/8a7e9a81592355e65704a325439f72b1c88fb749

in your countly/bin/countly.install.sh script

if issue still persists, please reopen the ticket

**Comment by yahuvi** [comment]
at 38 line and 39 line in the countly.install_ubuntu.sh on Ubuntu 16.04 

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

replace with:

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

then runing command line 
 rm -r /var/lib/apt/lists/*
 apt-get update

May be the cause of the cache of apt

**Comment by ar2rsawseen** [comment]
yes, that is exactly what the commit I pointed you too does, but on the dev branch :)
