### ISSUE TITLE
about mongodb and nodejs

### ISSUE THREAD

**Issue by TonyWang8904** [Countly/countly-server#288]
Hello, I do not know much about Linux  and I want to use countly, so I install ubuntu 14.04 and want to install countly, but one question is should I install mongodb and nodejs before countly. If the answer is yes , where should I install these two? If  countly-server has mongodb and nodejs in it ,where are these two software?

**Comment by osoner** [comment]
Hello Tony,

When you run Countly installation script as sudo bash countly/bin/countly.install.sh this script takes care of installing all necessary software including MongoDB and Node.js.

**Comment by TonyWang8904** [comment]
ok, thanks. I have installed successfully!
