### ISSUE TITLE
ERROR [jobs:manager]  Error while looking for jobs: {"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"}

### ISSUE THREAD

**Issue by thatsk** [Countly/countly-server#290]
Hi Countly team,
Please change IP of mongodb  from **127.0.0.1** to 0.0.0.0 from **countly/bin/scripts/configure_mongodb.js** 

Because when we deploy docker container of countly it does not connect to mongodb database. also it  very tedious to change because if we can not change that docker container never runs.
It impacts of cloud where large number of deployments are occupying

**Comment by ar2rsawseen** [comment]
Hello,
We definitely cannot bind to 0.0.0.0 because it will listen to all interfaces and would allow anyone from the outside to connect to mongodb, which would be a huge security risk.

Maybe you can elaborate more on your usage, so we could find solution that would fit you too

**Comment by thatsk** [comment]
So whats the solution for running docker container on our physical interface which is binded to public ip

**Comment by thatsk** [comment]
because if want to connect to monogdb database through remotely we have to open port of monogdb & it is binded to 127.0.0.1

**Comment by thatsk** [comment]
Even we are not able to run countly docker container
(https://cloud.githubusercontent.com/assets/15324013/22931895/5ce414ce-f2ec-11e6-8020-c3fa810848e9.png)

**Comment by thatsk** [comment]
So give me the suggestion how to run docker container if we are not starting docker container because of mongodb error

**Comment by thatsk** [comment]
Even As per your docker instruction  i have restarted the docker conatiner but same result occured

**Comment by thatsk** [comment]
Please suggest me to Run docker container in production also

**Comment by iartem** [comment]
Our docker container is meant to be used as fire and forget to try before serious deployment, so it's bundled with mongodb and nginx. So I'm afraid to be used in real environment, you'll need to modify Dockerfile according to your needs and build your own image. For example, for sure you don't want mongodb to live in the same container with countly. Some systems like k8s provide native loadbalancers so often you don't need nginx, etc.

As for screenshot you've attached, what exactly steps you performed to run that container? Modified any configuration files, changed sources? How do you run the container second time?

**Comment by thatsk** [comment]
1) To start container
docker run -d -p 81:80 -p 82:27017 -v /var/data/mongodb:/var/lib/mongodb countly/countly-server
2)For restarting container 
docker restart [containerID]
When i check the logs i get error as above screenshot
And countly server is not starting....

**Comment by iartem** [comment]
I just tried to run 1). With or without 2) Countly runs just fine. Apparently you messed up configuration of Countly or mongo or both.

**Comment by thatsk** [comment]
Can you provide me which docker version you are using on which platform 
And what are steps you are follow

**Comment by xxxifan** [comment]
I run like the documentation says, ```docker pull countly/countly-server```, and ```docker run -d -P -v /var/data/mongodb:/var/lib/mongodb countly/countly-server```
and docker logs see the same result.I can access web frontend and show this page
![2017-04-01 19-17-19](https://cloud.githubusercontent.com/assets/1215833/24578278/f6dd021e-16a2-11e7-9485-47e61c2338d7.png)

**Comment by peterwilli** [comment]
When building the Docker container myself, I get similar error during build:

```
Installing plugin "server-stats"...
Installing plugin "dbviewer"...
Processing plugin files for production mode
Preparing production files
{ MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/opt/countly/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/opt/countly/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/opt/countly/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect' }

```

**Comment by iartem** [comment]
Mongo must have being allocating files at that moment. See this comment http://resources.count.ly/docs/installing-countly-server#section-method-4-installation-via-docker

**Comment by peterwilli** [comment]
@iartem that is certainly not the case. It should but it doesnt. I ran it for a day on a dedicated server with SSD and it didn't allocate a single file. I think that it has something to do with the way the Counlty install script is ran during docker-build. I started investigating this issue myself as well, but I don't have enough time right now to continue.

**Comment by iartem** [comment]
Ok, then feel free to reopen this if needed.

**Comment by peterwilli** [comment]
@iartem I think this needs to be reopened, I've never done that.
This is a link of the latest build in Docker: https://hub.docker.com/r/countly/countly-server/builds/bbzmjywy5thqbxvbjqttcck/

Search in the logs for 'MongoError: failed to connect' (without quotes). You can see that there are errors during build. This is, with a high chance the cause of the error.

**Comment by peterwilli** [comment]
@iartem I fixed the bug! I believe some data paths have been mixed up.
Check this out:
If I run the original image without modifications like this: docker run -d -p 127.0.0.1:8085:80 -v /var/docker_data/countly_db:/data/db --restart=always --name countly countly/countly-server

See that the volume is now linked to **/data/db** instead of **/var/lib/mongodb**, then it works.
So what we need to do is change the Dockerfile and the commands in tutorials or docs where /var/lib/mongodb is used to /data/db.
