### ISSUE TITLE
Securing mongodb error

### ISSUE THREAD

**Issue by thatsk** [Countly/countly-server#292]
I'm just securing mongodb with the help of Security Guide 
as per url
http://resources.count.ly/docs/securing-mongodb#section-adding-authentication-for-your-mongodb-database
We have tried with command for adding user it give me error.
I'm attaching scrreenshot of it please look into this.
> db.createUser({user:"test", pwd:"test123",roles[{role:"readWrite", db:"countly"}]})
2017-02-16T13:07:23.027+0000 E QUERY    [thread1] SyntaxError: missing : after property id @(shell):1:47
![error1](https://cloud.githubusercontent.com/assets/15324013/23022948/6fb42b28-f479-11e6-8f2d-f2218a664eef.png)

**Comment by osoner** [comment]
Hi Kunalsing,

I emailed you already but just in case others can benefit, there was a missing ":" in that statement and correct one would be like below. This is also fixed in the [related document](http://resources.count.ly/docs/securing-mongodb).

    db.createUser({user:"test", pwd:"test123",roles: [{role:"readWrite", db:"countly"}]
