### ISSUE TITLE
Nginx 502 BadGateaway log报错connect faild

### ISSUE THREAD

**Issue by wcyyo** [Countly/countly-server#293]
failed (111: Connection refused) while connecting to upstream, client: 172.17.159.60, server: localhost, request: "GET /o/langmap HTTP/1.1", upstream: "http://127.0.0.1:3001/o/langmap", host: "10.223.94.34", referrer: "http://10.223.94.34/dashboard"
2017/02/28 15:28:46 [error] 4851#4851: *27 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.159.60, server: localhost, request: "GET /o/sources HTTP/1.1", upstream: "http://127.0.0.1:3001/o/sources", host: "10.223.94.34", referrer: "http://10.223.94.34/dashboard"
connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.159.60, server: localhost, request: "GET /o/sources HTTP/1.1", upstream: "http://127.0.0.1:3001/o/sources", host: "10.223.94.34", referrer: "http://10.223.94.34/dashboard

网页端打开，nginx日志报如下错误，求原因及解决办法

**Comment by ar2rsawseen** [comment]
I think this error mostly happens, when you are accessing countly url, but countly process is down, and thus nginx logs this error

**Comment by waiterZen** [comment]
3001是 数据api服务接口，现在目前 网页端能否正常展示数据？ 如果不能的话可以判断是这个服务挂了，然后在countly/log/文件夹下看看几个服务的日志有没有报错。

**Comment by wcyyo** [comment]
您好，首先感谢您的回复。
countly服务器刚刚在rh7.1服务器上搭建
图表未能正常显示。
countly-api.log下报如下错误
![image](https://cloud.githubusercontent.com/assets/16218736/23396791/75644dae-fdd0-11e6-8f16-5773fb5ae7e8.png)

@waiterZen

**Comment by gorkem-cetin** [comment]
Is this a Red Hat / CentOS ? What is the version?

**Comment by wcyyo** [comment]
RedHat7.1 @gorkem-cetin

**Comment by waiterZen** [comment]
这个是node.js和npm版本导致的node.js lib安装失败的问题。我们安装脚本主要考虑的是 ubuntu14+和 centos7+的平台，建议在这两个平台测试.

如果在redhat上，你可以尝试自行排查一下第三方node.js libs的安装问题，node.js 需要6.3以上的版本.更新完node之后在countly目录下执行"npm install"重新安装libs，看看安装libs过程中没有错误的话 。

**Comment by wcyyo** [comment]
thank u everyone!
我曾在centOS  node.5.12.0成功完成搭建，
在RedHat7.1下 node版本7.1.0，5.12.0版本都汇报module mismatch的错误。
之后升到6.4.0后问题解决。
 @waiterZen 感你的回答，

**Comment by waiterZen** [comment]
同样谢谢分享经验 :）
