### ISSUE TITLE
Change port except 80

### ISSUE THREAD

**Issue by wcyyo** [Countly/countly-server#294]
How can i change port to other port?

**Comment by ar2rsawseen** [comment]
Hello,
countly is actually running under other ports, but we are using nginx to forward traffic to specific processes, based on api endpoint.

So all you have to do is to change port in nginx config and restart nginx server. 
Nginx config looks like this: https://github.com/Countly/countly-server/blob/master/bin/config/nginx.server.conf

and it should be in /etc/nginx/sites-available/default

just changing these two lines should be enough:
https://github.com/Countly/countly-server/blob/master/bin/config/nginx.server.conf#L2-L3
