### ISSUE TITLE
Countly Installation On Multiple Nodes And One Large MongoDb Database

### ISSUE THREAD

**Issue by thatsk** [Countly/countly-server#296]
Can you provide me instruction to Create Countly Installation ON Multiple Nodes With one Big MongoDB database. I don't See any instruction in Documentation.

**Comment by osoner** [comment]
Please check [this link](http://resources.count.ly/docs/configuring-countly) for Countly MongoDB configuration. As per Countly itself you can install on as many nodes as you wish but you'll need a load balancer (such as AWS ELB) in front of those nodes to distribute the traffic.

**Comment by thatsk** [comment]
Let Me tell you we have ec2 machines we are installing using this command
wget -qO- http://c.ly/install | bash
So after that each has countly directory so how we can configure the two countly node to one elb

**Comment by thatsk** [comment]
which file to be modified on these two nodes

**Comment by thatsk** [comment]
is it proper way if we are creating 15GB RAM & 150GB SSD DIsk for mongodb

**Comment by osoner** [comment]
I won't be able to help you with specifics of ELB but [this link](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-getting-started.html) should be useful. For ELB you don't need to make any configuration on Countly apart from changing the config files mentioned in the link I sent in my previous message to point out to correct MongoDB instance.

I can't comment on whether those specs would be enough without understanding your use case and traffic.
