### ISSUE TITLE
Use mongoDB from other container.

### ISSUE THREAD

**Issue by jcgruenhage** [Countly/countly-server#297]
I am running a lot of stuff on my Server and already have an instance of mongoDB running. I would prefer not to run another instance in this container. In addition to that, this is somewhat against the docker philosophy of one thing per container. It would be really nice, if you could use the official mongoDB container together with this server.

**Comment by ar2rsawseen** [comment]
Hello,
from countly point of view there is no reason why you could not do that. If you can ensure that your mongodb can be accessed from countly container, then all you have to do is to configure countly config files (api/config.js and frontend/express/config.js) host to point to another container mongodb.

This is the same when users decide to run mongodb on separate server in real world applications. So it can be done quite easily.

But it is not something we want to do out of the box, cause what we want to provide is easy to setup system, which installs everything from one script and runs. And docker reuses this our primary system of the way we set up things.

And even if you use remote server, in most cases you still need mongotools to be installed locally on countly server too

**Comment by jcgruenhage** [comment]
Well, you could just do that by providing a sample docker-compose file, with that, you would have one command to start it and one to stop it, with the commands being a lot simpler than what the current docker run commands are. But if that is already possible, I'll look into that ^^
