### ISSUE TITLE
Support Mongo 3.5

### ISSUE THREAD

**Issue by KenanSulayman** [Countly/countly-server#300]
Hey,

I just rolled out (and then reverted) Mongo 3.5 and noticed that Countly (its UI, specifically; the analytics - i.e. inserting - does work as intended) fails to work with it. It appears the query API has changed, or deprecated APIs were used and phased out in 3.5.

-- Kenan

**Comment by ar2rsawseen** [comment]
Hello,
yes not tested with it yet and release in current preparation won't use it too, but will try to fit in next release.

**Comment by KenanSulayman** [comment]
Great, thanks! I intended to create this as a tracking-issue -- I was aware it wasn't fully supported, yet.

**Comment by gorkem-cetin** [comment]
Closing this issue, as in next release we'll support the most feasible Mongo version :)
