### ISSUE TITLE
Default Data for Docker instance

### ISSUE THREAD

**Issue by cihangir** [Countly/countly-server#303]
Hi Countly team,

Would you be open to have your Docker image shipped with default data? Such as default admin user and a default app. Which would be useful for initial bootstrap/development/testing purposes. 
You can see our usage [here](https://github.com/Countly/countly-server/compare/master...koding:master)
 
ps: you can ignore the "sso" plugin

Let me know if that sounds good and i can open a PR or you can close this issue.

**Comment by osoner** [comment]
Hi Cihangir,

Can you make it optionally add a default user and app? Like with an environment variable or parameter to the script.

**Comment by cihangir** [comment]
HI @osoner It is behind an [env var](https://github.com/Countly/countly-server/compare/master...koding:master#diff-159b6c0499802e7273757b340b177f23R16)

**Comment by osoner** [comment]
Ok sorry I didn't notice that one, looks good then. Feel free to open a PR.
