### ISSUE TITLE
Can I install countly-server on window OS?

### ISSUE THREAD

**Issue by Quinton** [Countly/countly-server#304]
Can I install countly-server on window OS?

**Comment by gkmngrgn** [comment]
@Quinton I didn't try but it seems possible if you use Ubuntu Bash on Windows[1]. You need to discover the requirements from Dockerfile and install them with `apt` command line package installer tool.

If I were you, I would like to explain why you want to install countly-server on Windows. What is the version of the OS, version 10 or 8? Is it a remote server? Do you think to use an Azure cloud service?

[1]: https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by Quinton** [comment]
@gkmngrgn  thx
