### ISSUE TITLE
Maybe a typo on /api/utils/authorizer.js

### ISSUE THREAD

**Issue by Siubaak** [Countly/countly-server#309]
I have read the codes these days, and it may be a typo in line 47 on /api/utils/authorizer.js.
I think it should be 'findOne' instead of 'findOn', shouldn't it?

**Comment by ar2rsawseen** [comment]
Yes it was a typo, thank you for reporting, fixed in:
https://github.com/Countly/countly-server/commit/db6ac4db7e160d1188593e0183735faa8ec62ed5
