### ISSUE TITLE
(maybe) a bug in job replacing

### ISSUE THREAD

**Issue by Siubaak** [Countly/countly-server#310]
when I started the api server, an error was thrown in replacing jobs. it said that require('...').create is not a function and the error occurred in /api/parts/jobs/job.js line 235. i found that it requires /api/parts/jobs/index.js which will return /api/parts/jobs/handle.js if running in child process, but there is no create method in './handle.js' and class Handle isn't extended from any other class. i don't know how to reappear the error and i forgot to copy down the log. could you please explain this?

**Comment by iartem** [comment]
Do you run some custom jobs or know which job it was?

**Comment by Siubaak** [comment]
I didn't add any custom jobs. Sorry that I didn't log it down and I don't know. I think it's rare because it just occurred once. If you guys don't know, I will close the issue. I will log it down and tell you if it occurs next time. Thanks a lot :)

**Comment by iartem** [comment]
So the thing is that replacing shouldn't occur in worker process, but only in master process. I think the only job that _might_ _possibly_ end up in this situation is push with timezone-based sending in some invalid state. Meaning we need to know that invalid state for a fix. 

So if it's about push, then please add logging to your server (type "push, jobs, job" without quotes into debug and clear info/warn/error, then save here: http://resources.count.ly/docs/logging#section-logging-configuration).

Ok, closing it for now then. Feel free to reopen at any time.

**Comment by Siubaak** [comment]
I meet it a again. Logs below.

> 2017-07-28T08:22:14.533Z: INFO  [jobs:job]      replacing job {"status":0,"name":"assistant:generate"} with { name: 'assistant:generate',
>   created: 1501230134519,
>   status: 0,
>   started: null,
>   finished: null,
>   duration: 0,
>   schedule: 'every 30 minutes starting on the 0 min',
>   next: 1501230600000,
>   modified: 1501230134532 }
> 2017-07-28T08:22:14.543Z: INFO  [jobs:job]      found 4 jobs with {"status":0,"name":"assistant:generate"}, going to cancel ["597ada6a82b4972465bd9
> 30b","597ae87b82b4972465bd930c","597ae87b82b4972465bd930d"]
> 2017-07-28T08:22:14.545Z: ERROR [jobs:job]      TypeError: require(...).create is not a function TypeError: require(...).create is not a function
>     at Promise.all.others.map.j (/home/qiuyankun/countly/api/parts/jobs/job.js:235:39)
>     at Array.map (native)
>     at db.collection.find.toArray.e (/home/qiuyankun/countly/api/parts/jobs/job.js:234:28)
>     at /home/qiuyankun/countly/plugins/pluginManager.js:771:25
>     at handleCallback (/home/qiuyankun/countly/node_modules/mongodb/lib/utils.js:120:56)
>     at /home/qiuyankun/countly/node_modules/mongodb/lib/cursor.js:860:16
>     at handleCallback (/home/qiuyankun/countly/node_modules/mongodb-core/lib/cursor.js:171:5)
>     at setCursorDeadAndNotified (/home/qiuyankun/countly/node_modules/mongodb-core/lib/cursor.js:505:3)
>     at nextFunction (/home/qiuyankun/countly/node_modules/mongodb-core/lib/cursor.js:651:7)
>     at Cursor.next [as _next] (/home/qiuyankun/countly/node_modules/mongodb-core/lib/cursor.js:692:3)
>     at fetchDocs (/home/qiuyankun/countly/node_modules/mongodb/lib/cursor.js:856:10)
>     at /home/qiuyankun/countly/node_modules/mongodb/lib/cursor.js:879:7
>     at handleCallback (/home/qiuyankun/countly/node_modules/mongodb-core/lib/cursor.js:171:5)
>     at nextFunction (/home/qiuyankun/countly/node_modules/mongodb-core/lib/cursor.js:682:5)
>     at /home/qiuyankun/countly/node_modules/mongodb-core/lib/cursor.js:593:7
>     at queryCallback (/home/qiuyankun/countly/node_modules/mongodb-core/lib/cursor.js:232:18)

**Comment by iartem** [comment]
Ok, thanks. Will look into this next week.

**Comment by iartem** [comment]
As far as I guess, should be resolved now. Feel free to reopen if 18.08 doesn't fix it.
