### ISSUE TITLE
Version mismatch after upgrade

### ISSUE THREAD

**Issue by bb-git** [Countly/countly-server#3102]
After upgrading from 20.11 to 21.11 and following the instructions and executing the script, I see the following message in the dashboard:

The script states:
```
Done.
Restarting Countly...
```

In the dashboard there is a message:
"There is a version mismatch between version in files and in database. It may indicate that upgrade scripts didn't complete properly."
<img width="334" alt="Bildschirmfoto 2022-04-26 um 17 01 20" src="https://user-images.githubusercontent.com/7348507/165275643-7107fbb3-80d8-47af-ab91-600540137d28.png">

### Your Environment

Ubuntu 20.04

Everything seems to be working so far. I also was able to crate a dashboard. How can I get rid of the message?

**Comment by jsarnowski96** [comment]
Same issue here. Not only the upgrade documentation is incomplete and ommits entire v21 release, but also breaks current countly installation and pollutes mongo server-related documents.

**Comment by jsarnowski96** [comment]
for future reference, @bb-git - simply update document via MongoDB Compass - countly > plugins > version.
![Przechwytywanie](https://user-images.githubusercontent.com/20375860/165484029-69d4c2fe-94d0-420f-9020-88d5dc9fb015.PNG)

**Comment by ar2rsawseen** [comment]
We had a bug with it previously which should be fixed now, but overall, we make version of files and version of database and this warning shows if they don't match, usually meaning you need to run some upgrade scripts
