### ISSUE TITLE
APN certificate validation not working

### ISSUE THREAD

**Issue by intrepidkarthi** [Countly/countly-server#319]
I have created a dev .p12 certificate with passwords. When I upload the credentials, the popup that says "validating credentials" runs infinitely. Password is correct. Did anyone else face the same?

**Comment by iartem** [comment]
Countly doesn't support dev certificates, which is stated in that upload form. Please follow this guide http://resources.count.ly/docs/countly-sdk-for-ios-and-os-x#section-setting-up-push-certificate

**Comment by iartem** [comment]
But let's keep it reopen to make it not run indefinitely :)

**Comment by intrepidkarthi** [comment]
Yes. That was my bad. Issue resolved. Thanks for the update.

**Comment by iartem** [comment]
Like I said, the fact that spinner runs indefinitely is a bug, so kipping this issue open for now
