### ISSUE TITLE
can't use google map in china

### ISSUE THREAD

**Issue by liangjie18430** [Countly/countly-server#321]
I got display incorrectly when i clicked Analytics-countries in 17.05.1. And the area of China displayed by google map really makes me uncomfortable. For the map reason, it might make my company choose other product.

**Comment by gorkem-cetin** [comment]
You can always disable google services from Management > Configurations .. Attaching a screenshot.

<img width="1038" alt="maps" src="https://user-images.githubusercontent.com/1757036/28615147-c21f61ac-7200-11e7-9088-8285ac843084.png">

**Comment by liangjie18430** [comment]
Anyway，thanks！
