### ISSUE TITLE
How can I change the password of the user via cli?

### ISSUE THREAD

**Issue by ashutoshvct** [Countly/countly-server#324]
I have tried to insert sha1 hash in mongodb members collection. I have to change the password via CLI. Please suggest a way to achieve it. Also, you must create commands to change the user password in countly shell.

**Comment by ar2rsawseen** [comment]
Hello,
you can't change password via CLI. Changing password require user's permission, and we must log who changed the password, etc, so there must be some trace like API KEY or something to identify who did the change.

Closest I can suggest is adding new global admin user via CLI

countly add_user "username" "password"

where "username" should be your desired username and "password" would be password for that user name.

Then either getting into dashboard and changing other's user's password under Management -> Users
or getting this newly created user's API KEY and making API request via CLI

and afterwards delete created user
countly remove_user "username" "password"

**Comment by gorkem-cetin** [comment]
Closing this issue for now @ashutoshvct - please send your questions to http://community.count.ly instead. Many thanks!

**Comment by ashutoshvct** [comment]
For security reasons, I have to automate password for every user every day.

**Comment by ar2rsawseen** [comment]
Then API is your friend, you can get Global Admin API key and use it to do all manipulations you need, even from command line.

http://resources.count.ly/v1.0/reference#iusersupdate
