### ISSUE TITLE
[v22.06] User Management broken

### ISSUE THREAD

**Issue by majamee** [Countly/countly-server#3310]
### Expected Behavior
Open "User Management" while being logged in enables you to manage your users.

### Current Behavior
On countly-server v22.06 the "User Management" section is not loading except the headline.
A bunch of error messages appear in the console. Tested with a fresh lxd container using Ubuntu 20.04 LTS.

### Screenshots: 
![Screenshot from 2022-07-01 18-45-07](https://user-images.githubusercontent.com/20463582/176936601-f312b5dd-5a58-4e8e-b5f2-62416b871b2c.png)

### Possible Solution

Before upgrading to the latest version the "User Management" was working fine.
Clean install behaves the same.

### Steps to Reproduce (for bugs)
1. Install or update to countly-server v22.06
2. Create an admin user and login
3. Try to load "User Management" by selecting it from the left hand menu

### Your Environment

* Operating System and version: Ubuntu 20.04 (inside a lxd container: https://linuxcontainers.org/lxd/getting-started-cli/#launch-a-container)
* Any changes you have made to your instance: fresh install + countly install script

**Comment by widatama** [comment]
@ar2rsawseen This one should be fixed in this pr https://github.com/Countly/countly-server/pull/3273

Would there be a patch release for this? Or should we just wait for the next release?

**Comment by majamee** [comment]
Imho: if the next release is still months or weeks away a fix/ patch would be highly appreciated.

**Comment by ar2rsawseen** [comment]
Hello, then it should be released in 22.06.2 tag already :)

**Comment by majamee** [comment]
@ar2rsawseen Thank you very much for the information, but can you please be a little bit more concrete on what to do, if my goal is to run the latest stable release. I was looking at the documentation here, which mentions 4 installation methods:
https://support.count.ly/hc/en-us/articles/360036862332-Installing-the-Countly-Server

Right now, I do not want to go the route to use the Docker way, this leaves the one-line-installation and the installation package from github (latest stable) and digital ocean is not used right now. Nevertheless, the one-line-installation as well as the route to go with the latest stable release from github are both still broken. Any suggestions how to overcome this would be highly appreciated.

**Comment by MuddleHeaded** [comment]
我也安装这个最新版本出现这个问题，请问有什么解决方案么

**Comment by MuddleHeaded** [comment]
also installed the latest version of this problem. Is there any solution

**Comment by ar2rsawseen** [comment]
Hello,
just getting latest from master would get the latest part
Currently for minor releases we only tag code and not create packages for CE
but maybe something we can improve in our pipelines later

**Comment by ZeroJsus** [comment]
> #3273

change file with this PR. I solve my problem.

**Comment by ar2rsawseen** [comment]
Should be fixed now
