### ISSUE TITLE
start: Job failed to start

### ISSUE THREAD

**Issue by liansghuaifan** [Countly/countly-server#336]
i use countly-server-17.05.1 version，I follow the tutorial installation like “”countly.install_rhel.sh“”，my linux is cetos6 ，The installation is complete and successful，but i start countly like“”countly start“”,i get
an  error "start: Job failed to start" ,I didn't find any logs in “”countly-server-17.05.1/log“”. can you help me?

**Comment by ar2rsawseen** [comment]
Hello,
Can you check this log file: /var/log/upstart/countly-supervisor.log

**Comment by liansghuaifan** [comment]
hello
i do not find "/var/log/upstart/countly-supervisor.log"  ,i use commond    " find / -name countly-supervisor.log" ,The result is still not found，then i try “start countly-supervisor" result still is
"start: Job failed to start“”

**Comment by ar2rsawseen** [comment]
Ok, then recheck /etc/init/countly-supervisor.conf file to make sure that it points to correct supervisord.conf and that it exists and provided location.

**Comment by liansghuaifan** [comment]
i find the supervisord.conf ， /root/countly-server-17.05.1/bin/config/supervisord.conf，i check this file ，find this “[supervisord] logfile=/var/log/supervisord.log”，The result is still not found supervisord.log .Forget it ，i try install countly in another node,if you like, Help me with this puzzle

**Comment by ar2rsawseen** [comment]
do you start countly with root permission?

**Comment by liansghuaifan** [comment]
sudo countly start
start: Job failed to start
i try install countly in another node，it run good，thank you very much

**Comment by gorkem-cetin** [comment]
For our information,what did you do differently so it worked? Thanks!

**Comment by liansghuaifan** [comment]
I reinstall it on another machine，I think there's something wrong with my previous machine environment，My previous machines have already installed nginx, mongdb and so on。In general, it should be machine  environmental issues

**Comment by gorkem-cetin** [comment]
Thanks for this information. We will try to make to sure to check this during installation as Countly installer deploys nginx, mongodb etc using its own scripts.
