### ISSUE TITLE
how to insert data into "https://asia-try.count.ly"

### ISSUE THREAD

**Issue by yaoboxu** [Countly/countly-server#338]
i user the python to insert data. 
like this:

if __name__ == '__main__':
    url_head = "https://asia-try.count.ly/i"
    url_content = "?app_key=xxxxx&device_id=xxxxxx&" \
                  "begin_session=1&session_duration=3&" \
                  "events=[{\"key\":\"activity_lujing_xx\",\"count\":1,\"sum\":1," \
                  "\"segmentation\":{\"activity_id\":\"10001\"}]&end_session=1"
    response = requests.request("GET", url_head+url_content)
    print(response.text)

the response.text result is success, but the data cannot see on the page of https://asia-try.count.ly

**Comment by gorkem-cetin** [comment]
Removed app key and device ID from your issue.

**Comment by yaoboxu** [comment]
in the server "https://asia-try.count.ly/i", we cannot see the eventlogs,so  cannot find any useful thing to locate questions

**Comment by gorkem-cetin** [comment]
Can you explain "we cannot see event logs" ? Did you try Management > Event Logs?

**Comment by yaoboxu** [comment]
YES, "Management > Event Logs  " this page is blank.

**Comment by yaoboxu** [comment]
can i ask another questions?

many indexes use "users"  but the data "userdetail" only conclude user name, not id,  what  property do you use to measure UV??

**Comment by gorkem-cetin** [comment]
Since you are writing a SDK in python, you are suggested to read this documentation. Its main purpose is to guide those how SDKs work in general:

https://resources.count.ly/docs/sdk-development-guide

**Comment by ar2rsawseen** [comment]
@yaoboxu what is the name of the app on that server, I will try to check it

**Comment by gorkem-cetin** [comment]
Closing for now, reopen when you have more data for this issue.
