### ISSUE TITLE
Which field is based on the amount of user statistics?

### ISSUE THREAD

**Issue by yaoboxu** [Countly/countly-server#339]
user_details={
    "name": "Arturs Sosins",
    "username": "ar2rsawseen",
    "email": "test@test.com",
    "organization": "Countly",
    "phone": "+37112345678",
    //Web URL to picture
    "picture": "https://pbs.twimg.com/profile_images/1442562237/012_n_400x400.jpg", 
    "gender": "M",
  	"byear": 1987, //birth year
  	"custom":{
      "key1":"value1",
      "key2":"value2",
      ...
    }
  }

**user_details** has no filed about userid, Which field is based on the amount of user statistics?
when i see the database, the table countly.app_users{appID}  has the _id denote user_id but not support upload data by restfulApi?????

can you tell me the filed _id in table countly.app_users{appID} how is generated

**Comment by ar2rsawseen** [comment]
Hello,
I'm sorry I did not really understand what do you mean by amount of user statistics.
_id field is generated like this:
https://github.com/Countly/countly-server/blob/master/api/api.js#L918

And user_details requires enterprise plugin user profiles to store that data

**Comment by yaoboxu** [comment]
#8

**Comment by gorkem-cetin** [comment]
@yaoboxu please send your questions to http://community.count.ly and only bugs/issues here please. Thank you for your understanding.
