### ISSUE TITLE
In Analytics->Views page, the dashbord show nothing, but many data in table list

### ISSUE THREAD

**Issue by yaoboxu** [Countly/countly-server#341]
![question](https://user-images.githubusercontent.com/32385205/32084467-d9789f14-bafb-11e7-96b5-5fb0c01a9387.png)

just like the picture show

**Comment by ar2rsawseen** [comment]
Hello, as I see, above the graph, you selected last tab, which I think was "bounces".
What happens when you select the first table for visits or second for users?

**Comment by yaoboxu** [comment]
![22](https://user-images.githubusercontent.com/32385205/32150427-9554edac-bd4d-11e7-8f40-4c05b22872a2.png)




which table i selected , the graph has no data.

**Comment by gorkem-cetin** [comment]
Are you using any other non-standard way of sending data? Are you using your own server (CE or EE) or trying out on one of our servers?

**Comment by gorkem-cetin** [comment]
Found this issue @yaoboxu  - will fix it in next release by next month.

**Comment by ar2rsawseen** [comment]
Hello,
so problem seems to be with view names containing special symbols, like dot.

Here is the fix:
https://github.com/Countly/countly-server/commit/104f518934cfb6bce28206306b1efef8f67a4e6c
