### ISSUE TITLE
Can I send timeonsite.js tracking paramerts to countly-server for combined reporting?

### ISSUE THREAD

**Issue by saleemkce** [Countly/countly-server#3424]
Hi all,

I'm using community edition for some of our websites for product analytics and tracking. It's easy to use and reporting is great.
Some of my customers are also using the most popular [**_timeonsite.js_**](https://saleemkce.github.io/timeonsite) library for tracking time-on-page data in real-time mode using Beacon APIs. Each pageview sends back following paylod/ping to API server:

```
{
	TOSId: 4771670523197352
	TOSSessionKey: "2185166028719732632552"
	TOSUserId: "anonymous"
	URL: "https://nature-blog-local.github.io/timeonsite/"
	currentTime: "2022-08-12 07:23:03.932"
	entryTime: "2022-08-12 07:22:58.148"
	timeOnPage: 6
	timeOnPageByDuration: "0d 00h 00m 06s"
	timeOnPageTrackedBy: "second"
	timeOnSite: 6
	timeOnSiteByDuration: "0d 00h 00m 06s"
	title: "Timeonsite Tracker | Real-time demo"
	trackingType: "tos"
}
```

Is there any custom API in **_countly-server_** to accept this payload as-is and show this data in reporting? the scope is to show custom analytics data in reporting view either combined or separately? Thanks in advance.

**Comment by ar2rsawseen** [comment]
Hello
this cannot be accepted directly as is, but data can be either attached to a user or to the event (user action).
If you already track websites, you probably use Countly web SDK, so you can check, how to pass user properties or create custom events
https://github.com/Countly/countly-sdk-web
