### ISSUE TITLE
how could i understand structure of countly.logs?

### ISSUE THREAD

**Issue by MrRRcc** [Countly/countly-server#343]
I have read countly database schema contents,but i can't understand what's the difference of 'ts' and 'reqts',what's more ,the period between 'ts' and 'reqts' is more than one day.How could I understand?
Thank you!!!

**Comment by ar2rsawseen** [comment]
Hello,
I assume you are talking about logger plugin, cause I think that is the only place where such wording as "reqts" exists. Correct me if I am wrong.

In that case, we can think of it like this:
* ts is when event or action happened on device and request was queued on device
* reqts is when request was received on server

So for example, if device was offline, request would be stored on device until SDK can connect to server. So if after one day device went online and SDK was able to send the request to server, that could totally explain why you have more than one day between them.

**Comment by MrRRcc** [comment]
Thanks a lot!!! And Sorry for replying you so late~
I'am try to understand countly  logger plugin every details.
Thank you for the good product you made~
