### ISSUE TITLE
The logger plugin structrue dictionary I need~

### ISSUE THREAD

**Issue by MrRRcc** [Countly/countly-server#346]
Now I'm using countly 17.09 Community Enterprise,I want to analyse user action,so I set a program to make logger plugin txt.But I don't totally understand the specified meaning of each key.I have looked up in https://resources.count.ly/docs/countlylogsappid ,and the contents are not enough.Could you please provide documents of logger plugin.
Thanks thanks thanks~

**Comment by ar2rsawseen** [comment]
Hello,
yes scheme changed for logger recently, I have updated docs about it. Let me know if you still have any questions.

https://resources.count.ly/docs/countlylogsappid

**Comment by MrRRcc** [comment]
Woow!
Thank you for making document more specified~
Sorry to troubling for some questions of logger plugin below:
1. One action creates one log and One log contains one action?
2.If I need to make statistics of session duration(though you have made it online which is much useful for us ,I need more dimensions),is it right that I calculate session_duration values whose's logs.t.session.end_session equals 1.
3.When I look up those data,I found some records whose's logs.t..events.key equals '[CLY]_view' or '[CLY]_action',what '[CLY]_view' and '[CLY]_action' mean?I also saw the record almost same with '[CLY]_view'.
Waiting for your reply gratefully~

**Comment by MrRRcc** [comment]
...and what's meaning of timestamp,hour,dow in logs.t.event?

**Comment by ar2rsawseen** [comment]
> One action creates one log and One log contains one action?
It was like this before, but not one log per request and request can contain multiple actions, like begin_session=1&events=[...]&crash={...} etc

> .If I need to make statistics of session duration(though you have made it online which is much useful for us ,I need more dimensions),is it right that I calculate session_duration values whose's logs.t.session.end_session equals 1.

All session_duration values should be taken into calculation. The ones that are with end_session, meaning it was last hearbeat/update from that session, but basically session duration should be called by device periodically, like every 60 seconds by default (could be different for some platforms or SDKs)

More information can be found in SDK developer guide:
https://resources.count.ly/docs/sdk-development-guide#section-session-flow

> When I look up those data,I found some records whose's logs.t..events.key equals '[CLY]_view' or '[CLY]_action',what '[CLY]_view' and '[CLY]_action' mean?I also saw the record almost same with '[CLY]_view'.

Those are internal countly events, usually for some specific plugins, like [CLY]_view is for view analytics and [CLY]_action is for heatmap actions

> ...and what's meaning of timestamp,hour,dow in logs.t.event?
Hour and day of the week on device, when event happened. We usually send timestamp wit request, but it gives us absolute time. But in different parts of the world, there is different time, so for example if you want to find out users who use your app 5am in the morning, you could do that with hour parameter we attach to every request or event. Similarly with dow - day of the week

**Comment by MrRRcc** [comment]
Woow!
It's 2017/11/2 16:57 in Peking , I think you just get to work ,HAHAHAHA~
Thanks for your replay!
Best Regards!
