### ISSUE TITLE
Creating new user not in a transaction

### ISSUE THREAD

**Issue by nighon** [Countly/countly-server#350]
If one device report twice very quickly, Countly will count "u" as 2 in users collection.

I think it is because the second session of report query for new user too quickly before the first session complete creating new user.

**Comment by ar2rsawseen** [comment]
Hello,
unfortunately mongodb database underneath is transaction less. 
We have duplicate request prevention, but if data is not stored yet, then it could happen as you say.

Do you encounter it with specific SDK? Because SDKs should be designed to prevent such behavior.

**Comment by gorkem-cetin** [comment]
Closing this issue - if you have more information @nighon - let us know.
