### ISSUE TITLE
Update devices list

### ISSUE THREAD

**Issue by wcyyo** [Countly/countly-server#352]
There is no iPhone8 and iPhoneX data. Could you updatecountly.device.list.js data?

**Comment by ar2rsawseen** [comment]
Hello,
we have updated list of devices,
you can retrieve it here:
https://github.com/Countly/countly-server/blob/next/frontend/express/public/javascripts/countly/countly.device.list.js

or run `countly update devices` on your countly server

**Comment by wcyyo** [comment]
Thanks, there are lots of Android device need update. Is there some method for me to update it by myself?

**Comment by ar2rsawseen** [comment]
I actually updated them too in that previous commit, but basically we are using this:
https://github.com/Countly/countly-server/tree/next/bin/scripts/device_list
