### ISSUE TITLE
How to run Countly on sub-domain?

### ISSUE THREAD

**Issue by yaoboxu** [Countly/countly-server#353]
in our situtation, we must add a sub-domain in our requst, so i want to add a sub-domain into all the interface,  like this :   http://xxxx.xxx.xxx.xxx/countly    to login?

**Comment by gorkem-cetin** [comment]
We don't have this out of the box as it requires customizations. May I ask you why you require this, as Countly requires a full box to work on due to several libraries, specific Nodejs and MongoDB requirements?

**Comment by gorkem-cetin** [comment]
Closing this.. Please reopen if you think it is necessary.
