### ISSUE TITLE
Achieving high availability on AWS? Possible to use with Dynamo DB?

### ISSUE THREAD

**Issue by jeznag** [Countly/countly-server#354]
I'm a bit concerned about data loss if we put countly-server on one EC2 instance and it keels over and dies. How do people go about achieving high availability on AWS? Is it possible to use dynamo DB instead of mongo?

**Comment by gorkem-cetin** [comment]
DynamoDB doesn't have some of the features that we benefit from to make Countly work, so you cannot use it out of the box for now. 

For MongoDB HA, suggesting to read this document: https://resources.count.ly/docs/high-availability-deployment-enterprise-edition

Please ask your technical help related questions on http://community.count.ly, a more suitable place for such inquiries.
