### ISSUE TITLE
Countly performance issues [solved]

### ISSUE THREAD

**Issue by liansghuaifan** [Countly/countly-server#356]
when countly High concurrency running time , my cpu  have 4 cores，cat /proc/cpuinfo |grep "physical id"|sort |uniq|wc -l  is 4. my linux Configuration  net.ipv4.tcp_max_tw_buckets = 10000，i get  an error in log/countly-api.log such as
”caused by :: Location11002: socket exception [CONNECT_ERROR] for myip:27017 .“
I checked the Mong log and there was no error.but linux /var/log/messages  have such error
”kernel: TCP: time wait bucket table overflow“
Can you help me fix it?

countly-server-17.05.1
MongoDB shell version: 3.2.17
CentOS release 6.8 (Final)

**Comment by ar2rsawseen** [comment]
Hello
are there any changes to your database connection config from a default one we have? Like connection pool size or any timeouts?

And can you define high concurrency, like if database is not handling all the requests, they would queue up and nodejs processes would wait for responses keeping connections alive. But it just means server can't handle so much requests.

In those cases if you want to push further with same specs, you can try increasing net.ipv4.tcp_max_tw_buckets and net.ipv4.tcp_max_tw_buckets_ub values

**Comment by liansghuaifan** [comment]
Hello
You're absolutely right，my server  can't handle so much requests. i have increased net.ipv4.tcp_max_tw_buckets=50000,but 
netstat -antp | grep TIME_WAIT | wc -l  will be sustainable growth.
i guess my issue is  nodejs processes would wait for responses time > connections close time
high concurrency is mean  that  send four hundred random requests per second to countly
Can you help me fix it?
my database connection is default ,it like that
 mongodb: {
        host: "XX.XX.XX.XX",
        db: "countly",
        port: 27017,
        max_pool_size: 500,
        //username: test,
        //password: test,
        //mongos: false,
        /*
        dbOptions:{
            //db options
            native_parser: true
        },
        serverOptions:{
            //server options
            ssl:false
        }
        */
    },
 api: {
        port: 3001,
        host: "localhost",
        max_sockets: 1024,
        timeout: 120000
        /* GCM proxy server for push plugin
        push_proxy: {
            host: 'localhost',
            port: 8888
        } */
    },

**Comment by liansghuaifan** [comment]
I solved this problem with a physical server，I used the virtual machine before.
I guess that might be the problem of a single mongos on a virtual server
Thank you so much for your assistance.
