### ISSUE TITLE
How to know which device an event belongs to？

### ISSUE THREAD

**Issue by yaoboxu** [Countly/countly-server#365]
When  i want to see an event  send by which divice like Andriod or ios which upload by metrics. in the "source" table, there is only have appid and os_type,  but have no relation to  event table.

**Comment by ar2rsawseen** [comment]
Hello
Countly core which is a community edition mostly tracks anonymous data, so you won't know which exactly user did specific event or had specific metric.
But enterprise edition had Drill plugin, extending countly to store granular data and keeping all the relations. So through Drill functionality it is possible to know which use did what.

**Comment by yaoboxu** [comment]
When i want to upgrade from community edition to enterprise edition, this means that eventhough add drill plugin in my server, the old data i got has lost  all the relations.

**Comment by ar2rsawseen** [comment]
Unfortunately yes
