### ISSUE TITLE
Hello, when I install server, I don't know what the login account and password are

### ISSUE THREAD

**Issue by liuhuanhui** [Countly/countly-server#366]
![image](https://user-images.githubusercontent.com/10370625/33515984-895dc81c-d7a5-11e7-9c80-5c66ba7983d0.png)
Hello, when I install server, I don't know what the login account and password are
 thanks~

**Comment by liuhuanhui** [comment]
thinks  i see，countly add_user admin admin

**Comment by gorkem-cetin** [comment]
Please send your support questions to http://community.count.ly and bugs to GitHub please
