### ISSUE TITLE
Widgets don't display data anymore

### ISSUE THREAD

**Issue by bb-git** [Countly/countly-server#3818]
Dashboard Widgets broken. They stay empty and also adding new ones just creates empty widgets. Countly was updated to the latest version, but widgets broke later. Only one widget of 6 dashboards with around 100 widgets is working, times of the day.

### Expected Behavior
Widgets displaying data

### Current Behavior
Blank widgets

### Screenshots (if appropriate):
<img width="1611" alt="Bildschirm­foto 2022-12-25 um 13 54 29" src="https://user-images.githubusercontent.com/7348507/209468688-7e8b0fbc-7378-4cdf-8273-feb2ac5801d3.png">

### Possible Solution
No idea

### Steps to Reproduce (for bugs)
Every new widget added on our system stays blank.

### More Description
-

### Your Environment

Ubuntu 20.04
No modifications

**Comment by ar2rsawseen** [comment]
Hello,
Can you elaborate on which actions that's started to happen? If it was after the upgrade, then from which version to which?

**Comment by bb-git** [comment]
I updated from 22.09.x to 22.09.y and tested the widgets afterwards. Everything was working fine. When coming back a couple of days later it displayed only blank widgets.

**Comment by bb-git** [comment]
I cleared the cache and it's working. 🤷‍♂️
