### ISSUE TITLE
Platform changes "Windows 10" to "Windows Phone 10"

### ISSUE THREAD

**Issue by AndrewAtAvenza** [Countly/countly-server#3822]
I setup a test server and I'm just in the progress of running countly through it's paces. I'm pretty happy for the most part (though I've already found and patched a bug in the C++ SDK!). I finally got metrics working (see aforementioned bug) and the _Platforms_ page looks correct:

![image](https://user-images.githubusercontent.com/10466087/210483812-b2573494-1650-4dd7-a3c8-c13b6a0d13e0.png)

However, when I went to _Devices and Types_ page, I noticed this:

![image](https://user-images.githubusercontent.com/10466087/210483621-12bc88df-4774-4782-981b-761fb00fc675.png)

I'm not sure why it's decided to change "Windows 10" to "Windows Phone". I'm guessing this is just a cosmetic label bug somewhere in the server code?

For reference, this is the C++ code I used to generate that data:

```cpp
	countly.setDeviceID(GetClientId().toStdString()); // this gets a static, unique UUID
	countly.setLocation(std::string(), std::string(), std::string(), "<my IP address>");
	countly.setDatabasePath("<path to local .db>");
	countly.setMetrics("Windows 10", "10.0.19045.2364", "PC", "3840x2160", "Rogers", "11.1");
	countly.start("<my application ID>", "<our internal countly server>", 80, true);
```

Previously, I'd used:

```cpp
	countly.setMetrics("Windows 10", "10.0", "PC", "3840x2160", "Bell", "11.2");
```

That's why the two versions in the screenshot.

**Comment by ar2rsawseen** [comment]
Hello,
I think I know where this comes from, as firstly, Countly was Mobile only, there is an os mapping from long to short and vice versa, and it probably picks windows phone as the primary name. Basically, it is just a "localization" string kind of a thing, and I will create an internal ticket to fix this. And update here, when it is done
Thank you for reporting :)

**Comment by AndrewAtAvenza** [comment]
I had a suspicion it was something like that. I'm glad to hear it's cosmetic only (I was pretty sure, but you like to hear confirmation!). I'll just read that as 'Windows 10' for now then, and look forward to a fix sometime in the future :)

**Comment by ar2rsawseen** [comment]
Should be fixed here: https://github.com/Countly/countly-server/pull/3924
