### ISSUE TITLE
If you set the session expiration time to a large number the application becomes broken.

### ISSUE THREAD

**Issue by Danthekilla** [Countly/countly-server#395]
I set my session timeout time to 900000000009999 ms and now I get 1000's of expiration messages that take all input and have made my installation unusable.

How can this be undone?

![image](https://user-images.githubusercontent.com/2770203/34926635-d533b630-fa04-11e7-8f65-fa6095dbb6a1.png)

**Comment by Danthekilla** [comment]
Restarting the server doesn't fix the issue. I just thought I would try. Can I ssh in and change the value back to a sane value?

Perhaps there should be some validation of this field?

**Comment by ar2rsawseen** [comment]
`countly config "frontend.session_timeout" 0`

Will recheck that, but I think we had max limit to the input not to overflow.

**Comment by melihkorkmaz** [comment]
https://github.com/Countly/countly-server/commit/ccd2c0972d0df656d18b4bae0989d24bf764ffa5
