### ISSUE TITLE
How do you calculate sessions and users?

### ISSUE THREAD

**Issue by MrRRcc** [Countly/countly-server#419]
Hi ,I use mongo'log to calculate user sessions in different departments,but I cann't verify the total session with the sessions number on your dashbord.
My logic is that i calculate the count number where begin_session equals 1.
Am I wrong ?Please tell me your right logic,thanks!

**Comment by ar2rsawseen** [comment]
Hello,
so there is a concept of extending session and session cooldown time. You can read more on our SDK development guide:
https://resources.count.ly/docs/sdk-development-guide#section-session-cooldown

**Comment by gorkem-cetin** [comment]
Basically https://resources.count.ly/docs/technical-faq#section-how-are-event-and-session-data-sent-to-countly-

Clock ticks when begin_session is 1 and session ends when we receive end_session is 1

**Comment by MrRRcc** [comment]
get!thans you!If I have another question,I will log on https://community.count.ly .
