### ISSUE TITLE
Feature Extend Docker-compose for countly server

### ISSUE THREAD

**Issue by thatsk** [Countly/countly-server#429]
Hi Countly Team,
It's nice to create docker-compose for Countly Server for scaling purpose.

You can use recently docker squash command for compressing the size of Docker container.
But when I check dockerfile why we are adding a specific user like countly and MongoDB it can create a problem for binding the volume. Because it needs the user creates at host level also if the user is not present with that user id it cannot properly bind the volume and countly server crashes.

**Comment by iartem** [comment]
I've never heard of this before, so I guess you have some experience with this. Is this issue related? https://github.com/Countly/countly-server/issues/409

**Comment by thatsk** [comment]
no i am trying to say you have to create different container one is countly web and other is for mongodb and then it can combine with both.
