### ISSUE TITLE
Use squash option for building countly container.

### ISSUE THREAD

**Issue by thatsk** [Countly/countly-server#430]
If you are building container without squash the container size will be 
{code}REPOSITORY                                     TAG                 IMAGE ID            CREATED              SIZE
countly/countly-server                         latest              c5bef568d7e0        About a minute ago   1.41GB{code}
If you are building container with squash option the container size will be
REPOSITORY                                     TAG                 IMAGE ID            CREATED              SIZE
countly/countly-server                         squash              8eb56f868bb2        5 seconds ago        1.2GB

**Comment by iartem** [comment]
Pull requests are always welcome 👍
