### ISSUE TITLE
Login failed after I setup the environment and create the account

### ISSUE THREAD

**Issue by yusheng-jia** [Countly/countly-server#4327]
I install the countly-server on my own remote ubuntu server successfully.
When first login the website , I need to create my account and I did this.
I can login the website by this: http://192.168.10.54/login

But after server hours later , I need to re-login it again, it  always "Login falied"

<img width="785" alt="image" src="https://github.com/Countly/countly-server/assets/13306735/f21ef6cc-76cd-42d2-9953-12d1d9a4f6fb">

So I want to know how to solve this and is there any way to reset the account or password?
Even the forgot password not working after i filled the correct email address, i never received the email.

**Comment by ar2rsawseen** [comment]
There is a way to reset in Management -> User Management that can be done by Global admin
or clear countly.failed_logins collection like

```
mongo
use countly
db.failed_logins.deleteMany({})
```

**Comment by yusheng-jia** [comment]
> There is a way to reset in Management -> User Management that can be done by Global admin or clear countly.failed_logins collection like
> 
> ```
> mongo
> use countly
> db.failed_logins.deleteMany({})
> ```

Do you know how to find mongo ?
I installed the countly-server on ubuntu flow this: https://support.count.ly/hc/en-us/articles/360036862332-Installing-the-Countly-Server

But when run mongo in the cmd, command 'mongo' not found
![image](https://github.com/Countly/countly-server/assets/13306735/da200aae-e427-4eb6-9fdb-af02d98287ed)

**Comment by ar2rsawseen** [comment]
Oh, sorry, it is
```
mongosh
```
now since the latest major version :)

**Comment by yusheng-jia** [comment]
Thanks, I can run it, but the thing is 'login failed', I believe the password is correct. so can i delete the my user and recreate a new count?

**Comment by ar2rsawseen** [comment]
Yeah, you can also delete all users by doing the same to db.members collection
and then you would have a setup page again.

Or you can try the forgot password flow, if your mail server accepts emails from local sendmail

about validity of the password, sorry can't comment there, but try setting it up again and make sure it is correct
if there is still a problem, let us know :)

**Comment by yusheng-jia** [comment]
I seem found the problem,  my actual username is 'Jayson' but when I filled it in the login page, it always force to lowercase:
'jayson'.
<img width="603" alt="image" src="https://github.com/Countly/countly-server/assets/13306735/993dedc2-9069-4e4b-b205-b1cf697888b4">
I'm not sure if this is a problem, but anyway, I solve it by login with email address. Thanks.

**Comment by ar2rsawseen** [comment]
Thank you for the insight, I will create a ticket internally to confirm this too :)
