### ISSUE TITLE
Unable to display Crashes, missing Countly.add_consent()

### ISSUE THREAD

**Issue by tlhunter** [Countly/countly-server#459]
My web application is generating crashes and submitting them to the Countly server. Countly is accepting them and acknowledging the report. However the Crashes Overview remains empty with the "No data" message.

Furthermore, while attempting to call `Countly.add_consent`, I get an error that the method does not exist. This method is documented in the [Web analytics (JavaScript)](https://resources.count.ly/docs/countly-sdk-for-web) page. I'm not sure if this missing method is related or not, though, as the crash messages are being sent to the server.

While using the DB Viewer, I can see that the three `app_crash*` collections are all empty.

### Expected Behavior
When a web client sends a crash it should be immediately visible in the Countly interface.

### Current Behavior
Errors are not being being displayed in the Countly interface.

### Screenshots (if appropriate):

Here's a screenshot of the JavaScript console:

![20180322210937](https://user-images.githubusercontent.com/551402/37811555-4d891d90-2e18-11e8-8c89-938a0d9c6048.png)

The server responds with a 200 OK:
```json
{"result":"Success"}
```

### Steps to Reproduce (for bugs)
I'm throwing an error in a new stack to make sure it doesn't break anything else:

```js
setTimeout(() => {
  throw new Error('fuck');
}, 1000);
```

This is with **Countly CE v18.01.1**.

### Context
The JavaScript file I'm using is downloaded from my analytics instance:
https://analytics.phobosrising.co/sdk/web/countly.min.js
(Note that the word 'consent' doesn't appear anywhere in the file)

Normal events are being properly tracked.

My initialization code looks like this:

```js
    Countly.init({
      app_key: app_key,
      url: countly_url,
      device_id: 'uuid string',
      app_version: '1.2.3',
      debug: true
    });
    //Countly.add_consent("crashes");
    Countly.userData.set('cordova', app.device.cordova);
    Countly.userData.set('vendor', app.device.vendor);
    Countly.track_errors();
    Countly.track_sessions();
    Countly.userData.save();
```

If I visit the Event Logs, I can see that the server is receiving the events:

![20180322210952](https://user-images.githubusercontent.com/551402/37812040-025bcc48-2e1b-11e8-85e0-c8d5f865bec2.png)

### Your Environment
* Operating System and version: Linux localhost 4.15.8-x86_64-linode103 #1 SMP Fri Mar 9 21:02:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Any changes you have made to your instance: None, this is a fresh installation using the recommended bash script

**Comment by ar2rsawseen** [comment]
Hello,
are there anything in log/countly-api.log file about parsing errors?

**Comment by tlhunter** [comment]
I didn't see anything in the logs. I cleared them and sent crash reports again and the log remains empty.

**Comment by ar2rsawseen** [comment]
Ok, I think the explanation could be that, if you go to Management -> Applications and select your app, it probably does not have Web type, but mobile, or something like that? Crashes are processed differently based on what app type is selected. Can you recheck?

**Comment by tlhunter** [comment]
That was the issue! My application is a mobile app wrapped in Cordova, but I'm using the JS libraries, not the native libraries.

I'd like to formally request some sort of error to help anyone else who makes this mistake (-:

**Comment by gorkem-cetin** [comment]
Sure, where do you think it will be most useful for you to see this warning/help? Multiple places can be OK.

**Comment by ar2rsawseen** [comment]
Completely agree with you. First step is adding Problems section to Events logs (the one you checked if the request came in).
It will look something like this, and I think a perfect place for displaying such informations:

![image](https://user-images.githubusercontent.com/399992/37819111-0ec20ea6-2e85-11e8-9495-2b7aa108136e.png)

**Comment by ar2rsawseen** [comment]
Added here:
https://github.com/Countly/countly-server/commit/e47bf97acf3907d055a06f17a7c86c98179ce5e2

And about add_consent, then I think it is available in github repo, but not yet published in npm, we try to synchronize SDK releases with server.

**Comment by tlhunter** [comment]
@gorkem-cetin Getting a 500 error or a console warning in the client would be useful to find the error during development. Getting the error in the UI system log would be useful for debugging deployed apps.
