### ISSUE TITLE
One-liner installation failed

### ISSUE THREAD

**Issue by jeffguorg** [Countly/countly-server#464]
### Expected Behavior

run the line and get a community server
```
wget -qO- http://c.ly/install | sudo bash
```

### Current Behavior

get a 404 from clouddn

### Screenshots (if appropriate):

[output.txt](https://github.com/Countly/countly-server/files/1850242/output.txt)

no screenshots but output from bash

### Possible Solution

I think it's related to the cdn you use

### Steps to Reproduce (for bugs)

[output.txt](https://github.com/Countly/countly-server/files/1850242/output.txt)

### Context

I was trying to deploy an instance on a clean vps but failed.

### Your Environment

* Operating System and version: Ubuntu 16.04.1
* Any changes you have made to your instance: nop

well, btw i'm in China

wish it could help

**Comment by ar2rsawseen** [comment]
Yes, it does help :)
So I see we try to ping google and if not successful then download from CDN
@waiterZen should know more about it :)

**Comment by jeffguorg** [comment]
I temporarily checkout the repository and installed the server locally

Google and some of CDNs are banned from China. You might need to fallback to fetch the file from github aws or your own server. 
and I suggest you check the digest of the file. it could be broken due to bad network environment.

**Comment by waiterZen** [comment]
Yes, we may should make it automatic. We store tar file in Qiniu CDN so far, and it is not efficiency.  Will update soon
