### ISSUE TITLE
"Click to view details" link in crash email doesn't work if I am viewing a different app

### ISSUE THREAD

**Issue by matthewl-biomatters** [Countly/countly-server#467]
To reproduce:
1. Open a browser tab for "App A" dashboard on https://try.count.ly
2. Click on "Click to view details" in an email reporting a crash from "App B"
3. A new tab opens in the browser showing Countly with a popup saying `This crash report cannot be viewed. Possible reasons: You are trying to view a crash report that you do not have access to or Link to this crash is invalid.`

The email links are like `https://try.count.ly/dashboard#/crashes/SOME_ID`

Chrome 64.0.3282.167 (Official Build) (64-bit) on macOS

**Comment by ar2rsawseen** [comment]
Hello,
this would be email from Alerts notifying about new crash, is that correct?

**Comment by ar2rsawseen** [comment]
@waiterZen can we use link with app_id in the alerts emails?

**Comment by matthewl-biomatters** [comment]
Yes the email about new crashes, the email subject is `Received new crashes for APP_NAME`

**Comment by waiterZen** [comment]
@ar2rsawseen  Yes, we can improve this part.
@matthewl-biomatters  Will fix soon, thanks for pointing out :)

**Comment by waiterZen** [comment]
committed and will release at 18.06
