### ISSUE TITLE
Incorrect country lookup from IP address

### ISSUE THREAD

**Issue by immermarc** [Countly/countly-server#478]
The country of users in Switzerland is shown as Germany, for a specific IP address range.

### Current Behavior
The country of a user is incorrectly detected as Germany where it should be Switzerland (using Countly community edition V 18.01.1)
Webpages such as https://www.iplocation.net/ show the correct country. 

This is possibly due to the use of te npm package geoip-lite to look-up ip addresses.

### Steps to Reproduce (for bugs)
This can be shown for an IP in the range 84.254.8X.XX such as 84.254.85.0, by
lookup the ip address with nodejs and the npm package geoip-lite:

```
var geoip = require('geoip-lite');

var ip = "84.254.85.0";
var geo = geoip.lookup(ip);

console.log(geo);
```
{ range: [ 1425948672, 1425965055 ],
  country: 'DE',
  region: '',
  city: '',
  ll: [ 51.2993, 9.491 ],
  metro: 0,
  zip: 0 }

**Comment by ar2rsawseen** [comment]
Hello, try updating your ip to geo database by running

`countly update geoip`

**Comment by immermarc** [comment]
This worked, thanks!

**Comment by Meserias** [comment]
![lic_key](https://github.com/Countly/countly-server/assets/12730634/80059ae4-4af7-4978-925a-09c2e72aa2ad)
could you please let me know where exactly should I add license key ?
it's not clear how do I provide new license key for GeoIP to countly

**Comment by ar2rsawseen** [comment]
Hello
good point, I will add this to internal tasks :)

**Comment by ar2rsawseen** [comment]
The way we do it in our build pipeline is actually following the original doc:
https://github.com/geoip-lite/node-geoip#ways-to-update-data

So basically going to countly/node_modules/geoip-lite
and running their command:
```
npm run-script updatedb license_key=YOUR_LICENSE_KEY
```
