### ISSUE TITLE
View duration not recorded when using manual view tracking

### ISSUE THREAD

**Issue by BerndStoltefuss** [Countly/countly-server#480]
When using manual view tracking with Countly.SharedInstance().ReportView("my View") the view duration is not recorded.

### Expected Behavior
View duration should be recorded in DB when using manual view tracking.

### Current Behavior
When using manual view tracking with Countly.SharedInstance().ReportView("my View") the view duration is not recorded, although the client sdk does correctly compute view duration (as shown in countly debug log) and the event seems to be pushed correctly(?) to the server.

### Screenshots (if appropriate):
Client debug log:
2018-04-18 09:20:52.114 XXX.iOS[40204:829375] [Countly] View tracking started: Settings.AppLoginPage
2018-04-18 09:21:09.116 XXX.iOS[40204:829375] [Countly] View tracking ended: Settings.AppLoginPage duration: 17.001121

Server event view:
`{
  "app_key": "xxx",
  "device_id": "xxx",
  "timestamp": "1524036110782",
  "hour": "9",
  "dow": "3",
  "tz": "120",
  "sdk_version": "17.05",
  "sdk_name": "objc-native-ios",
  "events": [
    {
      "dur": 0,
      "hour": 9,
      "segmentation": {
        "segment": "iOS",
        "visit": 1,
        "name": "Settings.AppLoginPage",
        "start": 1
      },
      "count": 1,
      "key": "[CLY]_view",
      "timestamp": 1524036052114,
      "dow": 3,
      "sum": 0
    },
    {
      "dur": 17.001121044158936,
      "hour": 9,
      "segmentation": {
        "name": "Settings.AppLoginPage",
        "segment": "iOS"
      },
      "count": 1,
      "key": "[CLY]_view",
      "timestamp": 1524036052115,
      "dow": 3,
      "sum": 0
    },
    {
      "dur": 0,
      "hour": 9,
      "segmentation": {
        "name": "MainPage",
        "segment": "iOS",
        "visit": 1
      },
      "count": 1,
      "key": "[CLY]_view",
      "timestamp": 1524036069116,
      "dow": 3,
      "sum": 0
    }
  ]
}`

DB view:
`{
    "_id": "no-segment_2018:4_Z",
    "m": "2018:4",
    "a": "xxx",
    "d": {
        "18": {
            "9": {
                "Settings&#46;AppLoginPage": {
                    "u": 1,
                    "t": 1,
                    "s": 1
                }
            },
            "Settings&#46;AppLoginPage": {
                "u": 1,
                "t": 1,
                "s": 1
            }
        }
    }
}

{
    "_id": "iOS_2018:4_Z",
    "m": "2018:4",
    "a": "xxx",
    "d": {
        "18": {
            "9": {
                "Settings&#46;AppLoginPage": {
                    "u": 1,
                    "t": 1,
                    "s": 1
                }
            },
            "Settings&#46;AppLoginPage": {
                "u": 1,
                "t": 1,
                "s": 1
            }
        }
    }
}
`
GUI:
Analytics->Views shows 0.0 as AVG.TIME for Settings.AppLoginPage

### Your Environment
Server: Countly 18.1.1 Enterprise Edition
Client: Countly SDK for Xamarin.iOS 1.0.2

**Comment by ar2rsawseen** [comment]
Hello,
this issue is due to un rounded duration value and has been fixed here:
https://github.com/Countly/countly-server/commit/bef7c7d55486c6cde19a4fcb7e9696e1d8f1ac62

And will be available in next release
