### ISSUE TITLE
Landing page has a horizontal scroll

### ISSUE THREAD

**Issue by dotslashbit** [Countly/countly-server#4817]
### Expected Behavior

It's good if we can eliminate the horizontal scroll

### Current Behavior

There's a horizontal scroll in the landing page, see the screenshot for better understanding

### Screenshots (if appropriate):
<img width="1710" alt="Screenshot 2024-01-04 at 6 35 16 PM" src="https://github.com/Countly/countly-server/assets/46224156/81235a20-78ec-4e9d-95a8-66b5697c97a9">

### Steps to Reproduce (for bugs)

1.https://countly.com/ Just 
2.
3.
4.

### Your Environment

* Operating System and version: Mac OS Sonoma 14.1.1
* Any changes you have made to your instance: None

**Comment by ar2rsawseen** [comment]
Hello,
thank you for reporting
Forwarding to your marketing team who manages the website :)

**Comment by ar2rsawseen** [comment]
It looks like the issue has been resolved now
Thank you for reporting :)
