### ISSUE TITLE
China map is displayed incorrectly

### ISSUE THREAD

**Issue by leewenbil** [Countly/countly-server#4851]
China map is displayed incorrectly, because Taiwan is not included. Internationally, we know the one-China principle, China map must include Taiwan.

### Expected Behavior
China map must include Taiwan.

### Current Behavior
China map does not include Taiwan

### Screenshots (if appropriate):
![image](https://github.com/Countly/countly-server/assets/3294022/1928a824-39e4-42d9-a083-9b94a1cb5d86)

### More Description
As this issue, we cannot use this product. Maybe you lost many customers as this reason(especially, in China)

**Comment by ar2rsawseen** [comment]
Hello
Thank you for raising the issue.

Unfortunately we are not creating the map ourselves, but using third-party provider data.
And the source we are using, "Natural Earth Data", uses Open Street Map default mapping.

I checked this case specifically here:
https://wiki.openstreetmap.org/wiki/Disputed_territories

So basically, our maps display what Google Maps or Open Street Maps would display, and we go with that as default.

If you know any good offline open-source libraries providing support for alternative tagging or configurations, please let us know :)

**Comment by leewenbil** [comment]
> Hello
> Thank you for raising the issue.

Thank you for your feedback.
For this issue. Here is option:
1、make the map source to plug-in components or plugin.

**Comment by ar2rsawseen** [comment]
Since lots of our deployments are offline, we cannot really use online maps. They should be available offline.

What I think we could do is to allow overwriting geojson data we use (https://github.com/Countly/countly-server/tree/master/frontend/express/public/geodata) with your own, so you could structure the map as you would like.

I am not sure how we could do that exactly yet, so upgrades would not overwrite them, but I think the might be already overriddable by themes. But we need to test this.

**Comment by ar2rsawseen** [comment]
So with this PR (https://github.com/Countly/countly-server/pull/4855) you should be able to override the geojson in files for the map using themes.
It also has an example theme with the map that has Antarctica.

In your case, you would need to find a geojson map that has the visualization you need, like maybe this one: https://github.com/georgique/world-geojson/blob/develop/countries/china.json

I am not sure if the formats match, you can try it out.
Then you create a theme similar like in the example PR and you recreate the structure of the geodata folder for the file you want to override, which I guess is this one: https://github.com/Countly/countly-server/blob/master/frontend/express/public/geodata/region/CN.geojson

Let me know if you have any questions :)

**Comment by leewenbil** [comment]
@ar2rsawseen Thank you for your help. I will try it.
