### ISSUE TITLE
One line install fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by tlhunter** [Countly/countly-server#493]
I've attempted to install Count.ly on a fresh Ubuntu Bionic Beaver 18.04 LTS install and receive an error. The package `python-software-properties` cannot be found and fails the install. It appears to be superseded by `software-properties-common`. However that package is already installed when the failure occurs.

### Expected Behavior
Should install as easily on this Ubuntu LTS as it did for the previous LTS.

### Current Behavior
Installation fails

### Screenshots (if appropriate):
![20180508150310](https://user-images.githubusercontent.com/551402/39785792-53a6cc48-52d2-11e8-8817-74b12c5e3e38.png)

### Possible Solution
I'm sure downgrading to a previous LTS fixes the problem.

### Steps to Reproduce (for bugs)
1. Install fresh server: https://www.ubuntu.com/download/server
2. Execute one-line install

### Your Environment
* Operating System and version: Kernel 4.15.0
* Any changes you have made to your instance: None, fresh VM install

**Comment by tlhunter** [comment]
Eventually the installer fails as it's unable to find node/npm, so it'll probably take some work to get the ubuntu installer working with 18.04.

**Comment by ar2rsawseen** [comment]
Hello,
this has been fixed here:
https://github.com/Countly/countly-server/commit/c78bc6de308e1baa79e7fe4f3809f7a299cd4c36

We will soon make another release with those fixes

**Comment by ar2rsawseen** [comment]
This has been fixed in:
https://github.com/Countly/countly-server/releases/tag/v18.04.1
