### ISSUE TITLE
Replacing MongoDB with Couchbase

### ISSUE THREAD

**Issue by Fujio-Turner** [Countly/countly-server#537]
Looking into Replacing MongoDB with Couchbase.

With Couchbase Lite 2.x with FTS and SQL(N1QL) on the device. Customers are wanting to capture user activity data and sync it into Couchbase.

Since Countly is open source and can be self-hosted many people are wanting a solution that can scale and leverage Couchbase Analytics.

**Comment by gorkem-cetin** [comment]
Closed due to inappropriate (e.g no PR) and also we haven't received a single request from customers to replace MongoDB. Thus we have no intention to move to Couchbase.
