### ISSUE TITLE
Requests to countly blocked by ublock

### ISSUE THREAD

**Issue by stewartwebb** [Countly/countly-server#551]
### Expected Behavior

Requests to countly server should go through fine and not be blocked by ublock.

### Current Behavior

Ublock picks up on the pattern `?begin_session=*&metrics=` in requests and automatically blocks them. This happens even if countly is setup on the same domain as the website that you want to track.

### Screenshots (if appropriate):
Screenshot from the ublock debug request screen.
![screenshot from 2018-07-05 10-14-44](https://user-images.githubusercontent.com/2047191/42444818-fc4c697c-8368-11e8-8c7a-936e3782cf9c.png)

### Possible Solution

You can view the ublock rule here I believe: https://github.com/uBlock-LLC/uBlock/blame/master/assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt#L3602

My "solution" would be to in the short term change the parameter names. In the long term, make them customisable by the end user through a configuration option on the server and client.

### Steps to Reproduce (for bugs)

Install ublock origin on your web browser. Navigate to a website running countly and check console for requests failed with error: CLIENT_ERR. Then check the ublock logger for more detail on the reason for being blocked.

### More Description

I had been experiencing similar issues for a while but I recently implemented a reverse proxy on my setup to ensure the countly domain was the same as my website as suggested in many articles. https://medium.freecodecamp.org/save-your-analytics-from-content-blockers-7ee08c6ec7ee

### Your Environment
Only difference from a vanilla install is that I reverse proxy all requests to `/analytics` to my countly server, making sure to rewrite the url to remove the `/analytics` portion.

**Comment by ar2rsawseen** [comment]
After more consideration on this, I don't think renaming parameters is viable. We have a documented API which should not change that drastically.
But since blocker blocks URL params, I think it would be enough for you to force POST requests always by SDK, that way it won't have any parameters at all.

So try setting force_post to true on init:
https://code.count.ly/sdk/web/Countly.html#.init

And let us know how it goes :)

**Comment by stewartwebb** [comment]
Thanks @ar2rsawseen, that fixed out issue. Is there any benefit in making post the default setting?

**Comment by ar2rsawseen** [comment]
Not exactly, post data won't also show in access logs, but since data is now delivered in the body and not in the header, there is a slight overhead for each request.

**Comment by gorkem-cetin** [comment]
I will add this to FAQ, thank you for raising this up @stewartwebb
