### ISSUE TITLE
Cannot display maps and country information

### ISSUE THREAD

**Issue by lijunboy008** [Countly/countly-server#553]
I know that in china can't use google maps, so countly Cannot display maps when Some people visit my website，but Is there any other way to display map information?

and i use docker to install the countly like this:
`docker run -d -p 32769:80  countly/countly-server`

after installed，i use the Web analytics (JavaScript) Document example to track and drill，but  the country display unknown 
![default](https://user-images.githubusercontent.com/30118692/42608486-8d785df4-85ba-11e8-9d30-28eb6051d9ec.PNG)

so How to solve this problem?
Thanks

**Comment by ar2rsawseen** [comment]
Hello,
even with Google disabled, countries still should record correctly. They would just no be displayed on map, but rather in table. So the problem is somewhere else.

We determine country by ip address of the connection that is made to server. Maybe somewhere on its way it loses this and you need to pass it in header, etc?

When you check Management -> Event logs, and click on request to view its full info, do you see headers like x-forwarded-for or x-real-ip? Do they contain valid ip addresses?

**Comment by lijunboy008** [comment]
thanks,I know where the problem is. I use the intranet for testing
i check Management -> Event logs,
```
{
  "x-forwarded-for": "172.16.40.92",
  "x-real-ip": "172.16.40.92",
  "host": "127.0.0.1:3001",
  "connection": "close",
  "pragma": "no-cache",
  "cache-control": "no-cache",
  "origin": "http://172.16.40.92:5000",
  "user-agent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
  "accept": "*/*",
  "referer": "http://172.16.40.92:5000/statisticArbitrage",
  "accept-encoding": "gzip, deflate",
  "accept-language": "zh-CN,zh;q=0.9"
}
```
Is the intranet ip

but how to solve the problem of google map，Can I use other maps?，how to set it

**Comment by ar2rsawseen** [comment]
I see there is ECharts used on asia-try servers

![image](https://user-images.githubusercontent.com/399992/42678540-e1c301d4-8687-11e8-95ed-54fa10baf2bc.png)

But not sure about availability

@gorkem-cetin ?

**Comment by gorkem-cetin** [comment]
@lijunboy008 not available for the masses yet, but we will release it very soon. We can let you know :)

**Comment by lijunboy008** [comment]
@ar2rsawseen   i'm install countly on AWS EC2 instances，but the country display unknown。
The following is my installation steps to test：

1.install countly 
`docker run -d -p 31768:80 countly/countly-server`
and then config App Application

2. install nginx
`docker run -d -p 31767:80 nginx`
and then modify the index.html , insert the javascript include Countly.app_key and Countly.url
you can  visit http://52.83.226.36:31767/, View page source code

3.check Management -> Event logs
```
Headers:
{
  "x-forwarded-for": "59.37.11.103",
  "x-real-ip": "59.37.11.103",
  "host": "127.0.0.1:3001",
  "connection": "close",
  "origin": "http://52.83.226.36:31767",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36",
  "accept": "*/*",
  "referer": "http://52.83.226.36:31767/",
  "accept-encoding": "gzip, deflate",
  "accept-language": "zh-CN,zh;q=0.9"
}
```
I can query this network IP address，but the  Analytics ->Countries still  unkown
  
![_20180718092920](https://user-images.githubusercontent.com/30118692/42854170-25caf8a8-8a6d-11e8-936f-1eaa37de53d1.png)

**Comment by lijunboy008** [comment]
I signing up for a 30 day Countly Enterprise trial , and config the App Application,set Countly.url
Countly.url=https://asia-try.count.ly

and then i  visit http://52.83.226.36:31767/，but the Analytics ->Countries and Management -> Event logs still unkown

**Comment by ar2rsawseen** [comment]
Hello
so we are using geoip lite database to determine location based on ip address.
I tested it with old version that is used in latest release, and it does not have your ip adrress listed.

In development code, we already upgrade to geoiplite2 which is newer database and there it determines your ip as:

```
{ range: [ 992280576, 992313343 ],
  country: 'CN',
  region: 'AS',
  eu: '0',
  timezone: 'Asia/Shanghai',
  city: 'Guangzhou',
  ll: [ 0, 0 ],
  metro: 0 }
```

So it will be working "hopefully" correctly, database is just older in previous release.

**Comment by lijunboy008** [comment]
Thanks，so I have to wait for your new version to be released.

**Comment by gorkem-cetin** [comment]
We have released the new version, please check @lijunboy008 .. Now it uses EChartMap for country view replacement for servers without Google services.
