### ISSUE TITLE
Countly Message Notification Error 

### ISSUE THREAD

**Issue by GaneshShetty951** [Countly/countly-server#582]
### Expected Behavior

I am testing Countly notification, it is giving error status for notifications as 1-EOF
![screen shot 2018-08-02 at 4 29 21 pm](https://user-images.githubusercontent.com/15211105/43580431-15e7e04c-9673-11e8-9df2-c0aadc9d8510.png)

Any help would be appreciated

**Comment by iartem** [comment]
Hi @GaneshShetty951, please update your server to latest version. Closing it for now, but feel free to reopen this issue if problem persists.
