### ISSUE TITLE
dashboard app path configuration seems problematic

### ISSUE THREAD

**Issue by ronkorving** [Countly/countly-server#616]
### Expected Behavior

All dashboard assets should be downloadable.

### Current Behavior

Half the endpoints give 404s when configuring path to be `/admin`. Mostly:

- fonts
- svg files
- API endpoints

Shorter endpoints create other problems in `app.js`:

**If path is empty string:**

this line breaks:

```js
app.use(countlyConfig.path, express.static(__dirname + '/public', { maxAge:oneYear }));
```

**If path is single forward slash (“/“):**

the app will redirect to //login which removes the domain name part from the URL (ie: we navigate to `http://login`):

```js
 app.get(countlyConfig.path+'/', function (req, res, next) { 
  res.redirect(countlyConfig.path+'/login'); 
});
```

**Unlike most other Express middleware functions, these 2 ignore countlyConfig.path** (I’m not sure if this is intentional):

```js
app.use('/stylesheets/ionicons/fonts/', function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
})

app.use('/fonts/', function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
})
```

### Possible Solution

Sanitize `countlyConfig.path` to be consistent whether or not empty string or trailing slash is input in config file, and update provided code to play nice with it (see items above).

### Steps to Reproduce (for bugs)

1. configure the `path` in frontend/express/config.js to be empty string, `/` or `/admin`
2. boot up the dashboard
3. sign up
4. open your browser console's network tab, lots and lots of 404s

### More Description

I'm trying to deploy Countly, but am stuck on this.

### Your Environment

* Operating System and version:

Provided Docker image with Countly 18.04.1.

* Any changes you have made to your instance: 

app/config.js:

```js
  mongodb: 'somestring',
  web: {
    port: 6001,
    host: '0.0.0.0',
    use_intercom: false,
    secure_cookies: false,
    track: 'none'
  },
  path: '/admin'
}
```

**Comment by ar2rsawseen** [comment]
So initial idea was to be able to provide a way to install countly in sub directory of domain.
But then this idea was scratched as too much work, and countly should be on dedicated server eitherway, so should at least have a subdomain, so this config is more of a legacy thing to not break the old code, but should not be used :(

**Comment by ar2rsawseen** [comment]
Any specific error you are seeing for default empty value?

**Comment by ronkorving** [comment]
See bug-report in the description above. Empty string makes this line fail:

```js
app.use(countlyConfig.path, express.static(__dirname + '/public', { maxAge:oneYear }));
```

Maybe I messed up... I will try again, just in case.

**Comment by ronkorving** [comment]
I tried again with empty string. No issues this time (of course, because magic). I'll leave it as-is then.
