### ISSUE TITLE
Typo in dashboard: dsiplay

### ISSUE THREAD

**Issue by ronkorving** [Countly/countly-server#623]
I noticed a typo in the dashboard today under `Events > Manage events > $eventname`, in the menu it says: `Dsiplay name for sum`

This is Countly Enterprise v18.04.1.

https://github.com/Countly/countly-server/search?q=Dsiplay+name+for+sum&unscoped_q=Dsiplay+name+for+sum

**Comment by ar2rsawseen** [comment]
Hello,
thanks for reporting, I think our original string was already fixed:
https://github.com/Countly/countly-server/blob/master/frontend/express/public/localization/dashboard/dashboard.properties#L361

The rest will be fixed when we sync up with translation service before packaging
