### ISSUE TITLE
FCM returned error 200 MismatchSenderId

### ISSUE THREAD

**Issue by cristobal151** [Countly/countly-server#670]
Every time I try to send a push message to Android devices, FCM throws me the following error MismatchSenderId

### Expected Behavior
Push message sent and received correctly

### Current Behavior
Message not sent, although in the dashboard it appears as sent.

### Your Environment
* Operating System and version: Centos 7
* Any changes you have made to your instance: No

**Comment by iartem** [comment]
That's not a server issue, so closing it. Feel free to reply though.

That issue means that Countly SDK competes for tokens with some other SDK. I'm not aware of this happening in 18.04+ versions of SDK if using FCM dependency `sdk-messaging-fcm`. And we have [a guide for FCM](https://resources.count.ly/docs/countly-sdk-for-android#section-setting-up-push-notifications).

**Comment by cristobal151** [comment]
Hello,
I am using the application example that comes in the Android SDK and I get that error.

I have done everything the documentation says that had to be done and I still get that error. Is it possible that something is missing from that application so that it works?

Please help me. Thanks.

**Comment by iartem** [comment]
Have you updated `google-services.json`?

**Comment by cristobal151** [comment]
Yes, I did and I still get the same error.

**Comment by cristobal151** [comment]
If I send it directly from FCM I get the notification in the application, but if I use countly it keeps giving the same error: MismatchSenderId

**Comment by iartem** [comment]
Then probably you use server key in Countly server for the app other than set in `google-services.json`.
