### ISSUE TITLE
Can't create users through the countly API

### ISSUE THREAD

**Issue by umang0202** [Countly/countly-server#688]
Whenever I try to call the /users/create API, i get a 400 error with "Not enough args" as the response

### Expected Behavior
For a user to be created

### Current Behavior

Error - not enough args. 400 Bad request.

### Your Environment
GET /i/users/create?api_key=MY_KEY&args={
    "admin_of": [
    ],
    "user_of": [
    ],
    "global_admin": false,
    "full_name": "Umang Agarwal",
    "email": "umang0202@yahoo.com",
    "password": "fairfes123t",
    "username": "shabana12312"} HTTP/1.1

400 BAD REQUEST

{
    "result": "Not enough args"
}

* Operating System and version:
* Any changes you have made to your instance:

**Comment by ar2rsawseen** [comment]
Hello,
yes we need to modify that behavior to output what exactly is wrong.
Here I can only guess for now that password does not fit the policy setup on your server, either length or required chars
