### ISSUE TITLE
Unable to launch docker image ('waiting for MongoDB to allocate files')

### ISSUE THREAD

**Issue by chrisrothwell** [Countly/countly-server#708]
EDIT - seems to be same as closed issue #409 
### Expected Behavior
Installed latest docker build according to the instructions and expected to be able to access the management console.

docker run -p 32768:80 countly/countly-server

### Current Behavior
Container starts but the output is as follows
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 8
tail: unrecognized file system type 0x794c7630 for ‘/var/log/syslog’. please report this to bug-coreutils@gnu.org. reverting to polling
exception: connect failed
exception: connect failed

[dashboard] waiting for MongoDB to allocate files ...

[api] waiting for MongoDB to allocate files ...
exception: connect failed
exception: connect failed

When trying to access the management console on port 32768, we get nginx 502 bad gateway error.

### Steps to Reproduce (for bugs)
1. docker run -p 32768:80 countly/countly-server
2. Try to access server at <ipaddress>:32768

**Comment by iartem** [comment]
After googling your error I found that it's an issue with your docker setup, that is `overlay` driver being not supported by coreutils.

**Comment by chrisrothwell** [comment]
Hi, thanks for getting back so fast.  Actually the issue was even simpler than that - lack of disk space on my linux instance :) docker image is working fine now.

**Comment by iartem** [comment]
Good to know, thanks!

**Comment by benbro** [comment]
I'm getting the same error and I have 10GB of free space on the host Ubuntu 18.04 machine.
What could be the issue?

**Comment by iartem** [comment]
@benbro Is it still an issue?

**Comment by benbro** [comment]
No, thanks.
