### ISSUE TITLE
Use MessagePack for event dispatch to server

### ISSUE THREAD

**Issue by molind** [Countly/countly-server#73]
There is a great binary format similar to JSON: http://msgpack.org and it have node.js binding: https://github.com/pgriess/node-msgpack

I think it would be great to add binary event endpoint (http://serverName.com/b for example) and receive events as content of HTTP POST requests.

If anyone could implement this server enhancement i'll send patch for iOS SDK with MessagePack support.

**Comment by ar2rsawseen** [comment]
Currently json implementation is used quite a lot through all the code, so it would be lots of changes to the core.

As this also concerns SDKs (many of which are managed by different developers), I really don't see this as an option for now.
