### ISSUE TITLE
How to count unique devices of an event?

### ISSUE THREAD

**Issue by nighon** [Countly/countly-server#736]
### Expected Behavior

For example, we would like to know how many devices installed a particular app. 

| segmentation | count | unique devices |
| --------------- | ------: | --------------: |
| com.facebook.game | 2 | 1 |

### Current Behavior

There is only count for how many times (c) the event happens. Can we also get the count of unique devices (u) for the event.

### Steps to Reproduce (for bugs)

1. mobile phone sdk send event data to countly server
2. go to Countly Dashboard > Events > All Events
3. and we can see only two columns: segmentation and count. can we get one more column like "unique devices"?

The requested data:

```
{
  key: "app_install",
  count: 2,
  segmentation: {
    app_id: "com.facebook.game"
  }
}
```

### Your Environment

* Operating System and version: countly-server 18.08
* Any changes you have made to your instance:

**Comment by ar2rsawseen** [comment]
Hello,
the core only stores data in aggregated anonymous format, thus we cannot tie event to any specific user.
But it is possible with granular data level in Enterprise Edition
So this exists by design, sorry :)
