### ISSUE TITLE
Add new devices

### ISSUE THREAD

**Issue by MaximKeegan** [Countly/countly-server#76]
Can anybody add new devices to  countly.device.js?
iPhone 5C 
iPhone 5,3 
iPhone 5,4   
iPhone 5S:
iPhone 6,1
iPhone 6,2

**Comment by gorkem-cetin** [comment]
iPhone 6s:   (s lowercase according to Apple)
iPhone8,1

iPhone 6s Plus:   (s lowercase according to Apple)
iPhone8,2

Ref: 
http://www.everymac.com/ultimate-mac-lookup/?search_keywords=iPhone8,1
http://www.everymac.com/ultimate-mac-lookup/?search_keywords=iPhone8,2

**Comment by ar2rsawseen** [comment]
Updated list of devices here:
https://github.com/Countly/countly-server/commit/251bb9e143e7dac1e2e832df0c819c14a03d5fec

But also added command to retrieve list of devices: countly update devices
https://github.com/Countly/countly-server/commit/d038583f64a2d31bd9e420b95ad33fe5c077950d
