### ISSUE TITLE
Cannot debug api server

### ISSUE THREAD

**Issue by chasel** [Countly/countly-server#763]
1. start dashboard & api server
<img width="910" alt="screen shot 2018-12-13 at 15 00 53" src="https://user-images.githubusercontent.com/1614604/49921406-5fec7580-fee8-11e8-9d47-8c211517b679.png">

dashboard and api server access suscessful!

<img width="1061" alt="screen shot 2018-12-13 at 15 01 30" src="https://user-images.githubusercontent.com/1614604/49921480-932f0480-fee8-11e8-9ba1-dbb76ecb0b60.png">

but the url "countly/o/langmap" response 404.

<img width="1115" alt="screen shot 2018-12-13 at 15 01 47" src="https://user-images.githubusercontent.com/1614604/49921717-6c250280-fee9-11e8-855a-5a4360abf08b.png">

2. chrome input the url and add breakpoint in chrome.
<img width="1353" alt="screen shot 2018-12-13 at 15 02 14" src="https://user-images.githubusercontent.com/1614604/49921546-d8ebcd00-fee8-11e8-8e13-9478726f5f1e.png">

the source access successful but debug not work!

how solve it?

nginx configuration is the below:
<img width="638" alt="screen shot 2018-12-13 at 15 10 50" src="https://user-images.githubusercontent.com/1614604/49921676-4e579d80-fee9-11e8-8264-95117b58a75f.png">

**Comment by chasel** [comment]
but I only config one process.
<img width="678" alt="screen shot 2018-12-13 at 15 31 29" src="https://user-images.githubusercontent.com/1614604/49922619-36cde400-feec-11e8-9b79-751a19d8b7ce.png">

the config is wrong?

countly defauly has two process? master and worker?

**Comment by chasel** [comment]
otherwise , I have question.

I'm direct launch dashboard and api server, so have many 404 and 400 error

<img width="1458" alt="screen shot 2018-12-13 at 15 41 44" src="https://user-images.githubusercontent.com/1614604/49923213-bf994f80-feed-11e8-817b-0cf1bbd452d7.png">

how solve it?

**Comment by ar2rsawseen** [comment]
So regarding that, there are multiple possible problems

Port in URL and countly in subdirectory. I think they would need more configuration and I am not sure we provide that capability at all, right now.

But you can try this guide:
https://resources.count.ly/docs/configuring-countly#section-using-countly-from-a-subdirectory

it might be still working, at least partially

**Comment by chasel** [comment]
thanks!
I try it.

**Comment by chasel** [comment]
I can't used supervisor solve it.
solve it by the signaling.

<img width="1054" alt="screen shot 2018-12-14 at 10 39 48" src="https://user-images.githubusercontent.com/1614604/49980135-376a8700-ff8d-11e8-8a7b-35852a8d20d0.png">
<img width="1463" alt="screen shot 2018-12-14 at 10 43 17" src="https://user-images.githubusercontent.com/1614604/49980137-3a657780-ff8d-11e8-8acf-9a7a88d28a48.png">
