### ISSUE TITLE
can you explain machine detail info?

### ISSUE THREAD

**Issue by chasel** [Countly/countly-server#771]
In the https://resources.count.ly/docs/implementation-and-configuration-scenarios document describe:

>  A mid-range server can handle 300+ requests per second (more than 25 million requests per day), which is equivalent to roughly 10.000 users at the same time.

other documents https://resources.count.ly/docs/technical-faq describe:

> In our tests, a high end server can handle several hundreds of events per per second, which is roughly 20.000 concurrent mobile users. For more information, see deployment scenarios for potential installation alternatives. However, do not take this number as a reference as it depends a lot on number of events, network load, configuration, disk speed, RAM size and many other criteria.

can you expplain machine detail profile when you detail "mid-range" and "high end server"?
how much cpu core numbers and memory is mid-range server or high server?

**Comment by ar2rsawseen** [comment]
It mostly depends on data points.
Datapoint is any events or session, or crash, etc sent to server.
You need to anticipate how many datapoints you would collect per month, which is basically

```
monthly users * average sessions * actions you want to track per session = datapoints per month
```

Then you can enter the datapoint per month number here:
https://code.count.ly/helpers.html

And it would show you roughly the server specs you would need

**Comment by gorkem-cetin** [comment]
Hi @chasel could you please ask your questions to our community support forum (https://community.count.ly) , and keep Github for bugs only instead? Thanks! :-)
