### ISSUE TITLE
Proposal: test against Node.js 10 on CI

### ISSUE THREAD

**Issue by DanielRuf** [Countly/countly-server#777]
Shall we test on Node.js as this is the current latest LTS?
https://github.com/Countly/countly-server/blob/master/.travis.yml#L2

**Comment by ronkorving** [comment]
You might as well go straight to 12 now, since that has been released :)

**Comment by ar2rsawseen** [comment]
We never run after the latest immediately, we like to stay 1 version behind 😄

**Comment by ronkorving** [comment]
Doesn't mean you can't test against it ;)

The breaking changes are mostly obscure and you'll likely not run into it. If you do, better to know about it early and not repeat Node 12 anti-patterns. But then again, I do understand you don't want your Travis CI to report problems when you don't consider them problems yet.

**Comment by ar2rsawseen** [comment]
Done here:
https://github.com/Countly/countly-server/pull/1020
