### ISSUE TITLE
Groups or tags

### ISSUE THREAD

**Issue by DanielNagy** [Countly/countly-server#8]
It would be great tobBe able to group applications into groups or categories.

Or alternatively, be able to associate "tags" to applications. That way you can assign more than one tag to a application.

Then be able to filter/select group or tag for viewing.

If appliation number aggregation(issue #7) was implemented, then show aggregated numbers based on a group of applications. Or a application with the specific "tag"

**Comment by ar2rsawseen** [comment]
Current version provide all apps view with ability to filter app names that include provided substring and compare apps. That should fill this gap :)
