### ISSUE TITLE
Summarise Data

### ISSUE THREAD

**Issue by leearmstrong** [Countly/countly-server#84]
Is there anyway to truncate/limit the amount of time you store for an app and delete the rest?

I have certain apps for example that I only want to know the last few weeks of detailed info but keep total user counts etc.  Is this possible?

**Comment by ar2rsawseen** [comment]
Implemented in https://github.com/Countly/countly-server/commit/187132824103cbd20d38babe4a82c95f976d158d and https://github.com/Countly/countly-server/commit/c8d20c1e44f255f14588d1be262960464756870d
