### ISSUE TITLE
app.recordEvent breaks chart

### ISSUE THREAD

**Issue by mt-henry-obein** [Countly/countly-server#845]
### Expected Behavior

Version 19.02
When I click on the date-selector widget I expect no javascript error and the current selection
should be highlight (set as current).

### Current Behavior

An exception is raised and the selected range is not highlighted.

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/47768261/53148470-0e4e1e80-35ee-11e9-899e-334937ba9592.png)

### Possible Solution
```js
<script type='text/javascript'>
    app.recordEvent = function (event) {
        if (Countly && Countly.add_event) {
            Countly.add_event(event);
        }
    };
</script>
```

the script above should be defined if `<% if (!track || track == "GA" && member['global_admin'] || track == "noneGA" && !member['global_admin']) { %>` is true

### Steps to Reproduce (for bugs)

1. create some fake date
2. click on analytics/session menu
3. click on one of the date range

### More Description

The bug is not in the version 18.08.2.

### Your Environment

* Operating System and version: OSX 10.13.6
* Any changes you have made to your instance: no

**Comment by ar2rsawseen** [comment]
Thank you for reporting
Fixed here: https://github.com/Countly/countly-server/commit/2f86762c04efa927fa3b234cf5afd5c727908450
We will release 19.02.1 with the fix soon

**Comment by mt-henry-obein** [comment]
thank you for the prompt fix.
waiting to see the next minor release out.
