### ISSUE TITLE
Ability to delete segments from events

### ISSUE THREAD

**Issue by BlakeGardner** [Countly/countly-server#85]
There are several events in our database that have segments that have many unique values which cause MongoDB to bog down and the analytics dashboard takes forever to load an event screen.

Please add the ability to delete segments from an event to free up space and help with speed issues.

Further reading:

http://support.count.ly/discussions/problems/180-custom-event-report-consumes-too-much-bandwidth-in-1306

**Comment by ar2rsawseen** [comment]
OPs specific issue was resolved and limits are now in place, do we still need a ui to delete specific segments?

**Comment by osoner** [comment]
Deleting segments doesn't free db (since document is already created/allocated) and it is error prone to delete a segment, need to lock the document etc. etc. so closing this.
