### ISSUE TITLE
Possible repeated calls to /session endpoint

### ISSUE THREAD

**Issue by mt-sebastien-robert** [Countly/countly-server#870]
When the session extending mechanism triggers, it also triggers a timeout for the second half of its duration, listening for clicks and mouse moves. When in the middle of the second half of the expiration delay, moving the mouse does:

### Expected behavior
Triggers a single call to the `/session` endpoint.

### Current behavior
Triggers 2 to 3 calls to the `/session` endpoint, with the frontend and the backend on the same machine. Could be a pain on a laggy network and/or with a server under load.

### Possible solution
In the code bellow:

```js
var extendSession = function() {
    /*** SUGGESTED CHANGE HERE ***
    shouldRecordAction = false;
    *** SUGGESTED CHANGE HERE ***/
    $.ajax({
        url: countlyGlobal.path + "/session",
        success: function(result) {
            if (result === "logout") {
                $("#user-logout").click();
            }
            if (result === "login") {
                $("#user-logout").click();
                window.location = "/login";
            }
            else if (result === "success") {
                shouldRecordAction = false;
                var myTimeoutValue = parseInt(countlyGlobal.config.session_timeout) * 1000 * 60;
                if (myTimeoutValue > 2147483647) { //max value used by set timeout function
                    myTimeoutValue = 1800000;//30 minutes
                }
                setTimeout(function() {
                    shouldRecordAction = true;
                }, Math.round(myTimeoutValue / 2));
                resetSessionTimeouts(myTimeoutValue);
            }
        }
        /*** SUGGESTED CHANGE HERE ***
        ,
        error: function() {
            shouldRecordAction = true;
        }
        *** SUGGESTED CHANGE HERE ***/
    });
};

...

$(document).on("click mousemove extend-dashboard-user-session", function() {
    if (shouldRecordAction) {
        extendSession();
    }
});
```

No matter the `/session` always return 200, one is never protected against network failure, checking for errors is always a good thing.

### Steps to reproduce
1. Open the dev tools in the browser on the Network tab (optionally filter on `session`)
2. Set session expiration to 1 minute (the smallest unit of time possible)
3. A bit before reaching 30 seconds, move the mouse like crazy
4. See the Network tab for what score you can get ;)

**Comment by ar2rsawseen** [comment]
This should be fixed here:
https://github.com/Countly/countly-server/pull/897

**Comment by mt-sebastien-robert** [comment]
Thanks @ar2rsawseen and @frknbasaran :)
