### ISSUE TITLE
Cannot set application type to "web"

### ISSUE THREAD

**Issue by adammeyer** [Countly/countly-server#872]
When setting the application type to "web" for an app, it changes to "mobile" on save.

### Expected Behavior

App type to be set to "web".

### Current Behavior

I have tried updating an existing app and creating a new one.  In both cases, the type changes to "Mobile" on save.  I can confirm the web xhr request is sending "web".

### More Description

No errors show in the logs.

### Your Environment

Ubuntu 16.04.6
Countly 19.02.1

**Comment by ar2rsawseen** [comment]
Hello,
and there are no errors in the countly/log/countly-api.log?
mobile app type is the default one.
Also make sure Web plugin is enabled too

**Comment by adammeyer** [comment]
countly/log/countly-api.log is empty, I cleared it before attempting to save again
web plugin is enabled

**Comment by adammeyer** [comment]
Running `countly plugin upgrade web` and `countly restart` resolved the issue.
