### ISSUE TITLE
Ionic CORS issue (content-type is not allowed)

### ISSUE THREAD

**Issue by ingageco** [Countly/countly-server#878]
I'm getting an issue with CORS on the server that i can't seem to workaround. Is this a setting I can change? 

"Access to XMLHttpRequest at 'https://redacted_app_url/i' from origin 'http://localhost' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response."

### Your Environment

* Operating System and version:
* Any changes you have made to your instance: 

Ionic 3
Server was started a couple of days ago via the Countly DO installer. 

Any help? I know generally that CORS issues required server-side changes. I've tried adding some CORS headers in NGINX but im still getting the issue.

**Comment by ar2rsawseen** [comment]
Hello,
Content-type is a simple header and should be always allowed, without any preflight check.
So whatever browser you are using there, is not following standards correctly.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers#Directives

But, I guess, you could add `Access-Control-Allow-Headers: content-type` to Management -> Configurations -> Security -> Additional API HTTP Response headers

**Comment by ingageco** [comment]
Thank you! I didn't see that area in configuration previously.
