### ISSUE TITLE
Python 2.7 issue with meld3 on CentOS 7

### ISSUE THREAD

**Issue by phobos-dthorga** [Countly/countly-server#879]
I'm experiencing the following issue when installing **Countly v19.02.1** on an updated CentOS 7.6:

```DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting supervisor
  Downloading https://files.pythonhosted.org/packages/1a/33/7f93b7fe060ada5c40a653f46f4cbea4f423e019d1a666d0a659d39d85e1/supervisor-4.0.0-py2.py3-none-any.whl (293kB)
Collecting meld3>=1.0.0 (from supervisor)
  Downloading https://files.pythonhosted.org/packages/b6/ae/e6d731e4b9661642c1b20591d8054855bb5b8281cbfa18f561c2edd783f7/meld3-1.0.2-py2.py3-none-any.whl
Installing collected packages: meld3, supervisor
  Found existing installation: meld3 0.6.10
Cannot uninstall 'meld3'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.```
```

The setup process simply aborts at this stage and does not proceed any further. I should note that this setup attempt is on a blank, newly provisioned virtual machine with 4 GB of RAM, 80 GB of HDD space, and 2 vCPUs, so the resources provided should be more than sufficient. The only interaction provided by me is to run the shell script that instantiates the setup wizard under CentOS 7. No changes have been made. Provided below is the `uname` output of the newly provisioned VM:

```Linux countly.gekkofyre.io 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```

Thank you and hopefully this problem can be sorted out soon, as I would like to use this analytics package for our organization, [GekkoFyre Networks](https://gekkofyre.io/), and I prefer to make use of CentOS as the distro of choice where possible.

**Comment by ar2rsawseen** [comment]
Hello,
yes you are correct
it seems supervisor 4.0 was released and it bundles its own newer version of meld with it
so
1) Removing this line from script should fixed it on clean installs
https://github.com/Countly/countly-server/blob/master/bin/countly.install_rhel.sh#L65

But if you already tried running install script then additionally to removing the said line, you should do
2) running `yum remove python-meld3` to remove older package
3) and then running install script again

**Comment by phobos-dthorga** [comment]
Hello @ar2rsawseen,

Thank you kindly for the rapid response, that seemed to have done the trick :) I never thought I'd be the first to report a bug but here we are!

**Comment by gorkem-cetin** [comment]
@phobos-dthorga for someone who has sent his first bug, details of the report look just awesome :-)

**Comment by phobos-dthorga** [comment]
@gorkem-cetin Awwr, thank you!

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-server/pull/882
