### ISSUE TITLE
How to pass readPreference to Mongo when ReplicaSet 

### ISSUE THREAD

**Issue by satnami** [Countly/countly-server#885]
## How to pass readPreference to Mongo when ReplicaSet 

Is there a way to pass readPreference to frontned/api mongoconfigurations when mongo is running on replica set.

**Comment by ar2rsawseen** [comment]
Sure, so from the driver it is an option on MongoClient:
http://mongodb.github.io/node-mongodb-native/3.2/api/MongoClient.html

But you can just provide it as, for example, server option here in config:
https://github.com/Countly/countly-server/blob/master/api/config.sample.js#L58

They were separate before, but now combined in single one for the driver, we have them still separate in config for legacy purposes, but actually server and db options are merged together and passed to driver when establishing connection.
