### ISSUE TITLE
Inbound license clarification

### ISSUE THREAD

**Issue by tmarble** [Countly/countly-server#926]
I understand there are Community and Enterprise editions of count.ly as per https://count.ly/pricing#compare-editions

I have read the FAQ at http://resources.count.ly/docs/licencing-faq

Is it correct to assume that the Enterprise edition uses code from the Community edition?'

In the contribution guidelines https://github.com/Countly/countly-server/blob/master/CONTRIBUTING.md there is no mention of a Contributor Licensing Agreement therefore is it correct to assume that any PR that is merged will be taken under the same license (AGPLv3 + modified section 7) ?

**Comment by gorkem-cetin** [comment]
Hi @tmarble - yes, we expect that any code you contribute to core will be accepted as AGPL v3 + modified section 7.
