### ISSUE TITLE
COUNTLY_CONFIG_API_MONGODB ignored during installation

### ISSUE THREAD

**Issue by Bramzor** [Countly/countly-server#933]
During installation, following errors occur:

```
Installing plugin "video-intelligence-monetization"...
Installing plugin "alerts"...
Installing alerts plugin
Adding alerts patch
Installing plugin "onboarding"...
Processing plugin files for production mode
Preparing production files
{ MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
```

When specifying a custom mongodb url like:
export COUNTLY_CONFIG_API_MONGODB=mongodb://user:pas@mdbcluster.internal:27017/countly

### Expected Behavior
The correct mongodb url should be used when generating countly/api/config.js

### Current Behavior
Errors are thrown and value seems to be ignored?

### Your Environment
Current release running on Ubuntu 18 LTS

**Comment by iartem** [comment]
I think it's not relevant anymore, feel free to reopen in case it is.
