### ISSUE TITLE
Sent user info, but cannot find it in the db

### ISSUE THREAD

**Issue by ningliu** [Countly/countly-server#940]
### Steps:
0. I am using the official sample react native app:
https://github.com/Countly/countly-sdk-react-native-bridge/tree/master/example
1. click "Init", and "Start"
2. click "Send Users Data",
3. when I check the db, 
db.app_users5d09b4c314c803006e160adc.find({name: {$exists: true}})
I get 0 results.

Is there anything I missed?
I confirmed two things: 
1. the app_usersxxxxx collection I checked is the correct one.  I am using AppID in the collection's name.
2. the user details request is made.  and it seems to be correct.
I can see a request is sent to the countly server.  I use a proxy to intercept the requests.
This is the request:
/i?app_key=xxxxxxxxda6f110fd4be63474c7c9ffeb750f720&device_id=B824BFAF-B3E7-4727-8CF8-0BBBD2E02085&timestamp=1562096058285&hour=15&dow=2&tz=-240&sdk_version=19.02&sdk_name=countly-sdk-react-native-bridge-ios&user_details=%7B%22phone%22%3A%22%2B91%20812%20840%202946%22%2C%22gender%22%3A%22F%22%2C%22organization%22%3A%22aeongo%22%2C%22picture%22%3A%22http%3A%5C%2F%5C%2Fwww.trinisofttechnologies.com%5C%2Fimages%5C%2Flogo.png%22%2C%22username%22%3A%22ningliu%22%2C%22email%22%3A%22ningliu%40aeongo.com%22%2C%22byear%22%3A1989%2C%22name%22%3A%22Ning%20Liu%22%7D

### Expected Behavior
In the db, when I run
db.app_users5d09b4c314c803006e160adc.find({name: {$exists: true}})
I expect to see the record I just sent using the mobile example app.

### Current Behavior
In the db, when I run
db.app_users5d09b4c314c803006e160adc.find({name: {$exists: true}})
I got 0 results.

**Comment by ar2rsawseen** [comment]
Hello,
is this on Community Edition?
I think user properties are Enterprise Edition only

**Comment by ningliu** [comment]
Yes, this is Community Edition.
I am evaluating if our company needs an Enterprise Edition.

I read this page, but still have a few questions:
https://resources.count.ly/docs/user-profiles#section-sending-user-profiles-data

1. I understand the Community Edition does not include the "User Profiles" tool, does that mean not only the analytics tool named "User Profiles" is not available, but also the user's data is not stored in the db at all?

2. For Enterprise edition, how do the events request look like?  Will the request for events include "user_details"?
The is a sample request for events in Community Edition:

'app_key': | xxxxxxxxa6f110fd4be63474c7c9ffeb750f720
-- | --
'device_id': | B824BFAF-B3E7-4727-8CF8-0BBBD2E02085
'timestamp': | 1562087633608
'hour': | 13
'dow': | 2
'tz': | -240
'sdk_version': | 19.02
'sdk_name': | countly-sdk-react-native-bridge-ios
'events': | [{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087630452,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087630825,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087631182,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087631527,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087631829,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087632180,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087632533,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087632921,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087633291,"dow":2,"dur":0},{"sum":0,"hour":13,"count":1,"key":"Basic Event IOS3","timestamp":1562087633607,"dow":2,"dur":0}]

I 

This is important for our company, because besides countly, we want to store and process the events in another system.  It is important to know which user the events come from.  So we would like to see each event request has a user identifier associated with it.    Does Enterprise Edition have that?

**Comment by ar2rsawseen** [comment]
Hello,
yes Enterprise has a granular level of data, so you would know each event for which user, etc.
I think you can request a demo/trial of enterprise version, right @gorkem-cetin ?

**Comment by gorkem-cetin** [comment]
Hi @ningliu  - please use https://count.ly/contact in order to contact us and then we will provide you with more information on how to move forward.
