### ISSUE TITLE
Countly fs migrate failing

### ISSUE THREAD

**Issue by Bramzor** [Countly/countly-server#941]
Tried https://resources.count.ly/docs/configuring-countly#section-configure-shared-file-system-between-multiple-countly-server

when running `countly fs migrate fs gridfs` , it fails with:

2019-07-02T21:52:29.404Z: ERROR	[db:read]	Error reading appimages.files {"name":"findOne","args":[{"filename":"5d12bf7a4c8abd079823ac4d.png"},{"projection":{"_id":1}},null]} MongoError: Authentication failed. {"ok":0,"errmsg":"Authentication failed.","code":18,"codeName":"AuthenticationFailed","name":"MongoError"}
Storing file finished 5d12bf7a4c8abd079823ac4d.png { MongoError: Authentication failed.

I did provide permissions for the same user to the countly_fs db:

db.getUsers()
[
	{
		"_id" : "countly.analytics",
		"user" : "analytics",
		"db" : "countly",
		"roles" : [
			{
				"role" : "readWrite",
				"db" : "countly_fs"
			},
			{
				"role" : "readWrite",
				"db" : "countly"
			}
		]
	}
]

Any ideas?

**Comment by ar2rsawseen** [comment]
So countlyFs uses the same config.js that api process uses, the one inside countly/api/config.js
If you added same countly user to that database too, it should have worked.

But I guess here could be a specific how you added it. So not only user matter, but also which database user gets authenticated by.

So I think when adding user this should have worked:

```
use countly
db.createUser({user:"test", pwd:"test123", roles: ["readWrite"]})
use countly_fs
db.createUser({user:"test", pwd:"test123", roles: ["readWrite"]})
```

https://resources.count.ly/docs/securing-mongodb#section-adding-single-user-for-all-countly-databases

**Comment by Bramzor** [comment]
I was using the

> Add your user with read and write permission to specific databases

option but apparently that wasn't working as it should. Now I added the user to each database by creating the same one in all databases and that seems to work.

Not sure why it didn't work with one user that had the role configured. Maybe because that user was not created inside the admin database but under countly?

**Comment by ar2rsawseen** [comment]
Yes, that is possible
You could try putting countly as authDatabase in the options then.
But I guess if it already works, it does not matter anymore

**Comment by Bramzor** [comment]
In api/config.js I'm using a mongodb connection url like: mongodb: "mongodb://analytics:....@mdbcluster.internal:27017/countly"

Which is odd that the same credentials are used in combination with a different database for gridfs for example. Do not think that I can add an authDatabase parameter to the connection url though.

**Comment by ar2rsawseen** [comment]
Yes you can, it is called authSource there:
https://docs.mongodb.com/manual/reference/connection-string/#urioption.authSource

But I am not sure countly db is allowed as authSource, maybe only administrative database is allowed

**Comment by Bramzor** [comment]
Tried by setting authSource to countly with the getUser output from above. But that didn't work. After that I tried the same thing with admin while first adding the users to the admin database but same result.
So only thing that works is creating the user in all the different databases.

**Comment by ar2rsawseen** [comment]
Yeah, as I said it is possible that only administrative database can work as authSource. But at least you have it working, so closing this issue :)
