### ISSUE TITLE
period parameters of Countly API for pageviews not work

### ISSUE THREAD

**Issue by anhph-0561** [Countly/countly-server#943]
Thank you for creating a very awesome and efficient tool, I have used this for 6-months but i had a problems. 

When i am trying to call the countly API for getting pageviews statistic 
http://countly_server/o?method=views&api_key=&app_id=&period=

The 'period' parameter as documentation said that can be: hour, yesterday, month,..

But any value of period will get all the pageviews data from start until now. And with me, this make the request becomes very slow. Does anybody know the solution of that type of request?

**Comment by ar2rsawseen** [comment]
Hello, so it depends on what version of Countly you have and what data you want to fetch.

To get summarized data  for your views (Table which summarizes views for given period). If period is not passed - then it is returned for 30 days.
You have to add action=getTable.

https://my.server.ly/o?method=views&action=getTable&api_key={api_key}&app_id={app_id}&period={period}


To get  graph data you should use:
https://anna.count.ly/o?api_key={api_key}&app_id={app_id}&method=views&action=&period={period}&selectedViews={selectedViews}&segment=&segmentVal=

for selected views there should be passed:
var obj = [{view:{view_id1}, action: {"" or "refresh"}}, {view:{view_id2}, action: {"" or "refresh"}}]
obj = JSON.stringify(oby).

If refresh is passed - then not all data is loaded  - but only data which is received lately.

For graph data period fetched will always be larger than provided (to use graph for previous period too, etc) and will be clipped to full years, as this is how the data is stored in database

**Comment by anhph-0561** [comment]
thank you for your quickly support, but it seems to be the same when i call the api https://my.server.ly/o?method=views&action=getTable&api_key={api_key}&app_id={app_id}&period={period} with any period :(

I want to get the data likes the PageViews annalysis. Does i have to upgrade to premium to have that API?

**Comment by ar2rsawseen** [comment]
No, but you might need to upgrade the server. Which version are you on?

**Comment by anhph-0561** [comment]
my version is 18.08.2. Do i need to update? If i upgrade the server, does the remain data is deleted?

**Comment by ar2rsawseen** [comment]
Yes you should upgrade your server. (There was change in Countly because slow loading of views)
It should be at least 19.02.
Data won't be lost - but if your page is already loading very slow - it might take some time to upgrade

**Comment by ar2rsawseen** [comment]
Assuming this was resolved, please reopen if not :)
