### ISSUE TITLE
No country lookup for IP address

### ISSUE THREAD

**Issue by TimoGatta** [Countly/countly-server#975]
### Current Behavior
Countly is showing all countries of visitors as Unknown. Although x-forwarded-for and x-real-ip are showing the correct IP address in event logs. Therefore I think it's not querying the geoIP DB. I already tried reinstalling countly using [this](https://resources.count.ly/docs/installing-countly-server) guide (Method 1) and updating geoip.

### Steps to Reproduce 
1. [Installation](https://resources.count.ly/docs/installing-countly-server) (using Method 1)
2. [Configuring SSL](https://resources.count.ly/docs/configuring-https-and-ssl) (using letsencrypt)

### Your Environment
* OS: Ubuntu 18.04

**Comment by ar2rsawseen** [comment]
Hello
can you try running
`countly update geoip`

Also the IP addresses you are seeing in your Event Logs, are they normal outside ip addresses, or internal ones?
Maybe some load balancer or server before countly adds its own ip address, and thus every IP address Countly checks is internal one that does not have Country?

**Comment by TimoGatta** [comment]
Hi,

thank you for your answer!

I already tried updating geoip and the IPs in our event logs seem to be the external IPs.
(verified using iplocation.net and a VPN)

**Comment by gorkem-cetin** [comment]
Hi @TimoGatta  - how many users are in this situation?

**Comment by ar2rsawseen** [comment]
Can you enter value `ip` under Management -> Configurations -> Logs -> Debug
and then check the logs, it will have the end ip values that Countly would use

**Comment by TimoGatta** [comment]
@gorkem-cetin 
We are currently developing our service, so there are only a few test users.

@ar2rsawseen 
The IP in "x-forwarded-for" is identical with the one in "x-real-ip" and it's a valid external one.

**Comment by gorkem-cetin** [comment]
@TimoGatta how many users are there ? If you are testing with a couple of users or so, they may already show up as Unknown as mapping is not 100% accurate (mostly around 65-90%).

**Comment by TimoGatta** [comment]
@gorkem-cetin 
Before reinstalling countly we had around 30 unique user, all with an unknown location.

**Comment by ar2rsawseen** [comment]
In overall we cannot reproduce this internally, sorry :)
Maybe these specific ip addresses are not in maxmind lite database? Because that one is used by default with geoip package.

I think you can check it by 
```
cd `countly dir`
node node_modules/geoip-lite/test/geo-lookup.js 127.0.0.1
```

replace 127.0.0.1 with your ip you want to find geolocation for

**Comment by thacoon** [comment]
The IP is correctly identified by the geoip package.

```
$ node node_modules/geoip-lite/test/geo-lookup.js 134.99.174.27                                  
{ range: [ 2254635008, 2254700543 ],                                                                                   
  country: 'DE',                                                                                                       
  region: 'NW',                                                                                                        
  eu: '1',                                                                                                             
  timezone: 'Europe/Berlin',                                                                                           
  city: 'Düsseldorf',                                                                                                  
  ll: [ 51.2283, 6.7938 ],                                                                                             
  metro: 0,                                                                                                            
  area: 200 }                                                                                                          
Startup: 213ms, exec: 7ms
```

In request logs the corresponding log is as following:

Headers:
```

{
  "x-forwarded-for": "134.99.174.27",
  "x-real-ip": "134.99.174.27",
  "host": "127.0.0.1:3001",
  "connection": "close",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0",
  "accept": "*/*",
  "accept-language": "en-US,en;q=0.5",
  "accept-encoding": "gzip, deflate, br",
  "referer": "https://our-url.de/",
  "origin": "https://our-url.de",
  "dnt": "1"
}

Data:

{
  "events": [
    {
      "key": "[CLY]_view",
      "count": 1,
      "segmentation": {
        "name": "/en/about",
        "visit": 1,
        "domain": "our-url.de",
        "view": "/en/about",
        "segment": "Windows"
      },
      "timestamp": 1566645780900,
      "hour": 11,
      "dow": 6
    }
  ],
  "app_key": "XXXX",
  "device_id": "XXX-XXX-XXX-XXX-XXX",
  "sdk_name": "javascript_native_web",
  "sdk_version": "19.02.1",
  "location": "",
  "timestamp": "1566645781400",
  "hour": "11",
  "dow": "6"
}

Response:

{
  "code": 200,
  "body": {
    "result": "Success"
  }
}
```

**Comment by ar2rsawseen** [comment]
I see, so from your SDK request 
"location": "",

Which means location is disabled in SDK implementation explicitly or you have GDPR consent management enabld and there is no consent for location/country for this user
Thus server ignores and does not set any location

So you need to check your SDK implementation.

**Comment by thacoon** [comment]
Thanks, adding `location` to the consent array fixed the issue.

I already have thought that it may have to do with the consent management. However, I was missing an overview of all available consent options and what they mean. If this could be added to the docs it would definitely be helpful. If there is already sth. like this, could you please share the link. I could not find sth. like this.

**Comment by ar2rsawseen** [comment]
There is an SDK development guide, which guides how SDKs should be implemented:
https://resources.count.ly/docs/sdk-development-guide#section-exposing-available-features-for-consent

And there should be SDK specific docs, like this for Web SDK
https://resources.count.ly/docs/countly-sdk-for-web#section-gdpr-consent-management

But this docs are constantly updated, so maybe it was not there, but is now :D
